// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dashboard.proto

/*
Package dashboard is a generated protocol buffer package.

It is generated from these files:
	dashboard.proto

It has these top-level messages:
	GetNodeInfosRequest
	GetNodeInfosResponse
	NodeInfoData
	GetRecentTxListRequest
	GetRecentTxListResponse
	RecentTxListData
	TxListRow
	GetBlockListRequest
	GetBlockListResponse
	BlockData
	BlockRow
	GetRequirementNumByDayRequest
	GetRequirementNumByDayResponse
	RequirementNumByDayData
	GetAllTxNumRequest
	GetAllTxNumResponse
	GetAssetNumByDayRequest
	GetAssetNumByDayResponse
	AssetNumByDayData
	GetAccountNumByDayRequest
	GetAccountNumByDayResponse
	AccountNumByDayData
	GetSumTxAmountRequest
	GetSumTxAmountResponse
	GetTxNumByDayRequest
	GetTxNumByDayResponse
	TxNumByDayData
	Num
	GetTxAmountByDayRequest
	GetTxAmountByDayResponse
	TxAmountByDay
	GetAllTypeTotalRequest
	GetAllTypeTotalResponse
	AllTypeData
*/
package dashboard

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNodeInfosRequest struct {
}

func (m *GetNodeInfosRequest) Reset()                    { *m = GetNodeInfosRequest{} }
func (m *GetNodeInfosRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeInfosRequest) ProtoMessage()               {}
func (*GetNodeInfosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetNodeInfosResponse struct {
	Code int32           `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*NodeInfoData `protobuf:"bytes,2,rep,name=data" json:"data"`
	Msg  string          `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetNodeInfosResponse) Reset()                    { *m = GetNodeInfosResponse{} }
func (m *GetNodeInfosResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeInfosResponse) ProtoMessage()               {}
func (*GetNodeInfosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetNodeInfosResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetNodeInfosResponse) GetData() []*NodeInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetNodeInfosResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type NodeInfoData struct {
	Ip      string `protobuf:"bytes,1,opt,name=ip" json:"ip"`
	Port    string `protobuf:"bytes,2,opt,name=port" json:"port"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address"`
}

func (m *NodeInfoData) Reset()                    { *m = NodeInfoData{} }
func (m *NodeInfoData) String() string            { return proto.CompactTextString(m) }
func (*NodeInfoData) ProtoMessage()               {}
func (*NodeInfoData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeInfoData) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeInfoData) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *NodeInfoData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetRecentTxListRequest struct {
	PageNum  uint64 `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	PageSize uint64 `protobuf:"varint,2,opt,name=pageSize" json:"pageSize"`
	Sort     string `protobuf:"bytes,3,opt,name=sort" json:"sort"`
	Username string `protobuf:"bytes,4,opt,name=username" json:"username"`
}

func (m *GetRecentTxListRequest) Reset()                    { *m = GetRecentTxListRequest{} }
func (m *GetRecentTxListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRecentTxListRequest) ProtoMessage()               {}
func (*GetRecentTxListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRecentTxListRequest) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetRecentTxListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetRecentTxListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *GetRecentTxListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetRecentTxListResponse struct {
	Code int32             `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *RecentTxListData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string            `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetRecentTxListResponse) Reset()                    { *m = GetRecentTxListResponse{} }
func (m *GetRecentTxListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRecentTxListResponse) ProtoMessage()               {}
func (*GetRecentTxListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRecentTxListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRecentTxListResponse) GetData() *RecentTxListData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetRecentTxListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RecentTxListData struct {
	PageNum  uint64       `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	RowCount uint64       `protobuf:"varint,2,opt,name=rowCount" json:"rowCount"`
	Row      []*TxListRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *RecentTxListData) Reset()                    { *m = RecentTxListData{} }
func (m *RecentTxListData) String() string            { return proto.CompactTextString(m) }
func (*RecentTxListData) ProtoMessage()               {}
func (*RecentTxListData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RecentTxListData) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *RecentTxListData) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *RecentTxListData) GetRow() []*TxListRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type TxListRow struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id"`
	From          string `protobuf:"bytes,2,opt,name=from" json:"from"`
	To            string `protobuf:"bytes,3,opt,name=to" json:"to"`
	Price         uint64 `protobuf:"varint,4,opt,name=price" json:"price"`
	AssetType     string `protobuf:"bytes,5,opt,name=asset_type,json=assetType" json:"asset_type"`
	Date          string `protobuf:"bytes,6,opt,name=date" json:"date"`
	BlockId       uint64 `protobuf:"varint,7,opt,name=block_id,json=blockId" json:"block_id"`
}

func (m *TxListRow) Reset()                    { *m = TxListRow{} }
func (m *TxListRow) String() string            { return proto.CompactTextString(m) }
func (*TxListRow) ProtoMessage()               {}
func (*TxListRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TxListRow) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TxListRow) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TxListRow) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TxListRow) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TxListRow) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *TxListRow) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TxListRow) GetBlockId() uint64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

type GetBlockListRequest struct {
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size"`
	PageNum  uint32 `protobuf:"varint,2,opt,name=page_num,json=pageNum" json:"page_num"`
	Sort     string `protobuf:"bytes,3,opt,name=sort" json:"sort"`
}

func (m *GetBlockListRequest) Reset()                    { *m = GetBlockListRequest{} }
func (m *GetBlockListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockListRequest) ProtoMessage()               {}
func (*GetBlockListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetBlockListRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetBlockListRequest) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetBlockListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type GetBlockListResponse struct {
	Code uint32     `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *BlockData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string     `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetBlockListResponse) Reset()                    { *m = GetBlockListResponse{} }
func (m *GetBlockListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockListResponse) ProtoMessage()               {}
func (*GetBlockListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetBlockListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetBlockListResponse) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetBlockListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BlockData struct {
	PageNum  uint64      `protobuf:"varint,1,opt,name=page_num,json=pageNum" json:"page_num"`
	RowCount uint64      `protobuf:"varint,2,opt,name=row_count,json=rowCount" json:"row_count"`
	Row      []*BlockRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *BlockData) Reset()                    { *m = BlockData{} }
func (m *BlockData) String() string            { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()               {}
func (*BlockData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BlockData) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *BlockData) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *BlockData) GetRow() []*BlockRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type BlockRow struct {
	BlockNumber   uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number"`
	BlockHash     string `protobuf:"bytes,2,opt,name=block_hash,json=blockHash" json:"block_hash"`
	PrevBlockHash string `protobuf:"bytes,3,opt,name=prev_block_hash,json=prevBlockHash" json:"prev_block_hash"`
	MerkleRoot    string `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot" json:"merkle_root"`
	TxNum         uint32 `protobuf:"varint,5,opt,name=tx_num,json=txNum" json:"tx_num"`
	Delegate      string `protobuf:"bytes,6,opt,name=delegate" json:"delegate"`
	Timestamp     uint64 `protobuf:"varint,7,opt,name=timestamp" json:"timestamp"`
}

func (m *BlockRow) Reset()                    { *m = BlockRow{} }
func (m *BlockRow) String() string            { return proto.CompactTextString(m) }
func (*BlockRow) ProtoMessage()               {}
func (*BlockRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BlockRow) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockRow) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *BlockRow) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *BlockRow) GetMerkleRoot() string {
	if m != nil {
		return m.MerkleRoot
	}
	return ""
}

func (m *BlockRow) GetTxNum() uint32 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

func (m *BlockRow) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *BlockRow) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetRequirementNumByDayRequest struct {
}

func (m *GetRequirementNumByDayRequest) Reset()                    { *m = GetRequirementNumByDayRequest{} }
func (m *GetRequirementNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequirementNumByDayRequest) ProtoMessage()               {}
func (*GetRequirementNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type GetRequirementNumByDayResponse struct {
	Code int32                      `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*RequirementNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetRequirementNumByDayResponse) Reset()                    { *m = GetRequirementNumByDayResponse{} }
func (m *GetRequirementNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRequirementNumByDayResponse) ProtoMessage()               {}
func (*GetRequirementNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetRequirementNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRequirementNumByDayResponse) GetData() []*RequirementNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequirementNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *RequirementNumByDayData) Reset()                    { *m = RequirementNumByDayData{} }
func (m *RequirementNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*RequirementNumByDayData) ProtoMessage()               {}
func (*RequirementNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RequirementNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RequirementNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAllTxNumRequest struct {
}

func (m *GetAllTxNumRequest) Reset()                    { *m = GetAllTxNumRequest{} }
func (m *GetAllTxNumRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllTxNumRequest) ProtoMessage()               {}
func (*GetAllTxNumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type GetAllTxNumResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *Num  `protobuf:"bytes,2,opt,name=data" json:"data"`
}

func (m *GetAllTxNumResponse) Reset()                    { *m = GetAllTxNumResponse{} }
func (m *GetAllTxNumResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllTxNumResponse) ProtoMessage()               {}
func (*GetAllTxNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetAllTxNumResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAllTxNumResponse) GetData() *Num {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAssetNumByDayRequest struct {
}

func (m *GetAssetNumByDayRequest) Reset()                    { *m = GetAssetNumByDayRequest{} }
func (m *GetAssetNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAssetNumByDayRequest) ProtoMessage()               {}
func (*GetAssetNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetAssetNumByDayResponse struct {
	Code int32                `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*AssetNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetAssetNumByDayResponse) Reset()                    { *m = GetAssetNumByDayResponse{} }
func (m *GetAssetNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAssetNumByDayResponse) ProtoMessage()               {}
func (*GetAssetNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetAssetNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAssetNumByDayResponse) GetData() []*AssetNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AssetNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *AssetNumByDayData) Reset()                    { *m = AssetNumByDayData{} }
func (m *AssetNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*AssetNumByDayData) ProtoMessage()               {}
func (*AssetNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *AssetNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AssetNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAccountNumByDayRequest struct {
}

func (m *GetAccountNumByDayRequest) Reset()                    { *m = GetAccountNumByDayRequest{} }
func (m *GetAccountNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountNumByDayRequest) ProtoMessage()               {}
func (*GetAccountNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type GetAccountNumByDayResponse struct {
	Code int32                  `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*AccountNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetAccountNumByDayResponse) Reset()                    { *m = GetAccountNumByDayResponse{} }
func (m *GetAccountNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountNumByDayResponse) ProtoMessage()               {}
func (*GetAccountNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetAccountNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAccountNumByDayResponse) GetData() []*AccountNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *AccountNumByDayData) Reset()                    { *m = AccountNumByDayData{} }
func (m *AccountNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*AccountNumByDayData) ProtoMessage()               {}
func (*AccountNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *AccountNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AccountNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetSumTxAmountRequest struct {
}

func (m *GetSumTxAmountRequest) Reset()                    { *m = GetSumTxAmountRequest{} }
func (m *GetSumTxAmountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSumTxAmountRequest) ProtoMessage()               {}
func (*GetSumTxAmountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type GetSumTxAmountResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *Num  `protobuf:"bytes,2,opt,name=data" json:"data"`
}

func (m *GetSumTxAmountResponse) Reset()                    { *m = GetSumTxAmountResponse{} }
func (m *GetSumTxAmountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSumTxAmountResponse) ProtoMessage()               {}
func (*GetSumTxAmountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetSumTxAmountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetSumTxAmountResponse) GetData() *Num {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetTxNumByDayRequest struct {
}

func (m *GetTxNumByDayRequest) Reset()                    { *m = GetTxNumByDayRequest{} }
func (m *GetTxNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxNumByDayRequest) ProtoMessage()               {}
func (*GetTxNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type GetTxNumByDayResponse struct {
	Code int32             `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*TxNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetTxNumByDayResponse) Reset()                    { *m = GetTxNumByDayResponse{} }
func (m *GetTxNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxNumByDayResponse) ProtoMessage()               {}
func (*GetTxNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetTxNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxNumByDayResponse) GetData() []*TxNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TxNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *TxNumByDayData) Reset()                    { *m = TxNumByDayData{} }
func (m *TxNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*TxNumByDayData) ProtoMessage()               {}
func (*TxNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *TxNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TxNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Num struct {
	Num int64 `protobuf:"varint,1,opt,name=num" json:"num"`
}

func (m *Num) Reset()                    { *m = Num{} }
func (m *Num) String() string            { return proto.CompactTextString(m) }
func (*Num) ProtoMessage()               {}
func (*Num) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Num) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetTxAmountByDayRequest struct {
}

func (m *GetTxAmountByDayRequest) Reset()                    { *m = GetTxAmountByDayRequest{} }
func (m *GetTxAmountByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxAmountByDayRequest) ProtoMessage()               {}
func (*GetTxAmountByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type GetTxAmountByDayResponse struct {
	Code int32            `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*TxAmountByDay `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetTxAmountByDayResponse) Reset()                    { *m = GetTxAmountByDayResponse{} }
func (m *GetTxAmountByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxAmountByDayResponse) ProtoMessage()               {}
func (*GetTxAmountByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GetTxAmountByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxAmountByDayResponse) GetData() []*TxAmountByDay {
	if m != nil {
		return m.Data
	}
	return nil
}

type TxAmountByDay struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *TxAmountByDay) Reset()                    { *m = TxAmountByDay{} }
func (m *TxAmountByDay) String() string            { return proto.CompactTextString(m) }
func (*TxAmountByDay) ProtoMessage()               {}
func (*TxAmountByDay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *TxAmountByDay) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TxAmountByDay) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAllTypeTotalRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type"`
}

func (m *GetAllTypeTotalRequest) Reset()                    { *m = GetAllTypeTotalRequest{} }
func (m *GetAllTypeTotalRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllTypeTotalRequest) ProtoMessage()               {}
func (*GetAllTypeTotalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *GetAllTypeTotalRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetAllTypeTotalResponse struct {
	Code int32          `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*AllTypeData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetAllTypeTotalResponse) Reset()                    { *m = GetAllTypeTotalResponse{} }
func (m *GetAllTypeTotalResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllTypeTotalResponse) ProtoMessage()               {}
func (*GetAllTypeTotalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *GetAllTypeTotalResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAllTypeTotalResponse) GetData() []*AllTypeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AllTypeData struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type"`
	Total int64  `protobuf:"varint,2,opt,name=total" json:"total"`
}

func (m *AllTypeData) Reset()                    { *m = AllTypeData{} }
func (m *AllTypeData) String() string            { return proto.CompactTextString(m) }
func (*AllTypeData) ProtoMessage()               {}
func (*AllTypeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *AllTypeData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AllTypeData) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNodeInfosRequest)(nil), "GetNodeInfosRequest")
	proto.RegisterType((*GetNodeInfosResponse)(nil), "GetNodeInfosResponse")
	proto.RegisterType((*NodeInfoData)(nil), "NodeInfoData")
	proto.RegisterType((*GetRecentTxListRequest)(nil), "GetRecentTxListRequest")
	proto.RegisterType((*GetRecentTxListResponse)(nil), "GetRecentTxListResponse")
	proto.RegisterType((*RecentTxListData)(nil), "RecentTxListData")
	proto.RegisterType((*TxListRow)(nil), "TxListRow")
	proto.RegisterType((*GetBlockListRequest)(nil), "GetBlockListRequest")
	proto.RegisterType((*GetBlockListResponse)(nil), "GetBlockListResponse")
	proto.RegisterType((*BlockData)(nil), "BlockData")
	proto.RegisterType((*BlockRow)(nil), "BlockRow")
	proto.RegisterType((*GetRequirementNumByDayRequest)(nil), "GetRequirementNumByDayRequest")
	proto.RegisterType((*GetRequirementNumByDayResponse)(nil), "GetRequirementNumByDayResponse")
	proto.RegisterType((*RequirementNumByDayData)(nil), "RequirementNumByDayData")
	proto.RegisterType((*GetAllTxNumRequest)(nil), "GetAllTxNumRequest")
	proto.RegisterType((*GetAllTxNumResponse)(nil), "GetAllTxNumResponse")
	proto.RegisterType((*GetAssetNumByDayRequest)(nil), "GetAssetNumByDayRequest")
	proto.RegisterType((*GetAssetNumByDayResponse)(nil), "GetAssetNumByDayResponse")
	proto.RegisterType((*AssetNumByDayData)(nil), "AssetNumByDayData")
	proto.RegisterType((*GetAccountNumByDayRequest)(nil), "GetAccountNumByDayRequest")
	proto.RegisterType((*GetAccountNumByDayResponse)(nil), "GetAccountNumByDayResponse")
	proto.RegisterType((*AccountNumByDayData)(nil), "AccountNumByDayData")
	proto.RegisterType((*GetSumTxAmountRequest)(nil), "GetSumTxAmountRequest")
	proto.RegisterType((*GetSumTxAmountResponse)(nil), "GetSumTxAmountResponse")
	proto.RegisterType((*GetTxNumByDayRequest)(nil), "GetTxNumByDayRequest")
	proto.RegisterType((*GetTxNumByDayResponse)(nil), "GetTxNumByDayResponse")
	proto.RegisterType((*TxNumByDayData)(nil), "TxNumByDayData")
	proto.RegisterType((*Num)(nil), "Num")
	proto.RegisterType((*GetTxAmountByDayRequest)(nil), "GetTxAmountByDayRequest")
	proto.RegisterType((*GetTxAmountByDayResponse)(nil), "GetTxAmountByDayResponse")
	proto.RegisterType((*TxAmountByDay)(nil), "TxAmountByDay")
	proto.RegisterType((*GetAllTypeTotalRequest)(nil), "GetAllTypeTotalRequest")
	proto.RegisterType((*GetAllTypeTotalResponse)(nil), "GetAllTypeTotalResponse")
	proto.RegisterType((*AllTypeData)(nil), "AllTypeData")
}

func init() { proto.RegisterFile("dashboard.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcf, 0x6e, 0xdb, 0x46,
	0x13, 0x97, 0x4c, 0xd9, 0x31, 0x47, 0x96, 0xed, 0xac, 0x65, 0x9b, 0xa6, 0x13, 0xdb, 0xd9, 0x0f,
	0x09, 0x7c, 0x08, 0xf6, 0xe0, 0xef, 0x50, 0x34, 0x40, 0xd0, 0xfa, 0x0f, 0xa2, 0x1a, 0x08, 0x9c,
	0x82, 0x11, 0x7a, 0x68, 0x0b, 0xa8, 0x94, 0xb8, 0xb6, 0x85, 0x88, 0x5c, 0x86, 0x5c, 0xd5, 0x56,
	0x0f, 0x7d, 0x92, 0x3e, 0x49, 0x1f, 0xa8, 0xcf, 0x51, 0xec, 0x2c, 0x29, 0x71, 0x25, 0x8a, 0x80,
	0x7b, 0xdb, 0x1d, 0xce, 0xec, 0xcc, 0xfc, 0x66, 0xe6, 0xb7, 0x4b, 0xd8, 0x0a, 0xfc, 0xf4, 0xbe,
	0x2f, 0xfc, 0x24, 0x60, 0x71, 0x22, 0xa4, 0xa0, 0xbb, 0xb0, 0xd3, 0xe1, 0xf2, 0x46, 0x04, 0xfc,
	0x3a, 0xba, 0x15, 0xa9, 0xc7, 0xbf, 0x8e, 0x79, 0x2a, 0x69, 0x0f, 0xda, 0xa6, 0x38, 0x8d, 0x45,
	0x94, 0x72, 0x42, 0xa0, 0x31, 0x10, 0x01, 0x77, 0xea, 0x27, 0xf5, 0xd3, 0x55, 0x0f, 0xd7, 0xe4,
	0x15, 0x34, 0x02, 0x5f, 0xfa, 0xce, 0xca, 0x89, 0x75, 0xda, 0x3c, 0x6b, 0xb1, 0xdc, 0xea, 0xca,
	0x97, 0xbe, 0x87, 0x9f, 0xc8, 0x36, 0x58, 0x61, 0x7a, 0xe7, 0x58, 0x27, 0xf5, 0x53, 0xdb, 0x53,
	0x4b, 0xfa, 0x11, 0x36, 0x8a, 0x7a, 0x64, 0x13, 0x56, 0x86, 0x31, 0x1e, 0x6b, 0x7b, 0x2b, 0xc3,
	0x58, 0x39, 0x8a, 0x45, 0x22, 0x9d, 0x15, 0x94, 0xe0, 0x9a, 0x38, 0xf0, 0xcc, 0x0f, 0x82, 0x84,
	0xa7, 0x69, 0x76, 0x52, 0xbe, 0xa5, 0x7f, 0xc2, 0x5e, 0x87, 0x4b, 0x8f, 0x0f, 0x78, 0x24, 0xbb,
	0x8f, 0x1f, 0x87, 0xa9, 0xcc, 0x12, 0x51, 0x36, 0xb1, 0x7f, 0xc7, 0x6f, 0xc6, 0x21, 0x1e, 0xde,
	0xf0, 0xf2, 0x2d, 0x71, 0x61, 0x5d, 0x2d, 0x3f, 0x0f, 0xff, 0xe0, 0xe8, 0xa5, 0xe1, 0x4d, 0xf7,
	0xca, 0x7b, 0xaa, 0xbc, 0x6b, 0x37, 0xb8, 0x56, 0xfa, 0xe3, 0x94, 0x27, 0x91, 0x1f, 0x72, 0xa7,
	0x81, 0xf2, 0xe9, 0x9e, 0xde, 0xc2, 0xfe, 0x82, 0xff, 0x0a, 0xc4, 0x5e, 0x4f, 0x11, 0xab, 0x9f,
	0x36, 0xcf, 0x9e, 0xb3, 0xa2, 0x61, 0x25, 0x6a, 0xb7, 0xb0, 0x3d, 0xaf, 0x5b, 0x9d, 0x61, 0x22,
	0x1e, 0x2e, 0xc5, 0x38, 0x92, 0x79, 0x86, 0xf9, 0x9e, 0xbc, 0x00, 0x2b, 0x11, 0x0f, 0x8e, 0x85,
	0x35, 0x03, 0x96, 0x05, 0x2d, 0x1e, 0x3c, 0x25, 0xa6, 0x7f, 0xd7, 0xc1, 0x9e, 0x8a, 0xc8, 0x6b,
	0xd8, 0x94, 0x89, 0x1f, 0xa5, 0xfe, 0x40, 0x0e, 0x45, 0xd4, 0x1b, 0x06, 0x59, 0x9d, 0x5a, 0x05,
	0xe9, 0x75, 0xa0, 0x32, 0xbd, 0x4d, 0x44, 0x98, 0x97, 0x4c, 0xad, 0x55, 0x59, 0xa5, 0xc8, 0x32,
	0x58, 0x91, 0x82, 0xb4, 0x61, 0x35, 0x4e, 0x86, 0x03, 0x8d, 0x60, 0xc3, 0xd3, 0x1b, 0xf2, 0x12,
	0xc0, 0x4f, 0x53, 0x2e, 0x7b, 0x72, 0x12, 0x73, 0x67, 0x15, 0xb5, 0x6d, 0x94, 0x74, 0x27, 0x31,
	0x42, 0x18, 0xf8, 0x92, 0x3b, 0x6b, 0xfa, 0x60, 0xb5, 0x26, 0x07, 0xb0, 0xde, 0x1f, 0x89, 0xc1,
	0x17, 0x15, 0xcd, 0x33, 0x9d, 0x36, 0xee, 0xaf, 0x03, 0xea, 0x63, 0x4b, 0x5f, 0xa8, 0x5d, 0xb1,
	0x13, 0x0e, 0xc1, 0x56, 0xc0, 0xf4, 0x52, 0x55, 0x70, 0x95, 0x40, 0xab, 0x50, 0xf0, 0x03, 0xdd,
	0x0c, 0xbd, 0x68, 0xac, 0xe3, 0x6f, 0xcd, 0x50, 0x2c, 0xe9, 0x05, 0xfa, 0x2b, 0x8e, 0x47, 0xc1,
	0x45, 0x49, 0xb1, 0x5b, 0x59, 0xb1, 0x8f, 0x8c, 0x62, 0x03, 0x43, 0xab, 0xca, 0x2a, 0xff, 0x06,
	0xf6, 0x54, 0xc9, 0x88, 0x6c, 0xae, 0xbe, 0x87, 0x60, 0x27, 0xe2, 0xa1, 0x37, 0x28, 0x2d, 0xf0,
	0x61, 0xb1, 0xc0, 0xb6, 0xf6, 0x3a, 0xad, 0xef, 0x3f, 0x75, 0x58, 0xcf, 0x25, 0xe4, 0x15, 0x6c,
	0x68, 0x28, 0xa3, 0x71, 0xd8, 0xe7, 0x49, 0xe6, 0xa5, 0x89, 0xb2, 0x1b, 0x14, 0xa9, 0x02, 0x69,
	0x95, 0x7b, 0x3f, 0xbd, 0xcf, 0x0a, 0x6c, 0xa3, 0xe4, 0x07, 0x3f, 0xbd, 0x27, 0x6f, 0x60, 0x2b,
	0x4e, 0xf8, 0xef, 0xbd, 0x82, 0x8e, 0x4e, 0xa7, 0xa5, 0xc4, 0x17, 0x53, 0xbd, 0x63, 0x68, 0x86,
	0x3c, 0xf9, 0x32, 0xe2, 0xbd, 0x44, 0x08, 0x99, 0x4d, 0x11, 0x68, 0x91, 0x27, 0x84, 0x24, 0xbb,
	0xb0, 0x26, 0x1f, 0x31, 0xd5, 0x55, 0x44, 0x70, 0x55, 0x3e, 0x66, 0x8d, 0x1c, 0xf0, 0x11, 0xbf,
	0x9b, 0x35, 0xc1, 0x74, 0x4f, 0x5e, 0x80, 0x2d, 0x87, 0x21, 0x4f, 0xa5, 0x1f, 0xc6, 0x59, 0x27,
	0xcc, 0x04, 0xf4, 0x18, 0x5e, 0xe2, 0x60, 0x7e, 0x1d, 0x0f, 0x13, 0x1e, 0xf2, 0x48, 0xde, 0x8c,
	0xc3, 0x8b, 0xc9, 0x95, 0x3f, 0xc9, 0x89, 0xae, 0x0f, 0x47, 0xcb, 0x14, 0x2a, 0x06, 0xf8, 0xad,
	0x41, 0x79, 0x0e, 0x2b, 0xb1, 0x9f, 0x55, 0x98, 0x5e, 0xc2, 0xfe, 0x12, 0x05, 0x75, 0xb8, 0x0a,
	0x16, 0x0f, 0xb7, 0x3c, 0x5c, 0xab, 0x19, 0x99, 0x95, 0xd4, 0xf2, 0xf4, 0x86, 0xb6, 0x81, 0x74,
	0xb8, 0x3c, 0x1f, 0x8d, 0xba, 0x0a, 0x92, 0x3c, 0xfc, 0x4b, 0xec, 0xf5, 0x99, 0xb4, 0x22, 0x66,
	0xc7, 0xe8, 0xc3, 0x06, 0x53, 0xfa, 0x3a, 0xbe, 0x03, 0x64, 0xaf, 0x73, 0x35, 0x6f, 0xf3, 0xf0,
	0xfc, 0x04, 0xce, 0xe2, 0xa7, 0x0a, 0x27, 0x6f, 0x0c, 0x60, 0x08, 0x33, 0x2c, 0x0b, 0x90, 0xbc,
	0x87, 0xe7, 0x0b, 0x9f, 0x9e, 0x00, 0xc6, 0x21, 0x1c, 0xa8, 0xb0, 0x06, 0xb8, 0x9b, 0x8f, 0xf9,
	0x67, 0x70, 0xcb, 0x3e, 0x56, 0x44, 0x7d, 0x6a, 0x44, 0xdd, 0x66, 0x73, 0xb6, 0x85, 0xb8, 0xbf,
	0x83, 0x9d, 0x92, 0x8f, 0x4f, 0x88, 0x7c, 0x1f, 0x76, 0x3b, 0x5c, 0x7e, 0x1e, 0x87, 0xdd, 0xc7,
	0xf3, 0x50, 0x49, 0xf2, 0xa8, 0x3f, 0xe0, 0x15, 0x66, 0x7c, 0xf8, 0x4f, 0xc5, 0xdc, 0x43, 0x6a,
	0xc2, 0x76, 0x30, 0x50, 0xf9, 0x11, 0x1d, 0x17, 0xe5, 0x15, 0xc7, 0xff, 0xcf, 0x00, 0x64, 0x8b,
	0xcd, 0xcc, 0x0a, 0x58, 0xbc, 0x83, 0x4d, 0x53, 0xfe, 0x24, 0x18, 0x2c, 0x35, 0xd8, 0xdb, 0x60,
	0xe5, 0xbc, 0x66, 0x79, 0x6a, 0x99, 0xf5, 0x62, 0x8e, 0x81, 0x91, 0x81, 0x87, 0xbd, 0x38, 0xf7,
	0xa9, 0x22, 0x09, 0x6a, 0x24, 0xb1, 0xc9, 0x4c, 0x4b, 0x9d, 0xc3, 0xb7, 0xd0, 0x32, 0xc4, 0x4f,
	0x48, 0xe1, 0x2d, 0x16, 0x4c, 0x8d, 0xde, 0x24, 0xe6, 0x5d, 0x21, 0xfd, 0x51, 0x7e, 0xd3, 0xa8,
	0x33, 0xd4, 0x45, 0xa6, 0x6f, 0x49, 0x5c, 0xd3, 0x4f, 0x7a, 0xc6, 0x0c, 0xed, 0x8a, 0xd8, 0x4f,
	0x8c, 0xd8, 0x37, 0x58, 0x66, 0x58, 0x40, 0xff, 0x1b, 0x68, 0x16, 0x84, 0x65, 0x3e, 0x55, 0xdc,
	0x52, 0x79, 0xca, 0xe3, 0xc6, 0xcd, 0xd9, 0x5f, 0x6b, 0x60, 0x5f, 0xe5, 0xaf, 0x40, 0xf2, 0x1e,
	0x36, 0x8a, 0x37, 0x19, 0x69, 0xb3, 0x92, 0xbb, 0xd3, 0xdd, 0x65, 0x65, 0xd7, 0x1d, 0xad, 0x65,
	0xe6, 0xd3, 0x77, 0xa2, 0x36, 0x9f, 0x7f, 0x4d, 0x6a, 0xf3, 0x85, 0xc7, 0x24, 0xad, 0x91, 0x0f,
	0xb0, 0x35, 0xf7, 0x6e, 0x22, 0xfb, 0xac, 0xfc, 0x25, 0xe7, 0x3a, 0x6c, 0xc9, 0x13, 0x8b, 0xd6,
	0xc8, 0x2f, 0xd9, 0xfb, 0x6f, 0x81, 0x64, 0xc9, 0x11, 0xab, 0xe4, 0x7f, 0xf7, 0x98, 0x55, 0xd3,
	0x3f, 0xad, 0x91, 0x77, 0xd0, 0x2c, 0x70, 0x2c, 0xd9, 0x61, 0x8b, 0x3c, 0xec, 0xb6, 0x59, 0x09,
	0x0d, 0xd3, 0x1a, 0xb9, 0x86, 0xed, 0x79, 0xfe, 0x24, 0x98, 0x48, 0x19, 0xdb, 0xba, 0x07, 0x6c,
	0x19, 0xd9, 0xd2, 0x1a, 0xf9, 0xa4, 0x2f, 0x00, 0x93, 0x7d, 0x88, 0xcb, 0x96, 0x12, 0xa1, 0x7b,
	0xc8, 0x96, 0xf3, 0x20, 0xad, 0x91, 0x4b, 0xd8, 0x34, 0x19, 0x87, 0xec, 0xb1, 0x52, 0x6e, 0x72,
	0xf7, 0x59, 0x39, 0x35, 0xd1, 0x1a, 0xf9, 0x1e, 0x5a, 0x06, 0xad, 0x10, 0xac, 0xf5, 0x02, 0xfd,
	0xb8, 0x7b, 0xac, 0x94, 0x7d, 0x68, 0x8d, 0x74, 0x10, 0x22, 0x73, 0x0a, 0x1d, 0xb6, 0x84, 0x04,
	0x34, 0x44, 0xe5, 0x1c, 0x70, 0x85, 0xcd, 0x54, 0x1c, 0x31, 0xdd, 0x4c, 0x25, 0x23, 0xaa, 0x9b,
	0xa9, 0x6c, 0x1a, 0xfb, 0x6b, 0xf8, 0x5f, 0xf4, 0xff, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4e,
	0xe6, 0x04, 0x48, 0x2a, 0x0d, 0x00, 0x00,
}
