// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dashboard.proto

/*
Package dashboard is a generated protocol buffer package.

It is generated from these files:
	dashboard.proto

It has these top-level messages:
	GetNodeInfosRequest
	GetNodeInfosResponse
	NodeInfoData
	Position
	GetTxListRequest
	GetTxListResponse
	TxListData
	Tx
	GetBlockListRequest
	GetBlockListResponse
	BlockData
	Block
	GetBlockInfoRequest
	GetBlockInfoResponse
	BlockInfoData
	TxList
	GetRequirementNumByDayRequest
	GetRequirementNumByDayResponse
	RequirementNumByDayData
	GetTxNumRequest
	GetTxNumResponse
	GetAssetNumByDayRequest
	GetAssetNumByDayResponse
	AssetNumByDayData
	GetAccountNumByDayRequest
	GetAccountNumByDayResponse
	AccountNumByDayData
	GetTxAmountRequest
	GetTxAmountResponse
	GetTxNumByDayRequest
	GetTxNumByDayResponse
	TxNumByDayData
	Num
	GetTxAmountByDayRequest
	GetTxAmountByDayResponse
	TxAmountByDay
	GetAllTypeTotalRequest
	GetAllTypeTotalResponse
	AllTypeData
*/
package dashboard

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNodeInfosRequest struct {
}

func (m *GetNodeInfosRequest) Reset()                    { *m = GetNodeInfosRequest{} }
func (m *GetNodeInfosRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeInfosRequest) ProtoMessage()               {}
func (*GetNodeInfosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetNodeInfosResponse struct {
	Code int32           `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*NodeInfoData `protobuf:"bytes,2,rep,name=data" json:"data"`
	Msg  string          `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetNodeInfosResponse) Reset()                    { *m = GetNodeInfosResponse{} }
func (m *GetNodeInfosResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeInfosResponse) ProtoMessage()               {}
func (*GetNodeInfosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetNodeInfosResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetNodeInfosResponse) GetData() []*NodeInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetNodeInfosResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type NodeInfoData struct {
	Ip       string    `protobuf:"bytes,1,opt,name=ip" json:"ip"`
	Port     string    `protobuf:"bytes,2,opt,name=port" json:"port"`
	Position *Position `protobuf:"bytes,3,opt,name=position" json:"position"`
}

func (m *NodeInfoData) Reset()                    { *m = NodeInfoData{} }
func (m *NodeInfoData) String() string            { return proto.CompactTextString(m) }
func (*NodeInfoData) ProtoMessage()               {}
func (*NodeInfoData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeInfoData) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeInfoData) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *NodeInfoData) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Position struct {
	Longitude float32 `protobuf:"fixed32,1,opt,name=longitude" json:"longitude"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=latitude" json:"latitude"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Position) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Position) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type GetTxListRequest struct {
	PageNum  uint64 `protobuf:"varint,1,opt,name=page_num,json=pageNum" json:"page_num"`
	PageSize uint64 `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size"`
	Sort     string `protobuf:"bytes,3,opt,name=sort" json:"sort"`
	Username string `protobuf:"bytes,4,opt,name=username" json:"username"`
}

func (m *GetTxListRequest) Reset()                    { *m = GetTxListRequest{} }
func (m *GetTxListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxListRequest) ProtoMessage()               {}
func (*GetTxListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetTxListRequest) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetTxListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetTxListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *GetTxListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetTxListResponse struct {
	Code int32       `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *TxListData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string      `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetTxListResponse) Reset()                    { *m = GetTxListResponse{} }
func (m *GetTxListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxListResponse) ProtoMessage()               {}
func (*GetTxListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetTxListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxListResponse) GetData() *TxListData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetTxListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TxListData struct {
	PageNum  uint32 `protobuf:"varint,1,opt,name=page_num,json=pageNum" json:"page_num"`
	RowCount uint32 `protobuf:"varint,2,opt,name=row_count,json=rowCount" json:"row_count"`
	Row      []*Tx  `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *TxListData) Reset()                    { *m = TxListData{} }
func (m *TxListData) String() string            { return proto.CompactTextString(m) }
func (*TxListData) ProtoMessage()               {}
func (*TxListData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TxListData) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *TxListData) GetRowCount() uint32 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *TxListData) GetRow() []*Tx {
	if m != nil {
		return m.Row
	}
	return nil
}

type Tx struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id"`
	From          string `protobuf:"bytes,2,opt,name=from" json:"from"`
	To            string `protobuf:"bytes,3,opt,name=to" json:"to"`
	Price         uint64 `protobuf:"varint,4,opt,name=price" json:"price"`
	AssetId       string `protobuf:"bytes,5,opt,name=asset_id,json=assetId" json:"asset_id"`
	AssetName     string `protobuf:"bytes,6,opt,name=asset_name,json=assetName" json:"asset_name"`
	AssetType     uint64 `protobuf:"varint,7,opt,name=asset_type,json=assetType" json:"asset_type"`
	Timestamp     uint64 `protobuf:"varint,8,opt,name=timestamp" json:"timestamp"`
	BlockNumber   uint32 `protobuf:"varint,9,opt,name=block_number,json=blockNumber" json:"block_number"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Tx) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Tx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Tx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Tx) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Tx) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Tx) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *Tx) GetAssetType() uint64 {
	if m != nil {
		return m.AssetType
	}
	return 0
}

func (m *Tx) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Tx) GetBlockNumber() uint32 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type GetBlockListRequest struct {
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size"`
	PageNum  uint32 `protobuf:"varint,2,opt,name=page_num,json=pageNum" json:"page_num"`
	Sort     string `protobuf:"bytes,3,opt,name=sort" json:"sort"`
}

func (m *GetBlockListRequest) Reset()                    { *m = GetBlockListRequest{} }
func (m *GetBlockListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockListRequest) ProtoMessage()               {}
func (*GetBlockListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetBlockListRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetBlockListRequest) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetBlockListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type GetBlockListResponse struct {
	Code uint32     `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *BlockData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string     `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetBlockListResponse) Reset()                    { *m = GetBlockListResponse{} }
func (m *GetBlockListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockListResponse) ProtoMessage()               {}
func (*GetBlockListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetBlockListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetBlockListResponse) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetBlockListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BlockData struct {
	PageNum  uint64   `protobuf:"varint,1,opt,name=page_num,json=pageNum" json:"page_num"`
	RowCount uint64   `protobuf:"varint,2,opt,name=row_count,json=rowCount" json:"row_count"`
	Row      []*Block `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *BlockData) Reset()                    { *m = BlockData{} }
func (m *BlockData) String() string            { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()               {}
func (*BlockData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BlockData) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *BlockData) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *BlockData) GetRow() []*Block {
	if m != nil {
		return m.Row
	}
	return nil
}

type Block struct {
	BlockNumber   uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number"`
	BlockHash     string `protobuf:"bytes,2,opt,name=block_hash,json=blockHash" json:"block_hash"`
	PrevBlockHash string `protobuf:"bytes,3,opt,name=prev_block_hash,json=prevBlockHash" json:"prev_block_hash"`
	MerkleRoot    string `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot" json:"merkle_root"`
	TxNum         uint32 `protobuf:"varint,5,opt,name=tx_num,json=txNum" json:"tx_num"`
	Delegate      string `protobuf:"bytes,6,opt,name=delegate" json:"delegate"`
	DelegateSign  string `protobuf:"bytes,7,opt,name=delegate_sign,json=delegateSign" json:"delegate_sign"`
	Timestamp     uint64 `protobuf:"varint,8,opt,name=timestamp" json:"timestamp"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Block) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Block) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetMerkleRoot() string {
	if m != nil {
		return m.MerkleRoot
	}
	return ""
}

func (m *Block) GetTxNum() uint32 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

func (m *Block) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *Block) GetDelegateSign() string {
	if m != nil {
		return m.DelegateSign
	}
	return ""
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetBlockInfoRequest struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number"`
}

func (m *GetBlockInfoRequest) Reset()                    { *m = GetBlockInfoRequest{} }
func (m *GetBlockInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockInfoRequest) ProtoMessage()               {}
func (*GetBlockInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetBlockInfoRequest) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type GetBlockInfoResponse struct {
	Code int32          `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *BlockInfoData `protobuf:"bytes,2,opt,name=data" json:"data"`
}

func (m *GetBlockInfoResponse) Reset()                    { *m = GetBlockInfoResponse{} }
func (m *GetBlockInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockInfoResponse) ProtoMessage()               {}
func (*GetBlockInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetBlockInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetBlockInfoResponse) GetData() *BlockInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockInfoData struct {
	Block  *Block    `protobuf:"bytes,1,opt,name=block" json:"block"`
	TxList []*TxList `protobuf:"bytes,2,rep,name=tx_list,json=txList" json:"tx_list"`
}

func (m *BlockInfoData) Reset()                    { *m = BlockInfoData{} }
func (m *BlockInfoData) String() string            { return proto.CompactTextString(m) }
func (*BlockInfoData) ProtoMessage()               {}
func (*BlockInfoData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BlockInfoData) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockInfoData) GetTxList() []*TxList {
	if m != nil {
		return m.TxList
	}
	return nil
}

type TxList struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id"`
	SequenceNum   uint32 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum" json:"sequence_num"`
	CursorNum     uint32 `protobuf:"varint,3,opt,name=cursor_num,json=cursorNum" json:"cursor_num"`
	CursorLabel   uint32 `protobuf:"varint,4,opt,name=cursor_label,json=cursorLabel" json:"cursor_label"`
	Lifetime      uint64 `protobuf:"varint,5,opt,name=lifetime" json:"lifetime"`
	Sender        string `protobuf:"bytes,6,opt,name=sender" json:"sender"`
	Contract      string `protobuf:"bytes,7,opt,name=contract" json:"contract"`
	Method        string `protobuf:"bytes,8,opt,name=method" json:"method"`
	Param         string `protobuf:"bytes,9,opt,name=param" json:"param"`
	SigAlg        uint32 `protobuf:"varint,10,opt,name=sig_alg,json=sigAlg" json:"sig_alg"`
	Signature     string `protobuf:"bytes,11,opt,name=signature" json:"signature"`
	CreateTime    uint64 `protobuf:"varint,12,opt,name=create_time,json=createTime" json:"create_time"`
}

func (m *TxList) Reset()                    { *m = TxList{} }
func (m *TxList) String() string            { return proto.CompactTextString(m) }
func (*TxList) ProtoMessage()               {}
func (*TxList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TxList) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TxList) GetSequenceNum() uint32 {
	if m != nil {
		return m.SequenceNum
	}
	return 0
}

func (m *TxList) GetCursorNum() uint32 {
	if m != nil {
		return m.CursorNum
	}
	return 0
}

func (m *TxList) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *TxList) GetLifetime() uint64 {
	if m != nil {
		return m.Lifetime
	}
	return 0
}

func (m *TxList) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *TxList) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *TxList) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TxList) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *TxList) GetSigAlg() uint32 {
	if m != nil {
		return m.SigAlg
	}
	return 0
}

func (m *TxList) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *TxList) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type GetRequirementNumByDayRequest struct {
}

func (m *GetRequirementNumByDayRequest) Reset()                    { *m = GetRequirementNumByDayRequest{} }
func (m *GetRequirementNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequirementNumByDayRequest) ProtoMessage()               {}
func (*GetRequirementNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetRequirementNumByDayResponse struct {
	Code int32                      `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*RequirementNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetRequirementNumByDayResponse) Reset()                    { *m = GetRequirementNumByDayResponse{} }
func (m *GetRequirementNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRequirementNumByDayResponse) ProtoMessage()               {}
func (*GetRequirementNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetRequirementNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRequirementNumByDayResponse) GetData() []*RequirementNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequirementNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *RequirementNumByDayData) Reset()                    { *m = RequirementNumByDayData{} }
func (m *RequirementNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*RequirementNumByDayData) ProtoMessage()               {}
func (*RequirementNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *RequirementNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RequirementNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetTxNumRequest struct {
}

func (m *GetTxNumRequest) Reset()                    { *m = GetTxNumRequest{} }
func (m *GetTxNumRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxNumRequest) ProtoMessage()               {}
func (*GetTxNumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type GetTxNumResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *Num  `protobuf:"bytes,2,opt,name=data" json:"data"`
}

func (m *GetTxNumResponse) Reset()                    { *m = GetTxNumResponse{} }
func (m *GetTxNumResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxNumResponse) ProtoMessage()               {}
func (*GetTxNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetTxNumResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxNumResponse) GetData() *Num {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAssetNumByDayRequest struct {
}

func (m *GetAssetNumByDayRequest) Reset()                    { *m = GetAssetNumByDayRequest{} }
func (m *GetAssetNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAssetNumByDayRequest) ProtoMessage()               {}
func (*GetAssetNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type GetAssetNumByDayResponse struct {
	Code int32                `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*AssetNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetAssetNumByDayResponse) Reset()                    { *m = GetAssetNumByDayResponse{} }
func (m *GetAssetNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAssetNumByDayResponse) ProtoMessage()               {}
func (*GetAssetNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetAssetNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAssetNumByDayResponse) GetData() []*AssetNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AssetNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *AssetNumByDayData) Reset()                    { *m = AssetNumByDayData{} }
func (m *AssetNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*AssetNumByDayData) ProtoMessage()               {}
func (*AssetNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *AssetNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AssetNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAccountNumByDayRequest struct {
}

func (m *GetAccountNumByDayRequest) Reset()                    { *m = GetAccountNumByDayRequest{} }
func (m *GetAccountNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountNumByDayRequest) ProtoMessage()               {}
func (*GetAccountNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type GetAccountNumByDayResponse struct {
	Code int32                  `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*AccountNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetAccountNumByDayResponse) Reset()                    { *m = GetAccountNumByDayResponse{} }
func (m *GetAccountNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountNumByDayResponse) ProtoMessage()               {}
func (*GetAccountNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetAccountNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAccountNumByDayResponse) GetData() []*AccountNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *AccountNumByDayData) Reset()                    { *m = AccountNumByDayData{} }
func (m *AccountNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*AccountNumByDayData) ProtoMessage()               {}
func (*AccountNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *AccountNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AccountNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetTxAmountRequest struct {
}

func (m *GetTxAmountRequest) Reset()                    { *m = GetTxAmountRequest{} }
func (m *GetTxAmountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxAmountRequest) ProtoMessage()               {}
func (*GetTxAmountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type GetTxAmountResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *Num  `protobuf:"bytes,2,opt,name=data" json:"data"`
}

func (m *GetTxAmountResponse) Reset()                    { *m = GetTxAmountResponse{} }
func (m *GetTxAmountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxAmountResponse) ProtoMessage()               {}
func (*GetTxAmountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *GetTxAmountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxAmountResponse) GetData() *Num {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetTxNumByDayRequest struct {
}

func (m *GetTxNumByDayRequest) Reset()                    { *m = GetTxNumByDayRequest{} }
func (m *GetTxNumByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxNumByDayRequest) ProtoMessage()               {}
func (*GetTxNumByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type GetTxNumByDayResponse struct {
	Code int32             `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*TxNumByDayData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetTxNumByDayResponse) Reset()                    { *m = GetTxNumByDayResponse{} }
func (m *GetTxNumByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxNumByDayResponse) ProtoMessage()               {}
func (*GetTxNumByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GetTxNumByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxNumByDayResponse) GetData() []*TxNumByDayData {
	if m != nil {
		return m.Data
	}
	return nil
}

type TxNumByDayData struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *TxNumByDayData) Reset()                    { *m = TxNumByDayData{} }
func (m *TxNumByDayData) String() string            { return proto.CompactTextString(m) }
func (*TxNumByDayData) ProtoMessage()               {}
func (*TxNumByDayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *TxNumByDayData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TxNumByDayData) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Num struct {
	Num int64 `protobuf:"varint,1,opt,name=num" json:"num"`
}

func (m *Num) Reset()                    { *m = Num{} }
func (m *Num) String() string            { return proto.CompactTextString(m) }
func (*Num) ProtoMessage()               {}
func (*Num) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *Num) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetTxAmountByDayRequest struct {
}

func (m *GetTxAmountByDayRequest) Reset()                    { *m = GetTxAmountByDayRequest{} }
func (m *GetTxAmountByDayRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxAmountByDayRequest) ProtoMessage()               {}
func (*GetTxAmountByDayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type GetTxAmountByDayResponse struct {
	Code int32            `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*TxAmountByDay `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetTxAmountByDayResponse) Reset()                    { *m = GetTxAmountByDayResponse{} }
func (m *GetTxAmountByDayResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTxAmountByDayResponse) ProtoMessage()               {}
func (*GetTxAmountByDayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *GetTxAmountByDayResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTxAmountByDayResponse) GetData() []*TxAmountByDay {
	if m != nil {
		return m.Data
	}
	return nil
}

type TxAmountByDay struct {
	Time  int64 `protobuf:"varint,1,opt,name=time" json:"time"`
	Count int64 `protobuf:"varint,2,opt,name=count" json:"count"`
}

func (m *TxAmountByDay) Reset()                    { *m = TxAmountByDay{} }
func (m *TxAmountByDay) String() string            { return proto.CompactTextString(m) }
func (*TxAmountByDay) ProtoMessage()               {}
func (*TxAmountByDay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *TxAmountByDay) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TxAmountByDay) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetAllTypeTotalRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type"`
}

func (m *GetAllTypeTotalRequest) Reset()                    { *m = GetAllTypeTotalRequest{} }
func (m *GetAllTypeTotalRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllTypeTotalRequest) ProtoMessage()               {}
func (*GetAllTypeTotalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *GetAllTypeTotalRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetAllTypeTotalResponse struct {
	Code int32          `protobuf:"varint,1,opt,name=code" json:"code"`
	Data []*AllTypeData `protobuf:"bytes,2,rep,name=data" json:"data"`
}

func (m *GetAllTypeTotalResponse) Reset()                    { *m = GetAllTypeTotalResponse{} }
func (m *GetAllTypeTotalResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllTypeTotalResponse) ProtoMessage()               {}
func (*GetAllTypeTotalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *GetAllTypeTotalResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAllTypeTotalResponse) GetData() []*AllTypeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AllTypeData struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type"`
	Total int64  `protobuf:"varint,2,opt,name=total" json:"total"`
}

func (m *AllTypeData) Reset()                    { *m = AllTypeData{} }
func (m *AllTypeData) String() string            { return proto.CompactTextString(m) }
func (*AllTypeData) ProtoMessage()               {}
func (*AllTypeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *AllTypeData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AllTypeData) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNodeInfosRequest)(nil), "GetNodeInfosRequest")
	proto.RegisterType((*GetNodeInfosResponse)(nil), "GetNodeInfosResponse")
	proto.RegisterType((*NodeInfoData)(nil), "NodeInfoData")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*GetTxListRequest)(nil), "GetTxListRequest")
	proto.RegisterType((*GetTxListResponse)(nil), "GetTxListResponse")
	proto.RegisterType((*TxListData)(nil), "TxListData")
	proto.RegisterType((*Tx)(nil), "Tx")
	proto.RegisterType((*GetBlockListRequest)(nil), "GetBlockListRequest")
	proto.RegisterType((*GetBlockListResponse)(nil), "GetBlockListResponse")
	proto.RegisterType((*BlockData)(nil), "BlockData")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*GetBlockInfoRequest)(nil), "GetBlockInfoRequest")
	proto.RegisterType((*GetBlockInfoResponse)(nil), "GetBlockInfoResponse")
	proto.RegisterType((*BlockInfoData)(nil), "BlockInfoData")
	proto.RegisterType((*TxList)(nil), "TxList")
	proto.RegisterType((*GetRequirementNumByDayRequest)(nil), "GetRequirementNumByDayRequest")
	proto.RegisterType((*GetRequirementNumByDayResponse)(nil), "GetRequirementNumByDayResponse")
	proto.RegisterType((*RequirementNumByDayData)(nil), "RequirementNumByDayData")
	proto.RegisterType((*GetTxNumRequest)(nil), "GetTxNumRequest")
	proto.RegisterType((*GetTxNumResponse)(nil), "GetTxNumResponse")
	proto.RegisterType((*GetAssetNumByDayRequest)(nil), "GetAssetNumByDayRequest")
	proto.RegisterType((*GetAssetNumByDayResponse)(nil), "GetAssetNumByDayResponse")
	proto.RegisterType((*AssetNumByDayData)(nil), "AssetNumByDayData")
	proto.RegisterType((*GetAccountNumByDayRequest)(nil), "GetAccountNumByDayRequest")
	proto.RegisterType((*GetAccountNumByDayResponse)(nil), "GetAccountNumByDayResponse")
	proto.RegisterType((*AccountNumByDayData)(nil), "AccountNumByDayData")
	proto.RegisterType((*GetTxAmountRequest)(nil), "GetTxAmountRequest")
	proto.RegisterType((*GetTxAmountResponse)(nil), "GetTxAmountResponse")
	proto.RegisterType((*GetTxNumByDayRequest)(nil), "GetTxNumByDayRequest")
	proto.RegisterType((*GetTxNumByDayResponse)(nil), "GetTxNumByDayResponse")
	proto.RegisterType((*TxNumByDayData)(nil), "TxNumByDayData")
	proto.RegisterType((*Num)(nil), "Num")
	proto.RegisterType((*GetTxAmountByDayRequest)(nil), "GetTxAmountByDayRequest")
	proto.RegisterType((*GetTxAmountByDayResponse)(nil), "GetTxAmountByDayResponse")
	proto.RegisterType((*TxAmountByDay)(nil), "TxAmountByDay")
	proto.RegisterType((*GetAllTypeTotalRequest)(nil), "GetAllTypeTotalRequest")
	proto.RegisterType((*GetAllTypeTotalResponse)(nil), "GetAllTypeTotalResponse")
	proto.RegisterType((*AllTypeData)(nil), "AllTypeData")
}

func init() { proto.RegisterFile("dashboard.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x76, 0x6c, 0xc7, 0xb1, 0xce, 0x76, 0x5e, 0xd8, 0xbc, 0x28, 0xee, 0x4b, 0x12, 0x16, 0x2d,
	0xf2, 0xa1, 0x20, 0xb0, 0x6e, 0xc0, 0xb6, 0x02, 0xc5, 0xfa, 0x12, 0x20, 0x0b, 0x50, 0xb8, 0x85,
	0x1a, 0x0c, 0x58, 0xbb, 0xc1, 0x60, 0x6c, 0xd6, 0x11, 0x6a, 0x89, 0x9e, 0x44, 0xaf, 0x49, 0x7f,
	0xc1, 0xfe, 0xd1, 0xfe, 0xd3, 0xfe, 0xc4, 0x06, 0x1e, 0x25, 0x99, 0xb2, 0x65, 0xb5, 0xd9, 0xa7,
	0xf0, 0x9e, 0xe3, 0x91, 0xc7, 0xbb, 0x87, 0x0f, 0xad, 0xc0, 0xc6, 0x90, 0xc7, 0x97, 0x17, 0x92,
	0x47, 0x43, 0x36, 0x89, 0xa4, 0x92, 0x74, 0x07, 0x6e, 0x9d, 0x0a, 0xd5, 0x93, 0x43, 0x71, 0x16,
	0x7e, 0x90, 0xb1, 0x27, 0xfe, 0x98, 0x8a, 0x58, 0xd1, 0x3e, 0x6c, 0xe7, 0xe1, 0x78, 0x22, 0xc3,
	0x58, 0x10, 0x02, 0xf5, 0x81, 0x1c, 0x0a, 0x77, 0xe5, 0x70, 0xe5, 0x78, 0xd5, 0xc3, 0x31, 0x39,
	0x82, 0xfa, 0x90, 0x2b, 0xee, 0x56, 0x0f, 0x6b, 0xc7, 0xad, 0xc7, 0x1d, 0x96, 0x46, 0x9d, 0x70,
	0xc5, 0x3d, 0x74, 0x91, 0x4d, 0xa8, 0x05, 0xf1, 0xc8, 0xad, 0x1d, 0xae, 0x1c, 0x3b, 0x9e, 0x1e,
	0xd2, 0x5f, 0xa1, 0x6d, 0xcf, 0x23, 0xeb, 0x50, 0xf5, 0x27, 0xb8, 0xac, 0xe3, 0x55, 0xfd, 0x89,
	0xde, 0x68, 0x22, 0x23, 0xe5, 0x56, 0x11, 0xc1, 0x31, 0x79, 0x00, 0xcd, 0x89, 0x8c, 0x7d, 0xe5,
	0xcb, 0x10, 0x97, 0x6a, 0x3d, 0x76, 0xd8, 0x9b, 0x04, 0xf0, 0x32, 0x17, 0x3d, 0x81, 0x66, 0x8a,
	0x92, 0x3b, 0xe0, 0x8c, 0x65, 0x38, 0xf2, 0xd5, 0x34, 0x49, 0xba, 0xea, 0xcd, 0x00, 0xd2, 0x85,
	0xe6, 0x98, 0x2b, 0xe3, 0xac, 0xa2, 0x33, 0xb3, 0xe9, 0x67, 0xd8, 0x3c, 0x15, 0xea, 0xfc, 0xea,
	0x95, 0x1f, 0xab, 0xa4, 0x2a, 0x64, 0x1f, 0x9a, 0x13, 0x3e, 0x12, 0xfd, 0x70, 0x1a, 0xe0, 0x62,
	0x75, 0x6f, 0x4d, 0xdb, 0xbd, 0x69, 0x40, 0x6e, 0x83, 0x83, 0xae, 0xd8, 0xff, 0x6c, 0xd6, 0xaa,
	0x7b, 0x38, 0xf7, 0xad, 0xff, 0x19, 0xab, 0x16, 0xeb, 0xc3, 0x98, 0xf3, 0xe3, 0x58, 0xef, 0x3d,
	0x8d, 0x45, 0x14, 0xf2, 0x40, 0xb8, 0x75, 0xc4, 0x33, 0x9b, 0xbe, 0x83, 0x2d, 0x6b, 0xef, 0x92,
	0xd2, 0x1f, 0x64, 0xa5, 0xd7, 0xd5, 0x68, 0x31, 0x13, 0x52, 0x5a, 0xf8, 0xf7, 0x00, 0xb3, 0x59,
	0x0b, 0x27, 0xea, 0xe4, 0x4e, 0x14, 0xc9, 0x4f, 0xfd, 0x81, 0x9c, 0x86, 0xa6, 0x0d, 0x1d, 0xaf,
	0x19, 0xc9, 0x4f, 0x2f, 0xb5, 0x4d, 0x76, 0xa0, 0x16, 0xc9, 0x4f, 0x6e, 0x0d, 0x5b, 0x5e, 0x63,
	0xe7, 0x57, 0x9e, 0xb6, 0xe9, 0xbf, 0x2b, 0x50, 0x3d, 0xbf, 0x22, 0x0f, 0x60, 0x5d, 0x45, 0x3c,
	0x8c, 0xf9, 0x40, 0x37, 0xa1, 0xef, 0x0f, 0x93, 0xc6, 0x76, 0x2c, 0xf4, 0x6c, 0xa8, 0x4f, 0xf4,
	0x21, 0x92, 0x41, 0xda, 0x63, 0x3d, 0xd6, 0x3c, 0x50, 0x32, 0xc9, 0xb7, 0xaa, 0x24, 0xd9, 0x86,
	0xd5, 0x49, 0xe4, 0x0f, 0x4c, 0x8d, 0xea, 0x9e, 0x31, 0x74, 0xda, 0x3c, 0x8e, 0x85, 0xd2, 0x4b,
	0xaf, 0xe2, 0xdc, 0x35, 0xb4, 0xcf, 0x86, 0xe4, 0x2e, 0x80, 0x71, 0x61, 0x65, 0x1b, 0xe8, 0x74,
	0x10, 0xe9, 0xf1, 0x40, 0xcc, 0xdc, 0xea, 0x7a, 0x22, 0xdc, 0x35, 0x5c, 0xd4, 0xb8, 0xcf, 0xaf,
	0x27, 0x42, 0xf3, 0x45, 0xf9, 0x81, 0x88, 0x15, 0x0f, 0x26, 0x6e, 0xd3, 0x78, 0x33, 0x80, 0x1c,
	0x41, 0xfb, 0x62, 0x2c, 0x07, 0x1f, 0x75, 0xb9, 0x2e, 0x44, 0xe4, 0x3a, 0x58, 0x95, 0x16, 0x62,
	0x3d, 0x84, 0x28, 0xc7, 0xfb, 0xf4, 0x42, 0x23, 0x36, 0x73, 0x72, 0xf4, 0x30, 0x85, 0x9e, 0xd1,
	0xc3, 0x6e, 0x42, 0x35, 0xdf, 0x84, 0x02, 0xe6, 0xd0, 0xdf, 0xf0, 0x6e, 0x5a, 0x5b, 0x14, 0x10,
	0xa4, 0x93, 0x10, 0xe4, 0x5e, 0x8e, 0x20, 0xc0, 0x30, 0xaa, 0x94, 0x1f, 0xbf, 0x83, 0x93, 0x4d,
	0xfa, 0x02, 0xe1, 0xf3, 0xf4, 0xa8, 0x5b, 0xf4, 0x70, 0x6d, 0x7a, 0x34, 0xcc, 0xae, 0x86, 0x21,
	0x7f, 0x55, 0x61, 0x15, 0xcd, 0x85, 0x62, 0x9a, 0xf5, 0xed, 0x62, 0xea, 0x66, 0x99, 0x29, 0x97,
	0x3c, 0xbe, 0x4c, 0x68, 0xe2, 0x20, 0xf2, 0x33, 0x8f, 0x2f, 0xc9, 0x43, 0xd8, 0x98, 0x44, 0xe2,
	0xcf, 0xbe, 0x35, 0xc7, 0x1c, 0xa4, 0xa3, 0xe1, 0x17, 0xd9, 0xbc, 0x03, 0x68, 0x05, 0x22, 0xfa,
	0x38, 0x16, 0xfd, 0x48, 0x4a, 0x95, 0xdc, 0x36, 0x30, 0x90, 0x27, 0xa5, 0x66, 0x73, 0x43, 0x5d,
	0xe1, 0x21, 0x57, 0xb1, 0x76, 0xab, 0xea, 0x4a, 0x1f, 0xb1, 0x0b, 0xcd, 0xa1, 0x18, 0x8b, 0x11,
	0x57, 0x29, 0x91, 0x32, 0x9b, 0xdc, 0x87, 0x4e, 0x3a, 0xee, 0xc7, 0xfe, 0x28, 0x44, 0x2a, 0x39,
	0x5e, 0x3b, 0x05, 0xdf, 0xfa, 0xa3, 0xb0, 0x9c, 0x4d, 0xf4, 0x87, 0x19, 0x55, 0xb4, 0x0c, 0xa6,
	0x54, 0xf9, 0x72, 0x5d, 0x68, 0x6f, 0xc6, 0x00, 0x13, 0x59, 0x22, 0x11, 0x34, 0xc7, 0x80, 0x75,
	0x96, 0x45, 0xcd, 0x58, 0x40, 0x5f, 0x43, 0x27, 0x07, 0x93, 0x3b, 0xb0, 0x8a, 0xfb, 0xe1, 0x4a,
	0xb3, 0x0e, 0x1a, 0x90, 0x1c, 0xc2, 0x9a, 0xba, 0xea, 0x8f, 0xfd, 0x58, 0x25, 0x9a, 0xbf, 0x96,
	0x08, 0x8f, 0xd7, 0x50, 0xf8, 0x97, 0xfe, 0x53, 0x85, 0x86, 0x81, 0xbe, 0x56, 0x0b, 0x8e, 0xa0,
	0x1d, 0xeb, 0x02, 0x84, 0x03, 0xfb, 0x1e, 0xb4, 0x52, 0x4c, 0xb7, 0xe3, 0x2e, 0xc0, 0x60, 0x1a,
	0xc5, 0x32, 0xc2, 0x09, 0x35, 0x9c, 0xe0, 0x18, 0x44, 0xbb, 0x8f, 0xa0, 0x9d, 0xb8, 0xc7, 0xfc,
	0x42, 0x8c, 0xb1, 0xcd, 0x1d, 0xaf, 0x65, 0xb0, 0x57, 0x1a, 0x42, 0xbd, 0xf7, 0x3f, 0x08, 0xdd,
	0x02, 0xec, 0x74, 0xdd, 0xcb, 0x6c, 0xb2, 0x0b, 0x8d, 0x58, 0x84, 0x43, 0x11, 0x25, 0xad, 0x4e,
	0x2c, 0x1d, 0x33, 0x90, 0xa1, 0x8a, 0xf8, 0x40, 0x25, 0x3d, 0xce, 0x6c, 0x1d, 0x13, 0x08, 0x75,
	0x29, 0x87, 0xd8, 0x5c, 0xc7, 0x4b, 0x2c, 0x14, 0x2d, 0x1e, 0xf1, 0x00, 0x05, 0xc2, 0xf1, 0x8c,
	0x41, 0xf6, 0x60, 0x2d, 0xf6, 0x47, 0x7d, 0x3e, 0x1e, 0xb9, 0x80, 0xb9, 0x35, 0x62, 0x7f, 0xf4,
	0x7c, 0x3c, 0xd2, 0x34, 0xd1, 0x14, 0xe2, 0x6a, 0x1a, 0x09, 0xb7, 0x65, 0x58, 0x9e, 0x01, 0x9a,
	0xbd, 0x83, 0x48, 0x68, 0x9e, 0x61, 0xde, 0x6d, 0xcc, 0x1b, 0x0c, 0x74, 0xee, 0x07, 0x82, 0x1e,
	0xc0, 0xdd, 0x53, 0x81, 0x4a, 0xe3, 0x47, 0x22, 0x10, 0xa1, 0xea, 0x4d, 0x83, 0x17, 0xd7, 0x27,
	0xfc, 0x3a, 0x7d, 0xcc, 0x2f, 0xe0, 0xde, 0xb2, 0x09, 0x25, 0xc4, 0x79, 0x94, 0x7b, 0xd6, 0x5d,
	0x56, 0x10, 0x6f, 0x51, 0xe8, 0x25, 0xec, 0x2d, 0x99, 0xa0, 0x17, 0xc7, 0xcc, 0xf5, 0xe2, 0x35,
	0x0f, 0xc7, 0xba, 0x42, 0x33, 0xe5, 0xa8, 0x79, 0xc6, 0xa0, 0x5b, 0xb0, 0x81, 0xef, 0x5e, 0x6f,
	0x1a, 0xa4, 0xb9, 0x3f, 0x4b, 0x9e, 0x61, 0x84, 0x4a, 0xb2, 0x75, 0x73, 0x34, 0xaf, 0x33, 0x3d,
	0xdf, 0x64, 0xb6, 0x0f, 0x7b, 0xa7, 0x42, 0x3d, 0xc7, 0x17, 0x60, 0xae, 0x30, 0xbf, 0x80, 0xbb,
	0xe8, 0x2a, 0xd9, 0xe4, 0x61, 0xae, 0x24, 0x84, 0xe5, 0x22, 0xad, 0x62, 0x3c, 0x85, 0xad, 0x05,
	0xd7, 0x0d, 0xca, 0x70, 0x1b, 0xf6, 0x75, 0x5a, 0x03, 0xb4, 0xe6, 0x73, 0x7e, 0x07, 0xdd, 0x22,
	0x67, 0x49, 0xd6, 0xc7, 0xb9, 0xac, 0xb7, 0xd9, 0x5c, 0xac, 0x95, 0xf7, 0x4f, 0x70, 0xab, 0xc0,
	0x79, 0x83, 0xcc, 0xb7, 0x81, 0x60, 0xb7, 0x9e, 0x07, 0xda, 0x4c, 0x53, 0x7e, 0x89, 0x42, 0x37,
	0x43, 0xff, 0x57, 0x1b, 0x77, 0x51, 0xf3, 0x90, 0x08, 0xb9, 0x7a, 0xbc, 0x81, 0x9d, 0x39, 0xbc,
	0x64, 0xf9, 0xfb, 0xb9, 0x52, 0x6c, 0xb0, 0x59, 0x98, 0x55, 0x85, 0x27, 0xb0, 0x9e, 0xc7, 0x6f,
	0x50, 0x80, 0x3d, 0xa8, 0x69, 0x2d, 0xda, 0x84, 0x5a, 0xfa, 0x64, 0xd6, 0x3c, 0x3d, 0x4c, 0x58,
	0x98, 0xd6, 0x20, 0x77, 0x02, 0x0f, 0x59, 0x38, 0xe7, 0xfa, 0x2a, 0x45, 0xaf, 0xa1, 0xa2, 0xe7,
	0x23, 0xcd, 0x19, 0x7e, 0x84, 0x4e, 0x0e, 0xbe, 0xc1, 0x11, 0x1e, 0xc1, 0xae, 0x26, 0xd8, 0x78,
	0xac, 0x7f, 0x10, 0x9d, 0x4b, 0xc5, 0xc7, 0xe9, 0xcb, 0xa4, 0xd7, 0xd0, 0xbf, 0x9a, 0x8c, 0x80,
	0xe3, 0x98, 0xbe, 0x36, 0xb7, 0x2b, 0x37, 0xbb, 0x24, 0xf7, 0xc3, 0x5c, 0xee, 0x6d, 0x96, 0x04,
	0x5a, 0xd5, 0xff, 0x1e, 0x5a, 0x16, 0x58, 0xb4, 0xa7, 0xce, 0x5b, 0xe9, 0x9d, 0xd2, 0xbc, 0xd1,
	0x78, 0xfc, 0x77, 0x03, 0x9c, 0x93, 0xf4, 0xeb, 0x86, 0x3c, 0x85, 0xb6, 0xfd, 0x23, 0x89, 0x6c,
	0xb3, 0x82, 0x9f, 0x65, 0xdd, 0x1d, 0x56, 0xf4, 0x4b, 0x8a, 0x56, 0xec, 0x70, 0xfd, 0x28, 0x5a,
	0xe1, 0xd6, 0x53, 0x6d, 0x85, 0xdb, 0xcf, 0x70, 0x16, 0x9e, 0x7d, 0x3e, 0x99, 0xf0, 0xf9, 0x8f,
	0x2c, 0x13, 0xbe, 0xf0, 0x8d, 0x45, 0x2b, 0xe4, 0x3b, 0x70, 0xb2, 0xdf, 0xff, 0x64, 0x8b, 0xcd,
	0x7f, 0x87, 0x74, 0x09, 0x5b, 0xf8, 0x3c, 0xa0, 0x15, 0xf2, 0x0d, 0x34, 0xd3, 0x9b, 0x40, 0x36,
	0xd9, 0x9c, 0x90, 0x76, 0xb7, 0xd8, 0xbc, 0x8e, 0xd2, 0x0a, 0x79, 0x8f, 0xbd, 0x2e, 0x10, 0x6e,
	0x72, 0x8f, 0x95, 0xbe, 0x29, 0xdd, 0x03, 0x56, 0xfe, 0xa4, 0xd0, 0x0a, 0x39, 0x43, 0xe9, 0xce,
	0x09, 0x21, 0x71, 0xd9, 0x12, 0x2d, 0xee, 0xee, 0xb3, 0x65, 0x52, 0x4c, 0x2b, 0xe4, 0x35, 0xea,
	0xca, 0x9c, 0x36, 0x91, 0x2e, 0x5b, 0x2a, 0x93, 0xdd, 0xdb, 0x6c, 0xb9, 0x4a, 0xd2, 0x0a, 0x79,
	0x02, 0x2d, 0xeb, 0xce, 0x91, 0x5b, 0x6c, 0x51, 0xb6, 0xba, 0xdb, 0xac, 0x40, 0xb5, 0x68, 0x85,
	0x3c, 0x83, 0x4e, 0x4e, 0x71, 0xc8, 0x0e, 0x2b, 0x52, 0xa6, 0xee, 0x2e, 0x2b, 0x14, 0x26, 0x5a,
	0x21, 0xa7, 0xc9, 0xa3, 0x66, 0x5f, 0x50, 0x97, 0x2d, 0xd1, 0x07, 0x53, 0x99, 0x62, 0x79, 0x38,
	0xc1, 0x07, 0xd3, 0xbe, 0x7d, 0x64, 0x8f, 0x15, 0xdf, 0xde, 0xae, 0xcb, 0x96, 0x5c, 0xd4, 0x8b,
	0x06, 0xfe, 0x2b, 0xe0, 0xdb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x84, 0xb1, 0x1c, 0x1d,
	0x10, 0x00, 0x00,
}
