// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bottos-project/bottos/service/storage/proto/storage-api.proto

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	github.com/bottos-project/bottos/service/storage/proto/storage-api.proto

It has these top-level messages:
	AllRequest
	UserRequest
	FileUploadRequest
	FileUploadResponse
	FileUploadStatRequest
	FileUploadStatResponse
	DownLoadRequest
	DownLoadResponse
	Request
	Response
	InsertTokenRequest
	InsertTokenResponse
	TokenRequest
	TokenResponse
	DelTokenRequest
	DelTokenResponse
	AgeTokenRequest
	AgeTokenResponse
	UserFileListRequest
	File
	UserFileListResponse
	UserRequireListRequest
	Requirement
	UserRequireListResponse
	AllRequireListResponse
	FeatureRequireListRequest
	FeatureRequireListResponse
	UserAssetListRequest
	UserAsset
	UserAssetListResponse
	Asset
	AssetListRequest
	AssetListResponse
	RecentTx
	RecentTxListRequest
	RecentTxListResponse
	UserTxListResponse
	AllTxNumResponse
	SumTxAmountRequest
	SumTxAmountResponse
	DayTxNumRequest
	DayTxNumResponse
	WeekTxNumResponse
	DayAssetNumResponse
	WeekAssetNumResponse
	DayRequirementNumResponse
	WeekRequirementNumResponse
	Node
	NodeInfosResponse
	Transfer
	TransferListResponse
	Favorit
	UserFavoritResponse
	DataPresale
	UserDataPresaleResponse
	AssetIdRequest
	AssetInfoResponse
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/bottos-project/go-micro/client"
	server "github.com/bottos-project/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllRequest struct {
}

func (m *AllRequest) Reset()                    { *m = AllRequest{} }
func (m *AllRequest) String() string            { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()               {}
func (*AllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type FileUploadRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	FileName   string `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	FileSize   uint64 `protobuf:"varint,3,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	FilePolicy string `protobuf:"bytes,4,opt,name=file_policy,json=filePolicy" json:"file_policy,omitempty"`
	FileNumber uint64 `protobuf:"varint,5,opt,name=file_number,json=fileNumber" json:"file_number,omitempty"`
	Signature  string `protobuf:"bytes,6,opt,name=signature" json:"signature,omitempty"`
}

func (m *FileUploadRequest) Reset()                    { *m = FileUploadRequest{} }
func (m *FileUploadRequest) String() string            { return proto.CompactTextString(m) }
func (*FileUploadRequest) ProtoMessage()               {}
func (*FileUploadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileUploadRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FileUploadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileUploadRequest) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileUploadRequest) GetFilePolicy() string {
	if m != nil {
		return m.FilePolicy
	}
	return ""
}

func (m *FileUploadRequest) GetFileNumber() uint64 {
	if m != nil {
		return m.FileNumber
	}
	return 0
}

func (m *FileUploadRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type FileUploadResponse struct {
	Result          string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Message         string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	PresignedPutUrl string `protobuf:"bytes,3,opt,name=presigned_put_url,json=presignedPutUrl" json:"presigned_put_url,omitempty"`
}

func (m *FileUploadResponse) Reset()                    { *m = FileUploadResponse{} }
func (m *FileUploadResponse) String() string            { return proto.CompactTextString(m) }
func (*FileUploadResponse) ProtoMessage()               {}
func (*FileUploadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileUploadResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *FileUploadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FileUploadResponse) GetPresignedPutUrl() string {
	if m != nil {
		return m.PresignedPutUrl
	}
	return ""
}

type FileUploadStatRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
}

func (m *FileUploadStatRequest) Reset()                    { *m = FileUploadStatRequest{} }
func (m *FileUploadStatRequest) String() string            { return proto.CompactTextString(m) }
func (*FileUploadStatRequest) ProtoMessage()               {}
func (*FileUploadStatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FileUploadStatRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FileUploadStatRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type FileUploadStatResponse struct {
	Result  string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Size    int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *FileUploadStatResponse) Reset()                    { *m = FileUploadStatResponse{} }
func (m *FileUploadStatResponse) String() string            { return proto.CompactTextString(m) }
func (*FileUploadStatResponse) ProtoMessage()               {}
func (*FileUploadStatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FileUploadStatResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *FileUploadStatResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FileUploadStatResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type DownLoadRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
}

func (m *DownLoadRequest) Reset()                    { *m = DownLoadRequest{} }
func (m *DownLoadRequest) String() string            { return proto.CompactTextString(m) }
func (*DownLoadRequest) ProtoMessage()               {}
func (*DownLoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DownLoadRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DownLoadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type DownLoadResponse struct {
	Result          string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Message         string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	PresignedGetUrl string `protobuf:"bytes,3,opt,name=presigned_get_url,json=presignedGetUrl" json:"presigned_get_url,omitempty"`
}

func (m *DownLoadResponse) Reset()                    { *m = DownLoadResponse{} }
func (m *DownLoadResponse) String() string            { return proto.CompactTextString(m) }
func (*DownLoadResponse) ProtoMessage()               {}
func (*DownLoadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DownLoadResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *DownLoadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DownLoadResponse) GetPresignedGetUrl() string {
	if m != nil {
		return m.PresignedGetUrl
	}
	return ""
}

type Request struct {
	Txid    string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Request) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Request) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type InsertTokenRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *InsertTokenRequest) Reset()                    { *m = InsertTokenRequest{} }
func (m *InsertTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertTokenRequest) ProtoMessage()               {}
func (*InsertTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *InsertTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InsertTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InsertTokenResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *InsertTokenResponse) Reset()                    { *m = InsertTokenResponse{} }
func (m *InsertTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*InsertTokenResponse) ProtoMessage()               {}
func (*InsertTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *InsertTokenResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type TokenRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenResponse struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Token      string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	InsertTime int64  `protobuf:"varint,3,opt,name=insert_time,json=insertTime" json:"insert_time,omitempty"`
	Code       uint32 `protobuf:"varint,4,opt,name=code" json:"code,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TokenResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenResponse) GetInsertTime() int64 {
	if m != nil {
		return m.InsertTime
	}
	return 0
}

func (m *TokenResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type DelTokenRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *DelTokenRequest) Reset()                    { *m = DelTokenRequest{} }
func (m *DelTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*DelTokenRequest) ProtoMessage()               {}
func (*DelTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DelTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DelTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DelTokenResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *DelTokenResponse) Reset()                    { *m = DelTokenResponse{} }
func (m *DelTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*DelTokenResponse) ProtoMessage()               {}
func (*DelTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DelTokenResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type AgeTokenRequest struct {
	Timeout int64 `protobuf:"varint,1,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *AgeTokenRequest) Reset()                    { *m = AgeTokenRequest{} }
func (m *AgeTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*AgeTokenRequest) ProtoMessage()               {}
func (*AgeTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AgeTokenRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type AgeTokenResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *AgeTokenResponse) Reset()                    { *m = AgeTokenResponse{} }
func (m *AgeTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*AgeTokenResponse) ProtoMessage()               {}
func (*AgeTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AgeTokenResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UserFileListRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *UserFileListRequest) Reset()                    { *m = UserFileListRequest{} }
func (m *UserFileListRequest) String() string            { return proto.CompactTextString(m) }
func (*UserFileListRequest) ProtoMessage()               {}
func (*UserFileListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UserFileListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type File struct {
	FileName          string `protobuf:"bytes,1,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	FileSize          uint64 `protobuf:"varint,2,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	FilePolicy        string `protobuf:"bytes,3,opt,name=file_policy,json=filePolicy" json:"file_policy,omitempty"`
	FileNumber        uint64 `protobuf:"varint,4,opt,name=file_number,json=fileNumber" json:"file_number,omitempty"`
	FileHash          string `protobuf:"bytes,5,opt,name=file_hash,json=fileHash" json:"file_hash,omitempty"`
	AuthorizedStorage string `protobuf:"bytes,6,opt,name=authorized_storage,json=authorizedStorage" json:"authorized_storage,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *File) GetFilePolicy() string {
	if m != nil {
		return m.FilePolicy
	}
	return ""
}

func (m *File) GetFileNumber() uint64 {
	if m != nil {
		return m.FileNumber
	}
	return 0
}

func (m *File) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *File) GetAuthorizedStorage() string {
	if m != nil {
		return m.AuthorizedStorage
	}
	return ""
}

type UserFileListResponse struct {
	Code     uint32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	FileList []*File `protobuf:"bytes,2,rep,name=FileList" json:"FileList,omitempty"`
}

func (m *UserFileListResponse) Reset()                    { *m = UserFileListResponse{} }
func (m *UserFileListResponse) String() string            { return proto.CompactTextString(m) }
func (*UserFileListResponse) ProtoMessage()               {}
func (*UserFileListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *UserFileListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserFileListResponse) GetFileList() []*File {
	if m != nil {
		return m.FileList
	}
	return nil
}

type UserRequireListRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *UserRequireListRequest) Reset()                    { *m = UserRequireListRequest{} }
func (m *UserRequireListRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequireListRequest) ProtoMessage()               {}
func (*UserRequireListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *UserRequireListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Requirement struct {
	RequirementId   string `protobuf:"bytes,1,opt,name=requirement_id,json=requirementId" json:"requirement_id,omitempty"`
	Username        string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	RequirementName string `protobuf:"bytes,3,opt,name=requirement_name,json=requirementName" json:"requirement_name,omitempty"`
	FeatureTag      uint64 `protobuf:"varint,4,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
	SamplePath      string `protobuf:"bytes,5,opt,name=sample_path,json=samplePath" json:"sample_path,omitempty"`
	SampleHash      string `protobuf:"bytes,6,opt,name=sample_hash,json=sampleHash" json:"sample_hash,omitempty"`
	ExpireTime      uint32 `protobuf:"varint,7,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	Price           uint64 `protobuf:"varint,8,opt,name=price" json:"price,omitempty"`
	Description     string `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
	PublishDate     uint32 `protobuf:"varint,10,opt,name=publish_date,json=publishDate" json:"publish_date,omitempty"`
}

func (m *Requirement) Reset()                    { *m = Requirement{} }
func (m *Requirement) String() string            { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()               {}
func (*Requirement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Requirement) GetRequirementId() string {
	if m != nil {
		return m.RequirementId
	}
	return ""
}

func (m *Requirement) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Requirement) GetRequirementName() string {
	if m != nil {
		return m.RequirementName
	}
	return ""
}

func (m *Requirement) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

func (m *Requirement) GetSamplePath() string {
	if m != nil {
		return m.SamplePath
	}
	return ""
}

func (m *Requirement) GetSampleHash() string {
	if m != nil {
		return m.SampleHash
	}
	return ""
}

func (m *Requirement) GetExpireTime() uint32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *Requirement) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Requirement) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Requirement) GetPublishDate() uint32 {
	if m != nil {
		return m.PublishDate
	}
	return 0
}

type UserRequireListResponse struct {
	Code        uint32         `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	RequireList []*Requirement `protobuf:"bytes,2,rep,name=RequireList" json:"RequireList,omitempty"`
}

func (m *UserRequireListResponse) Reset()                    { *m = UserRequireListResponse{} }
func (m *UserRequireListResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRequireListResponse) ProtoMessage()               {}
func (*UserRequireListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *UserRequireListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserRequireListResponse) GetRequireList() []*Requirement {
	if m != nil {
		return m.RequireList
	}
	return nil
}

type AllRequireListResponse struct {
	Code        uint32         `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	RequireList []*Requirement `protobuf:"bytes,2,rep,name=RequireList" json:"RequireList,omitempty"`
}

func (m *AllRequireListResponse) Reset()                    { *m = AllRequireListResponse{} }
func (m *AllRequireListResponse) String() string            { return proto.CompactTextString(m) }
func (*AllRequireListResponse) ProtoMessage()               {}
func (*AllRequireListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *AllRequireListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AllRequireListResponse) GetRequireList() []*Requirement {
	if m != nil {
		return m.RequireList
	}
	return nil
}

type FeatureRequireListRequest struct {
	FeatureTag uint64 `protobuf:"varint,1,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
}

func (m *FeatureRequireListRequest) Reset()                    { *m = FeatureRequireListRequest{} }
func (m *FeatureRequireListRequest) String() string            { return proto.CompactTextString(m) }
func (*FeatureRequireListRequest) ProtoMessage()               {}
func (*FeatureRequireListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *FeatureRequireListRequest) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

type FeatureRequireListResponse struct {
	Code        uint32         `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	RequireList []*Requirement `protobuf:"bytes,2,rep,name=RequireList" json:"RequireList,omitempty"`
}

func (m *FeatureRequireListResponse) Reset()                    { *m = FeatureRequireListResponse{} }
func (m *FeatureRequireListResponse) String() string            { return proto.CompactTextString(m) }
func (*FeatureRequireListResponse) ProtoMessage()               {}
func (*FeatureRequireListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *FeatureRequireListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FeatureRequireListResponse) GetRequireList() []*Requirement {
	if m != nil {
		return m.RequireList
	}
	return nil
}

type UserAssetListRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *UserAssetListRequest) Reset()                    { *m = UserAssetListRequest{} }
func (m *UserAssetListRequest) String() string            { return proto.CompactTextString(m) }
func (*UserAssetListRequest) ProtoMessage()               {}
func (*UserAssetListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UserAssetListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserAsset struct {
	AssetId     string `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
	AssetName   string `protobuf:"bytes,2,opt,name=asset_name,json=assetName" json:"asset_name,omitempty"`
	FeatureTag  uint64 `protobuf:"varint,3,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
	SamplePath  string `protobuf:"bytes,4,opt,name=sample_path,json=samplePath" json:"sample_path,omitempty"`
	SampleHash  string `protobuf:"bytes,5,opt,name=sample_hash,json=sampleHash" json:"sample_hash,omitempty"`
	StoragePath string `protobuf:"bytes,6,opt,name=storage_path,json=storagePath" json:"storage_path,omitempty"`
	StorageHash string `protobuf:"bytes,7,opt,name=storage_hash,json=storageHash" json:"storage_hash,omitempty"`
	ExpireTime  uint32 `protobuf:"varint,8,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	Price       uint64 `protobuf:"varint,9,opt,name=price" json:"price,omitempty"`
	Description string `protobuf:"bytes,10,opt,name=description" json:"description,omitempty"`
	UploadDate  uint32 `protobuf:"varint,11,opt,name=upload_date,json=uploadDate" json:"upload_date,omitempty"`
}

func (m *UserAsset) Reset()                    { *m = UserAsset{} }
func (m *UserAsset) String() string            { return proto.CompactTextString(m) }
func (*UserAsset) ProtoMessage()               {}
func (*UserAsset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *UserAsset) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *UserAsset) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *UserAsset) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

func (m *UserAsset) GetSamplePath() string {
	if m != nil {
		return m.SamplePath
	}
	return ""
}

func (m *UserAsset) GetSampleHash() string {
	if m != nil {
		return m.SampleHash
	}
	return ""
}

func (m *UserAsset) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *UserAsset) GetStorageHash() string {
	if m != nil {
		return m.StorageHash
	}
	return ""
}

func (m *UserAsset) GetExpireTime() uint32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *UserAsset) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UserAsset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserAsset) GetUploadDate() uint32 {
	if m != nil {
		return m.UploadDate
	}
	return 0
}

type UserAssetListResponse struct {
	Code          uint32       `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	UserAssetList []*UserAsset `protobuf:"bytes,2,rep,name=UserAssetList" json:"UserAssetList,omitempty"`
}

func (m *UserAssetListResponse) Reset()                    { *m = UserAssetListResponse{} }
func (m *UserAssetListResponse) String() string            { return proto.CompactTextString(m) }
func (*UserAssetListResponse) ProtoMessage()               {}
func (*UserAssetListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *UserAssetListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserAssetListResponse) GetUserAssetList() []*UserAsset {
	if m != nil {
		return m.UserAssetList
	}
	return nil
}

type Asset struct {
	AssetId     string `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	AssetName   string `protobuf:"bytes,3,opt,name=asset_name,json=assetName" json:"asset_name,omitempty"`
	FeatureTag  uint64 `protobuf:"varint,4,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
	SamplePath  string `protobuf:"bytes,5,opt,name=sample_path,json=samplePath" json:"sample_path,omitempty"`
	SampleHash  string `protobuf:"bytes,6,opt,name=sample_hash,json=sampleHash" json:"sample_hash,omitempty"`
	StoragePath string `protobuf:"bytes,7,opt,name=storage_path,json=storagePath" json:"storage_path,omitempty"`
	StorageHash string `protobuf:"bytes,8,opt,name=storage_hash,json=storageHash" json:"storage_hash,omitempty"`
	ExpireTime  uint32 `protobuf:"varint,9,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	Price       uint64 `protobuf:"varint,10,opt,name=price" json:"price,omitempty"`
	Description string `protobuf:"bytes,11,opt,name=description" json:"description,omitempty"`
	UploadDate  uint32 `protobuf:"varint,12,opt,name=upload_date,json=uploadDate" json:"upload_date,omitempty"`
}

func (m *Asset) Reset()                    { *m = Asset{} }
func (m *Asset) String() string            { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()               {}
func (*Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *Asset) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Asset) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Asset) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *Asset) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

func (m *Asset) GetSamplePath() string {
	if m != nil {
		return m.SamplePath
	}
	return ""
}

func (m *Asset) GetSampleHash() string {
	if m != nil {
		return m.SampleHash
	}
	return ""
}

func (m *Asset) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *Asset) GetStorageHash() string {
	if m != nil {
		return m.StorageHash
	}
	return ""
}

func (m *Asset) GetExpireTime() uint32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *Asset) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Asset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Asset) GetUploadDate() uint32 {
	if m != nil {
		return m.UploadDate
	}
	return 0
}

type AssetListRequest struct {
}

func (m *AssetListRequest) Reset()                    { *m = AssetListRequest{} }
func (m *AssetListRequest) String() string            { return proto.CompactTextString(m) }
func (*AssetListRequest) ProtoMessage()               {}
func (*AssetListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type AssetListResponse struct {
	Code      uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	AssetList []*Asset `protobuf:"bytes,2,rep,name=AssetList" json:"AssetList,omitempty"`
}

func (m *AssetListResponse) Reset()                    { *m = AssetListResponse{} }
func (m *AssetListResponse) String() string            { return proto.CompactTextString(m) }
func (*AssetListResponse) ProtoMessage()               {}
func (*AssetListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *AssetListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AssetListResponse) GetAssetList() []*Asset {
	if m != nil {
		return m.AssetList
	}
	return nil
}

type RecentTx struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	From          string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To            string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	Price         uint64 `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	Type          uint64 `protobuf:"varint,5,opt,name=type" json:"type,omitempty"`
	Date          string `protobuf:"bytes,6,opt,name=date" json:"date,omitempty"`
	BlockId       uint64 `protobuf:"varint,7,opt,name=block_id,json=blockId" json:"block_id,omitempty"`
}

func (m *RecentTx) Reset()                    { *m = RecentTx{} }
func (m *RecentTx) String() string            { return proto.CompactTextString(m) }
func (*RecentTx) ProtoMessage()               {}
func (*RecentTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *RecentTx) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *RecentTx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RecentTx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *RecentTx) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RecentTx) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RecentTx) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *RecentTx) GetBlockId() uint64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

type RecentTxListRequest struct {
}

func (m *RecentTxListRequest) Reset()                    { *m = RecentTxListRequest{} }
func (m *RecentTxListRequest) String() string            { return proto.CompactTextString(m) }
func (*RecentTxListRequest) ProtoMessage()               {}
func (*RecentTxListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type RecentTxListResponse struct {
	Code         uint32      `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	RecentTxList []*RecentTx `protobuf:"bytes,2,rep,name=RecentTxList" json:"RecentTxList,omitempty"`
}

func (m *RecentTxListResponse) Reset()                    { *m = RecentTxListResponse{} }
func (m *RecentTxListResponse) String() string            { return proto.CompactTextString(m) }
func (*RecentTxListResponse) ProtoMessage()               {}
func (*RecentTxListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *RecentTxListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RecentTxListResponse) GetRecentTxList() []*RecentTx {
	if m != nil {
		return m.RecentTxList
	}
	return nil
}

type UserTxListResponse struct {
	Code         uint32      `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	RecentTxList []*RecentTx `protobuf:"bytes,2,rep,name=RecentTxList" json:"RecentTxList,omitempty"`
}

func (m *UserTxListResponse) Reset()                    { *m = UserTxListResponse{} }
func (m *UserTxListResponse) String() string            { return proto.CompactTextString(m) }
func (*UserTxListResponse) ProtoMessage()               {}
func (*UserTxListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *UserTxListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserTxListResponse) GetRecentTxList() []*RecentTx {
	if m != nil {
		return m.RecentTxList
	}
	return nil
}

type AllTxNumResponse struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	TxNum uint64 `protobuf:"varint,2,opt,name=tx_num,json=txNum" json:"tx_num,omitempty"`
}

func (m *AllTxNumResponse) Reset()                    { *m = AllTxNumResponse{} }
func (m *AllTxNumResponse) String() string            { return proto.CompactTextString(m) }
func (*AllTxNumResponse) ProtoMessage()               {}
func (*AllTxNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *AllTxNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AllTxNumResponse) GetTxNum() uint64 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

type SumTxAmountRequest struct {
}

func (m *SumTxAmountRequest) Reset()                    { *m = SumTxAmountRequest{} }
func (m *SumTxAmountRequest) String() string            { return proto.CompactTextString(m) }
func (*SumTxAmountRequest) ProtoMessage()               {}
func (*SumTxAmountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type SumTxAmountResponse struct {
	Code      uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	AmountSum uint64 `protobuf:"varint,2,opt,name=amount_sum,json=amountSum" json:"amount_sum,omitempty"`
}

func (m *SumTxAmountResponse) Reset()                    { *m = SumTxAmountResponse{} }
func (m *SumTxAmountResponse) String() string            { return proto.CompactTextString(m) }
func (*SumTxAmountResponse) ProtoMessage()               {}
func (*SumTxAmountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *SumTxAmountResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SumTxAmountResponse) GetAmountSum() uint64 {
	if m != nil {
		return m.AmountSum
	}
	return 0
}

type DayTxNumRequest struct {
}

func (m *DayTxNumRequest) Reset()                    { *m = DayTxNumRequest{} }
func (m *DayTxNumRequest) String() string            { return proto.CompactTextString(m) }
func (*DayTxNumRequest) ProtoMessage()               {}
func (*DayTxNumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type DayTxNumResponse struct {
	Code     uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	DayTxNum uint64 `protobuf:"varint,2,opt,name=day_tx_num,json=dayTxNum" json:"day_tx_num,omitempty"`
}

func (m *DayTxNumResponse) Reset()                    { *m = DayTxNumResponse{} }
func (m *DayTxNumResponse) String() string            { return proto.CompactTextString(m) }
func (*DayTxNumResponse) ProtoMessage()               {}
func (*DayTxNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *DayTxNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DayTxNumResponse) GetDayTxNum() uint64 {
	if m != nil {
		return m.DayTxNum
	}
	return 0
}

type WeekTxNumResponse struct {
	Code      uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	WeekTxNum []uint64 `protobuf:"varint,2,rep,packed,name=week_tx_num,json=weekTxNum" json:"week_tx_num,omitempty"`
}

func (m *WeekTxNumResponse) Reset()                    { *m = WeekTxNumResponse{} }
func (m *WeekTxNumResponse) String() string            { return proto.CompactTextString(m) }
func (*WeekTxNumResponse) ProtoMessage()               {}
func (*WeekTxNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *WeekTxNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WeekTxNumResponse) GetWeekTxNum() []uint64 {
	if m != nil {
		return m.WeekTxNum
	}
	return nil
}

type DayAssetNumResponse struct {
	Code        uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	DayAssetNum uint64 `protobuf:"varint,2,opt,name=day_asset_num,json=dayAssetNum" json:"day_asset_num,omitempty"`
}

func (m *DayAssetNumResponse) Reset()                    { *m = DayAssetNumResponse{} }
func (m *DayAssetNumResponse) String() string            { return proto.CompactTextString(m) }
func (*DayAssetNumResponse) ProtoMessage()               {}
func (*DayAssetNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *DayAssetNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DayAssetNumResponse) GetDayAssetNum() uint64 {
	if m != nil {
		return m.DayAssetNum
	}
	return 0
}

type WeekAssetNumResponse struct {
	Code         uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	WeekAssetNum []uint64 `protobuf:"varint,2,rep,packed,name=week_asset_num,json=weekAssetNum" json:"week_asset_num,omitempty"`
}

func (m *WeekAssetNumResponse) Reset()                    { *m = WeekAssetNumResponse{} }
func (m *WeekAssetNumResponse) String() string            { return proto.CompactTextString(m) }
func (*WeekAssetNumResponse) ProtoMessage()               {}
func (*WeekAssetNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *WeekAssetNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WeekAssetNumResponse) GetWeekAssetNum() []uint64 {
	if m != nil {
		return m.WeekAssetNum
	}
	return nil
}

type DayRequirementNumResponse struct {
	Code              uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	DayRequirementNum uint64 `protobuf:"varint,2,opt,name=day_requirement_num,json=dayRequirementNum" json:"day_requirement_num,omitempty"`
}

func (m *DayRequirementNumResponse) Reset()                    { *m = DayRequirementNumResponse{} }
func (m *DayRequirementNumResponse) String() string            { return proto.CompactTextString(m) }
func (*DayRequirementNumResponse) ProtoMessage()               {}
func (*DayRequirementNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *DayRequirementNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DayRequirementNumResponse) GetDayRequirementNum() uint64 {
	if m != nil {
		return m.DayRequirementNum
	}
	return 0
}

type WeekRequirementNumResponse struct {
	Code               uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	WeekRequirementNum []uint64 `protobuf:"varint,2,rep,packed,name=week_requirement_num,json=weekRequirementNum" json:"week_requirement_num,omitempty"`
}

func (m *WeekRequirementNumResponse) Reset()                    { *m = WeekRequirementNumResponse{} }
func (m *WeekRequirementNumResponse) String() string            { return proto.CompactTextString(m) }
func (*WeekRequirementNumResponse) ProtoMessage()               {}
func (*WeekRequirementNumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *WeekRequirementNumResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WeekRequirementNumResponse) GetWeekRequirementNum() []uint64 {
	if m != nil {
		return m.WeekRequirementNum
	}
	return nil
}

type Node struct {
	NodeId   string `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	NodeIp   string `protobuf:"bytes,2,opt,name=node_ip,json=nodeIp" json:"node_ip,omitempty"`
	NodePort string `protobuf:"bytes,3,opt,name=node_port,json=nodePort" json:"node_port,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *Node) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Node) GetNodeIp() string {
	if m != nil {
		return m.NodeIp
	}
	return ""
}

func (m *Node) GetNodePort() string {
	if m != nil {
		return m.NodePort
	}
	return ""
}

type NodeInfosResponse struct {
	Code     uint32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	NodeNum  uint64  `protobuf:"varint,2,opt,name=node_num,json=nodeNum" json:"node_num,omitempty"`
	NodeList []*Node `protobuf:"bytes,3,rep,name=node_list,json=nodeList" json:"node_list,omitempty"`
}

func (m *NodeInfosResponse) Reset()                    { *m = NodeInfosResponse{} }
func (m *NodeInfosResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeInfosResponse) ProtoMessage()               {}
func (*NodeInfosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *NodeInfosResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NodeInfosResponse) GetNodeNum() uint64 {
	if m != nil {
		return m.NodeNum
	}
	return 0
}

func (m *NodeInfosResponse) GetNodeList() []*Node {
	if m != nil {
		return m.NodeList
	}
	return nil
}

type Transfer struct {
	TxId     string `protobuf:"bytes,1,opt,name=tx_id,json=txId" json:"tx_id,omitempty"`
	TxTime   string `protobuf:"bytes,2,opt,name=tx_time,json=txTime" json:"tx_time,omitempty"`
	Price    uint64 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	From     string `protobuf:"bytes,4,opt,name=from" json:"from,omitempty"`
	To       string `protobuf:"bytes,5,opt,name=to" json:"to,omitempty"`
	BlockNum uint64 `protobuf:"varint,6,opt,name=block_num,json=blockNum" json:"block_num,omitempty"`
}

func (m *Transfer) Reset()                    { *m = Transfer{} }
func (m *Transfer) String() string            { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()               {}
func (*Transfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *Transfer) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Transfer) GetTxTime() string {
	if m != nil {
		return m.TxTime
	}
	return ""
}

func (m *Transfer) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Transfer) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transfer) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transfer) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

type TransferListResponse struct {
	Code         uint32      `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	TransferList []*Transfer `protobuf:"bytes,2,rep,name=transfer_list,json=transferList" json:"transfer_list,omitempty"`
}

func (m *TransferListResponse) Reset()                    { *m = TransferListResponse{} }
func (m *TransferListResponse) String() string            { return proto.CompactTextString(m) }
func (*TransferListResponse) ProtoMessage()               {}
func (*TransferListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *TransferListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TransferListResponse) GetTransferList() []*Transfer {
	if m != nil {
		return m.TransferList
	}
	return nil
}

type Favorit struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	OpType    string `protobuf:"bytes,2,opt,name=op_type,json=opType" json:"op_type,omitempty"`
	GoodsType string `protobuf:"bytes,3,opt,name=goods_type,json=goodsType" json:"goods_type,omitempty"`
	GoodsId   string `protobuf:"bytes,4,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
}

func (m *Favorit) Reset()                    { *m = Favorit{} }
func (m *Favorit) String() string            { return proto.CompactTextString(m) }
func (*Favorit) ProtoMessage()               {}
func (*Favorit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *Favorit) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Favorit) GetOpType() string {
	if m != nil {
		return m.OpType
	}
	return ""
}

func (m *Favorit) GetGoodsType() string {
	if m != nil {
		return m.GoodsType
	}
	return ""
}

func (m *Favorit) GetGoodsId() string {
	if m != nil {
		return m.GoodsId
	}
	return ""
}

type UserFavoritResponse struct {
	Code        uint32     `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	FavoritList []*Favorit `protobuf:"bytes,2,rep,name=favorit_list,json=favoritList" json:"favorit_list,omitempty"`
}

func (m *UserFavoritResponse) Reset()                    { *m = UserFavoritResponse{} }
func (m *UserFavoritResponse) String() string            { return proto.CompactTextString(m) }
func (*UserFavoritResponse) ProtoMessage()               {}
func (*UserFavoritResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *UserFavoritResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserFavoritResponse) GetFavoritList() []*Favorit {
	if m != nil {
		return m.FavoritList
	}
	return nil
}

type DataPresale struct {
	DataPresaleId string `protobuf:"bytes,1,opt,name=data_presale_id,json=dataPresaleId" json:"data_presale_id,omitempty"`
	UserName      string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	AssetId       string `protobuf:"bytes,3,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
	DataReqId     string `protobuf:"bytes,4,opt,name=data_req_id,json=dataReqId" json:"data_req_id,omitempty"`
	Consumer      string `protobuf:"bytes,5,opt,name=consumer" json:"consumer,omitempty"`
}

func (m *DataPresale) Reset()                    { *m = DataPresale{} }
func (m *DataPresale) String() string            { return proto.CompactTextString(m) }
func (*DataPresale) ProtoMessage()               {}
func (*DataPresale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *DataPresale) GetDataPresaleId() string {
	if m != nil {
		return m.DataPresaleId
	}
	return ""
}

func (m *DataPresale) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *DataPresale) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *DataPresale) GetDataReqId() string {
	if m != nil {
		return m.DataReqId
	}
	return ""
}

func (m *DataPresale) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

type UserDataPresaleResponse struct {
	Code            uint32         `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	DataPresaleList []*DataPresale `protobuf:"bytes,2,rep,name=data_presale_list,json=dataPresaleList" json:"data_presale_list,omitempty"`
}

func (m *UserDataPresaleResponse) Reset()                    { *m = UserDataPresaleResponse{} }
func (m *UserDataPresaleResponse) String() string            { return proto.CompactTextString(m) }
func (*UserDataPresaleResponse) ProtoMessage()               {}
func (*UserDataPresaleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

func (m *UserDataPresaleResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserDataPresaleResponse) GetDataPresaleList() []*DataPresale {
	if m != nil {
		return m.DataPresaleList
	}
	return nil
}

type AssetIdRequest struct {
	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id,omitempty"`
}

func (m *AssetIdRequest) Reset()                    { *m = AssetIdRequest{} }
func (m *AssetIdRequest) String() string            { return proto.CompactTextString(m) }
func (*AssetIdRequest) ProtoMessage()               {}
func (*AssetIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

func (m *AssetIdRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

type AssetInfoResponse struct {
	Code      uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	AssetInfo *Asset `protobuf:"bytes,2,opt,name=asset_info,json=assetInfo" json:"asset_info,omitempty"`
}

func (m *AssetInfoResponse) Reset()                    { *m = AssetInfoResponse{} }
func (m *AssetInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*AssetInfoResponse) ProtoMessage()               {}
func (*AssetInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

func (m *AssetInfoResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AssetInfoResponse) GetAssetInfo() *Asset {
	if m != nil {
		return m.AssetInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*AllRequest)(nil), "storage.AllRequest")
	proto.RegisterType((*UserRequest)(nil), "storage.UserRequest")
	proto.RegisterType((*FileUploadRequest)(nil), "storage.FileUploadRequest")
	proto.RegisterType((*FileUploadResponse)(nil), "storage.FileUploadResponse")
	proto.RegisterType((*FileUploadStatRequest)(nil), "storage.FileUploadStatRequest")
	proto.RegisterType((*FileUploadStatResponse)(nil), "storage.FileUploadStatResponse")
	proto.RegisterType((*DownLoadRequest)(nil), "storage.DownLoadRequest")
	proto.RegisterType((*DownLoadResponse)(nil), "storage.DownLoadResponse")
	proto.RegisterType((*Request)(nil), "storage.Request")
	proto.RegisterType((*Response)(nil), "storage.Response")
	proto.RegisterType((*InsertTokenRequest)(nil), "storage.InsertTokenRequest")
	proto.RegisterType((*InsertTokenResponse)(nil), "storage.InsertTokenResponse")
	proto.RegisterType((*TokenRequest)(nil), "storage.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "storage.TokenResponse")
	proto.RegisterType((*DelTokenRequest)(nil), "storage.DelTokenRequest")
	proto.RegisterType((*DelTokenResponse)(nil), "storage.DelTokenResponse")
	proto.RegisterType((*AgeTokenRequest)(nil), "storage.AgeTokenRequest")
	proto.RegisterType((*AgeTokenResponse)(nil), "storage.AgeTokenResponse")
	proto.RegisterType((*UserFileListRequest)(nil), "storage.UserFileListRequest")
	proto.RegisterType((*File)(nil), "storage.File")
	proto.RegisterType((*UserFileListResponse)(nil), "storage.UserFileListResponse")
	proto.RegisterType((*UserRequireListRequest)(nil), "storage.UserRequireListRequest")
	proto.RegisterType((*Requirement)(nil), "storage.Requirement")
	proto.RegisterType((*UserRequireListResponse)(nil), "storage.UserRequireListResponse")
	proto.RegisterType((*AllRequireListResponse)(nil), "storage.AllRequireListResponse")
	proto.RegisterType((*FeatureRequireListRequest)(nil), "storage.FeatureRequireListRequest")
	proto.RegisterType((*FeatureRequireListResponse)(nil), "storage.FeatureRequireListResponse")
	proto.RegisterType((*UserAssetListRequest)(nil), "storage.UserAssetListRequest")
	proto.RegisterType((*UserAsset)(nil), "storage.UserAsset")
	proto.RegisterType((*UserAssetListResponse)(nil), "storage.UserAssetListResponse")
	proto.RegisterType((*Asset)(nil), "storage.Asset")
	proto.RegisterType((*AssetListRequest)(nil), "storage.AssetListRequest")
	proto.RegisterType((*AssetListResponse)(nil), "storage.AssetListResponse")
	proto.RegisterType((*RecentTx)(nil), "storage.RecentTx")
	proto.RegisterType((*RecentTxListRequest)(nil), "storage.RecentTxListRequest")
	proto.RegisterType((*RecentTxListResponse)(nil), "storage.RecentTxListResponse")
	proto.RegisterType((*UserTxListResponse)(nil), "storage.UserTxListResponse")
	proto.RegisterType((*AllTxNumResponse)(nil), "storage.AllTxNumResponse")
	proto.RegisterType((*SumTxAmountRequest)(nil), "storage.SumTxAmountRequest")
	proto.RegisterType((*SumTxAmountResponse)(nil), "storage.SumTxAmountResponse")
	proto.RegisterType((*DayTxNumRequest)(nil), "storage.DayTxNumRequest")
	proto.RegisterType((*DayTxNumResponse)(nil), "storage.DayTxNumResponse")
	proto.RegisterType((*WeekTxNumResponse)(nil), "storage.WeekTxNumResponse")
	proto.RegisterType((*DayAssetNumResponse)(nil), "storage.DayAssetNumResponse")
	proto.RegisterType((*WeekAssetNumResponse)(nil), "storage.WeekAssetNumResponse")
	proto.RegisterType((*DayRequirementNumResponse)(nil), "storage.DayRequirementNumResponse")
	proto.RegisterType((*WeekRequirementNumResponse)(nil), "storage.WeekRequirementNumResponse")
	proto.RegisterType((*Node)(nil), "storage.Node")
	proto.RegisterType((*NodeInfosResponse)(nil), "storage.NodeInfosResponse")
	proto.RegisterType((*Transfer)(nil), "storage.Transfer")
	proto.RegisterType((*TransferListResponse)(nil), "storage.TransferListResponse")
	proto.RegisterType((*Favorit)(nil), "storage.Favorit")
	proto.RegisterType((*UserFavoritResponse)(nil), "storage.UserFavoritResponse")
	proto.RegisterType((*DataPresale)(nil), "storage.DataPresale")
	proto.RegisterType((*UserDataPresaleResponse)(nil), "storage.UserDataPresaleResponse")
	proto.RegisterType((*AssetIdRequest)(nil), "storage.AssetIdRequest")
	proto.RegisterType((*AssetInfoResponse)(nil), "storage.AssetInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Storage service

type StorageClient interface {
	GetFileUploadURL(ctx context.Context, in *FileUploadRequest, opts ...client.CallOption) (*FileUploadResponse, error)
	GetFileUploadStat(ctx context.Context, in *FileUploadStatRequest, opts ...client.CallOption) (*FileUploadStatResponse, error)
	GetDownLoadURL(ctx context.Context, in *DownLoadRequest, opts ...client.CallOption) (*DownLoadResponse, error)
	GetUserFileList(ctx context.Context, in *UserFileListRequest, opts ...client.CallOption) (*UserFileListResponse, error)
	GetTx(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 	rpc GetUserInfo(UserInfoRequest) returns (UserInfoResponse) {}
	// 	rpc GetUserNum(UserNumRequest) returns (UserNumResponse) {}
	InsertUserToken(ctx context.Context, in *InsertTokenRequest, opts ...client.CallOption) (*InsertTokenResponse, error)
	GetUserToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error)
	DelUserToken(ctx context.Context, in *DelTokenRequest, opts ...client.CallOption) (*DelTokenResponse, error)
	AgeUserToken(ctx context.Context, in *AgeTokenRequest, opts ...client.CallOption) (*AgeTokenResponse, error)
	GetUserRequirementList(ctx context.Context, in *UserRequireListRequest, opts ...client.CallOption) (*UserRequireListResponse, error)
	GetRequirementListByFeature(ctx context.Context, in *FeatureRequireListRequest, opts ...client.CallOption) (*FeatureRequireListResponse, error)
	GetAllRequirementList(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*AllRequireListResponse, error)
	GetUserAssetList(ctx context.Context, in *UserAssetListRequest, opts ...client.CallOption) (*UserAssetListResponse, error)
	GetUserPurchaseAssetList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserAssetListResponse, error)
	GetAssetByAssetId(ctx context.Context, in *AssetIdRequest, opts ...client.CallOption) (*AssetInfoResponse, error)
	GetAllAssetList(ctx context.Context, in *AssetListRequest, opts ...client.CallOption) (*AssetListResponse, error)
	GetRecentTxList(ctx context.Context, in *RecentTxListRequest, opts ...client.CallOption) (*RecentTxListResponse, error)
	GetUserTxList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserTxListResponse, error)
	GetRecentTransferList(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*TransferListResponse, error)
	GetAllTxNum(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*AllTxNumResponse, error)
	GetTxNumByDay(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*DayTxNumResponse, error)
	GetTxNumByWeek(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*WeekTxNumResponse, error)
	GetAssetNumByDay(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*DayAssetNumResponse, error)
	GetAssetNumByWeek(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*WeekAssetNumResponse, error)
	GetRequirementNumByDay(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*DayRequirementNumResponse, error)
	GetRequirementNumByWeek(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*WeekRequirementNumResponse, error)
	GetSumTxAmount(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*SumTxAmountResponse, error)
	GetNodeInfos(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*NodeInfosResponse, error)
	GetUserFavorit(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserFavoritResponse, error)
	GetUserDataPresale(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDataPresaleResponse, error)
}

type storageClient struct {
	c           client.Client
	serviceName string
}

func NewStorageClient(serviceName string, c client.Client) StorageClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "storage"
	}
	return &storageClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *storageClient) GetFileUploadURL(ctx context.Context, in *FileUploadRequest, opts ...client.CallOption) (*FileUploadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetFileUploadURL", in)
	out := new(FileUploadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetFileUploadStat(ctx context.Context, in *FileUploadStatRequest, opts ...client.CallOption) (*FileUploadStatResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetFileUploadStat", in)
	out := new(FileUploadStatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetDownLoadURL(ctx context.Context, in *DownLoadRequest, opts ...client.CallOption) (*DownLoadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetDownLoadURL", in)
	out := new(DownLoadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserFileList(ctx context.Context, in *UserFileListRequest, opts ...client.CallOption) (*UserFileListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserFileList", in)
	out := new(UserFileListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetTx(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetTx", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) InsertUserToken(ctx context.Context, in *InsertTokenRequest, opts ...client.CallOption) (*InsertTokenResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.InsertUserToken", in)
	out := new(InsertTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserToken", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DelUserToken(ctx context.Context, in *DelTokenRequest, opts ...client.CallOption) (*DelTokenResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.DelUserToken", in)
	out := new(DelTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) AgeUserToken(ctx context.Context, in *AgeTokenRequest, opts ...client.CallOption) (*AgeTokenResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.AgeUserToken", in)
	out := new(AgeTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserRequirementList(ctx context.Context, in *UserRequireListRequest, opts ...client.CallOption) (*UserRequireListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserRequirementList", in)
	out := new(UserRequireListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetRequirementListByFeature(ctx context.Context, in *FeatureRequireListRequest, opts ...client.CallOption) (*FeatureRequireListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetRequirementListByFeature", in)
	out := new(FeatureRequireListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAllRequirementList(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*AllRequireListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetAllRequirementList", in)
	out := new(AllRequireListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserAssetList(ctx context.Context, in *UserAssetListRequest, opts ...client.CallOption) (*UserAssetListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserAssetList", in)
	out := new(UserAssetListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserPurchaseAssetList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserAssetListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserPurchaseAssetList", in)
	out := new(UserAssetListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAssetByAssetId(ctx context.Context, in *AssetIdRequest, opts ...client.CallOption) (*AssetInfoResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetAssetByAssetId", in)
	out := new(AssetInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAllAssetList(ctx context.Context, in *AssetListRequest, opts ...client.CallOption) (*AssetListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetAllAssetList", in)
	out := new(AssetListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetRecentTxList(ctx context.Context, in *RecentTxListRequest, opts ...client.CallOption) (*RecentTxListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetRecentTxList", in)
	out := new(RecentTxListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserTxList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserTxListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserTxList", in)
	out := new(UserTxListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetRecentTransferList(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*TransferListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetRecentTransferList", in)
	out := new(TransferListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAllTxNum(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*AllTxNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetAllTxNum", in)
	out := new(AllTxNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetTxNumByDay(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*DayTxNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetTxNumByDay", in)
	out := new(DayTxNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetTxNumByWeek(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*WeekTxNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetTxNumByWeek", in)
	out := new(WeekTxNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAssetNumByDay(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*DayAssetNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetAssetNumByDay", in)
	out := new(DayAssetNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAssetNumByWeek(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*WeekAssetNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetAssetNumByWeek", in)
	out := new(WeekAssetNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetRequirementNumByDay(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*DayRequirementNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetRequirementNumByDay", in)
	out := new(DayRequirementNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetRequirementNumByWeek(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*WeekRequirementNumResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetRequirementNumByWeek", in)
	out := new(WeekRequirementNumResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetSumTxAmount(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*SumTxAmountResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetSumTxAmount", in)
	out := new(SumTxAmountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetNodeInfos(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*NodeInfosResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetNodeInfos", in)
	out := new(NodeInfosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserFavorit(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserFavoritResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserFavorit", in)
	out := new(UserFavoritResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetUserDataPresale(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDataPresaleResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Storage.GetUserDataPresale", in)
	out := new(UserDataPresaleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Storage service

type StorageHandler interface {
	GetFileUploadURL(context.Context, *FileUploadRequest, *FileUploadResponse) error
	GetFileUploadStat(context.Context, *FileUploadStatRequest, *FileUploadStatResponse) error
	GetDownLoadURL(context.Context, *DownLoadRequest, *DownLoadResponse) error
	GetUserFileList(context.Context, *UserFileListRequest, *UserFileListResponse) error
	GetTx(context.Context, *Request, *Response) error
	// 	rpc GetUserInfo(UserInfoRequest) returns (UserInfoResponse) {}
	// 	rpc GetUserNum(UserNumRequest) returns (UserNumResponse) {}
	InsertUserToken(context.Context, *InsertTokenRequest, *InsertTokenResponse) error
	GetUserToken(context.Context, *TokenRequest, *TokenResponse) error
	DelUserToken(context.Context, *DelTokenRequest, *DelTokenResponse) error
	AgeUserToken(context.Context, *AgeTokenRequest, *AgeTokenResponse) error
	GetUserRequirementList(context.Context, *UserRequireListRequest, *UserRequireListResponse) error
	GetRequirementListByFeature(context.Context, *FeatureRequireListRequest, *FeatureRequireListResponse) error
	GetAllRequirementList(context.Context, *AllRequest, *AllRequireListResponse) error
	GetUserAssetList(context.Context, *UserAssetListRequest, *UserAssetListResponse) error
	GetUserPurchaseAssetList(context.Context, *UserRequest, *UserAssetListResponse) error
	GetAssetByAssetId(context.Context, *AssetIdRequest, *AssetInfoResponse) error
	GetAllAssetList(context.Context, *AssetListRequest, *AssetListResponse) error
	GetRecentTxList(context.Context, *RecentTxListRequest, *RecentTxListResponse) error
	GetUserTxList(context.Context, *UserRequest, *UserTxListResponse) error
	GetRecentTransferList(context.Context, *AllRequest, *TransferListResponse) error
	GetAllTxNum(context.Context, *AllRequest, *AllTxNumResponse) error
	GetTxNumByDay(context.Context, *AllRequest, *DayTxNumResponse) error
	GetTxNumByWeek(context.Context, *AllRequest, *WeekTxNumResponse) error
	GetAssetNumByDay(context.Context, *AllRequest, *DayAssetNumResponse) error
	GetAssetNumByWeek(context.Context, *AllRequest, *WeekAssetNumResponse) error
	GetRequirementNumByDay(context.Context, *AllRequest, *DayRequirementNumResponse) error
	GetRequirementNumByWeek(context.Context, *AllRequest, *WeekRequirementNumResponse) error
	GetSumTxAmount(context.Context, *AllRequest, *SumTxAmountResponse) error
	GetNodeInfos(context.Context, *AllRequest, *NodeInfosResponse) error
	GetUserFavorit(context.Context, *UserRequest, *UserFavoritResponse) error
	GetUserDataPresale(context.Context, *UserRequest, *UserDataPresaleResponse) error
}

func RegisterStorageHandler(s server.Server, hdlr StorageHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Storage{hdlr}, opts...))
}

type Storage struct {
	StorageHandler
}

func (h *Storage) GetFileUploadURL(ctx context.Context, in *FileUploadRequest, out *FileUploadResponse) error {
	return h.StorageHandler.GetFileUploadURL(ctx, in, out)
}

func (h *Storage) GetFileUploadStat(ctx context.Context, in *FileUploadStatRequest, out *FileUploadStatResponse) error {
	return h.StorageHandler.GetFileUploadStat(ctx, in, out)
}

func (h *Storage) GetDownLoadURL(ctx context.Context, in *DownLoadRequest, out *DownLoadResponse) error {
	return h.StorageHandler.GetDownLoadURL(ctx, in, out)
}

func (h *Storage) GetUserFileList(ctx context.Context, in *UserFileListRequest, out *UserFileListResponse) error {
	return h.StorageHandler.GetUserFileList(ctx, in, out)
}

func (h *Storage) GetTx(ctx context.Context, in *Request, out *Response) error {
	return h.StorageHandler.GetTx(ctx, in, out)
}

func (h *Storage) InsertUserToken(ctx context.Context, in *InsertTokenRequest, out *InsertTokenResponse) error {
	return h.StorageHandler.InsertUserToken(ctx, in, out)
}

func (h *Storage) GetUserToken(ctx context.Context, in *TokenRequest, out *TokenResponse) error {
	return h.StorageHandler.GetUserToken(ctx, in, out)
}

func (h *Storage) DelUserToken(ctx context.Context, in *DelTokenRequest, out *DelTokenResponse) error {
	return h.StorageHandler.DelUserToken(ctx, in, out)
}

func (h *Storage) AgeUserToken(ctx context.Context, in *AgeTokenRequest, out *AgeTokenResponse) error {
	return h.StorageHandler.AgeUserToken(ctx, in, out)
}

func (h *Storage) GetUserRequirementList(ctx context.Context, in *UserRequireListRequest, out *UserRequireListResponse) error {
	return h.StorageHandler.GetUserRequirementList(ctx, in, out)
}

func (h *Storage) GetRequirementListByFeature(ctx context.Context, in *FeatureRequireListRequest, out *FeatureRequireListResponse) error {
	return h.StorageHandler.GetRequirementListByFeature(ctx, in, out)
}

func (h *Storage) GetAllRequirementList(ctx context.Context, in *AllRequest, out *AllRequireListResponse) error {
	return h.StorageHandler.GetAllRequirementList(ctx, in, out)
}

func (h *Storage) GetUserAssetList(ctx context.Context, in *UserAssetListRequest, out *UserAssetListResponse) error {
	return h.StorageHandler.GetUserAssetList(ctx, in, out)
}

func (h *Storage) GetUserPurchaseAssetList(ctx context.Context, in *UserRequest, out *UserAssetListResponse) error {
	return h.StorageHandler.GetUserPurchaseAssetList(ctx, in, out)
}

func (h *Storage) GetAssetByAssetId(ctx context.Context, in *AssetIdRequest, out *AssetInfoResponse) error {
	return h.StorageHandler.GetAssetByAssetId(ctx, in, out)
}

func (h *Storage) GetAllAssetList(ctx context.Context, in *AssetListRequest, out *AssetListResponse) error {
	return h.StorageHandler.GetAllAssetList(ctx, in, out)
}

func (h *Storage) GetRecentTxList(ctx context.Context, in *RecentTxListRequest, out *RecentTxListResponse) error {
	return h.StorageHandler.GetRecentTxList(ctx, in, out)
}

func (h *Storage) GetUserTxList(ctx context.Context, in *UserRequest, out *UserTxListResponse) error {
	return h.StorageHandler.GetUserTxList(ctx, in, out)
}

func (h *Storage) GetRecentTransferList(ctx context.Context, in *AllRequest, out *TransferListResponse) error {
	return h.StorageHandler.GetRecentTransferList(ctx, in, out)
}

func (h *Storage) GetAllTxNum(ctx context.Context, in *AllRequest, out *AllTxNumResponse) error {
	return h.StorageHandler.GetAllTxNum(ctx, in, out)
}

func (h *Storage) GetTxNumByDay(ctx context.Context, in *AllRequest, out *DayTxNumResponse) error {
	return h.StorageHandler.GetTxNumByDay(ctx, in, out)
}

func (h *Storage) GetTxNumByWeek(ctx context.Context, in *AllRequest, out *WeekTxNumResponse) error {
	return h.StorageHandler.GetTxNumByWeek(ctx, in, out)
}

func (h *Storage) GetAssetNumByDay(ctx context.Context, in *AllRequest, out *DayAssetNumResponse) error {
	return h.StorageHandler.GetAssetNumByDay(ctx, in, out)
}

func (h *Storage) GetAssetNumByWeek(ctx context.Context, in *AllRequest, out *WeekAssetNumResponse) error {
	return h.StorageHandler.GetAssetNumByWeek(ctx, in, out)
}

func (h *Storage) GetRequirementNumByDay(ctx context.Context, in *AllRequest, out *DayRequirementNumResponse) error {
	return h.StorageHandler.GetRequirementNumByDay(ctx, in, out)
}

func (h *Storage) GetRequirementNumByWeek(ctx context.Context, in *AllRequest, out *WeekRequirementNumResponse) error {
	return h.StorageHandler.GetRequirementNumByWeek(ctx, in, out)
}

func (h *Storage) GetSumTxAmount(ctx context.Context, in *AllRequest, out *SumTxAmountResponse) error {
	return h.StorageHandler.GetSumTxAmount(ctx, in, out)
}

func (h *Storage) GetNodeInfos(ctx context.Context, in *AllRequest, out *NodeInfosResponse) error {
	return h.StorageHandler.GetNodeInfos(ctx, in, out)
}

func (h *Storage) GetUserFavorit(ctx context.Context, in *UserRequest, out *UserFavoritResponse) error {
	return h.StorageHandler.GetUserFavorit(ctx, in, out)
}

func (h *Storage) GetUserDataPresale(ctx context.Context, in *UserRequest, out *UserDataPresaleResponse) error {
	return h.StorageHandler.GetUserDataPresale(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/bottos-project/bottos/service/storage/proto/storage-api.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 2198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0x4f, 0x77, 0xdb, 0xc6,
	0x11, 0x27, 0x45, 0x4a, 0x24, 0x87, 0x94, 0x48, 0xae, 0x28, 0x99, 0xa2, 0x25, 0xdb, 0xd9, 0xb4,
	0x79, 0x76, 0x52, 0xcb, 0xad, 0xd3, 0x7f, 0x87, 0xb6, 0x89, 0x1c, 0xc6, 0x0a, 0xf3, 0x6c, 0x55,
	0x8f, 0x92, 0xd2, 0x53, 0xc3, 0x07, 0x11, 0x2b, 0x12, 0xcf, 0x24, 0x01, 0x03, 0x0b, 0x9b, 0xf4,
	0xa9, 0xb7, 0x1e, 0xfb, 0x39, 0x7a, 0xe9, 0xf7, 0xe8, 0xa5, 0x1f, 0xa0, 0x9f, 0xa0, 0x1f, 0xa3,
	0x6f, 0x67, 0x17, 0xc0, 0x02, 0x04, 0x41, 0x25, 0x8e, 0x6f, 0xdc, 0x99, 0xd9, 0xdf, 0xcc, 0xce,
	0xec, 0x0c, 0x66, 0x96, 0xf0, 0xa7, 0x91, 0xc5, 0xc7, 0xfe, 0xf5, 0xf1, 0xd0, 0x9e, 0x3e, 0x19,
	0xda, 0x26, 0x7b, 0x72, 0x6d, 0x73, 0x6e, 0x7b, 0x4f, 0x3c, 0xe6, 0xbe, 0xb1, 0x86, 0xec, 0x89,
	0xc7, 0x6d, 0xd7, 0x18, 0xb1, 0x27, 0x8e, 0x6b, 0x73, 0x3b, 0x58, 0x3d, 0x36, 0x1c, 0xeb, 0x18,
	0x29, 0xa4, 0xa4, 0x48, 0xb4, 0x06, 0x70, 0x32, 0x99, 0xf4, 0xd9, 0x6b, 0x9f, 0x79, 0x9c, 0x3e,
	0x82, 0xea, 0x95, 0xc7, 0x5c, 0xb5, 0x24, 0x1d, 0x28, 0xfb, 0x1e, 0x73, 0x67, 0xc6, 0x94, 0xb5,
	0xf3, 0x0f, 0xf2, 0x0f, 0x2b, 0xfd, 0x70, 0x4d, 0xff, 0x9d, 0x87, 0xe6, 0x73, 0x6b, 0xc2, 0xae,
	0x9c, 0x89, 0x6d, 0x98, 0xb7, 0xd8, 0x41, 0xee, 0x42, 0xe5, 0xc6, 0x9a, 0xb0, 0x01, 0x32, 0x37,
	0x24, 0x53, 0x10, 0xce, 0x74, 0xa6, 0x67, 0xbd, 0x63, 0xed, 0xc2, 0x83, 0xfc, 0xc3, 0xa2, 0x64,
	0x5e, 0x58, 0xef, 0x18, 0xb9, 0x0f, 0x55, 0x64, 0x3a, 0xf6, 0xc4, 0x1a, 0x2e, 0xda, 0x45, 0xdc,
	0x0b, 0x82, 0x74, 0x8e, 0x94, 0x50, 0x60, 0xe6, 0x4f, 0xaf, 0x99, 0xdb, 0xde, 0xc4, 0xfd, 0x28,
	0x70, 0x86, 0x14, 0x72, 0x08, 0x15, 0xcf, 0x1a, 0xcd, 0x0c, 0xee, 0xbb, 0xac, 0xbd, 0x85, 0xfb,
	0x23, 0x02, 0x75, 0x81, 0xe8, 0x47, 0xf1, 0x1c, 0x7b, 0xe6, 0x31, 0xb2, 0x0f, 0x5b, 0x2e, 0xf3,
	0xfc, 0x09, 0x57, 0x27, 0x51, 0x2b, 0xd2, 0x86, 0xd2, 0x94, 0x79, 0x9e, 0x31, 0x0a, 0x4e, 0x11,
	0x2c, 0xc9, 0xa7, 0xd0, 0x74, 0x5c, 0x26, 0x70, 0x99, 0x39, 0x70, 0x7c, 0x3e, 0xf0, 0xdd, 0x09,
	0x1e, 0xa6, 0xd2, 0xaf, 0x87, 0x8c, 0x73, 0x9f, 0x5f, 0xb9, 0x13, 0x7a, 0x0e, 0x7b, 0x91, 0xce,
	0x0b, 0x6e, 0xf0, 0xf7, 0x75, 0x21, 0xfd, 0x1e, 0xf6, 0x93, 0x88, 0x3f, 0xfa, 0x24, 0x04, 0x8a,
	0x61, 0x24, 0x0a, 0x7d, 0xfc, 0x4d, 0xbf, 0x85, 0x7a, 0xd7, 0x7e, 0x3b, 0x7b, 0xf1, 0x13, 0x84,
	0x9b, 0x3a, 0xd0, 0x88, 0xb0, 0x7e, 0x1a, 0x7f, 0x8f, 0x58, 0xba, 0xbf, 0x4f, 0x19, 0xfa, 0xfb,
	0x77, 0x50, 0x0a, 0xac, 0x26, 0x50, 0xe4, 0x73, 0xcb, 0x54, 0x6a, 0xf0, 0xb7, 0x50, 0x62, 0x0c,
	0x87, 0xb6, 0x3f, 0xe3, 0x81, 0x12, 0xb5, 0xa4, 0x87, 0x50, 0x0e, 0x4d, 0x6c, 0x40, 0x61, 0xea,
	0x8d, 0xd4, 0x46, 0xf1, 0x93, 0x3e, 0x07, 0xd2, 0x9b, 0x79, 0xcc, 0xe5, 0x97, 0xf6, 0x2b, 0x36,
	0xbb, 0x8d, 0x5f, 0x5a, 0xb0, 0xc9, 0x85, 0xac, 0xd2, 0x23, 0x17, 0xf4, 0x11, 0xec, 0xc6, 0x70,
	0x94, 0x42, 0x02, 0x45, 0x91, 0xde, 0x08, 0xb2, 0xdd, 0xc7, 0xdf, 0xf4, 0x4b, 0xa8, 0xbd, 0xa7,
	0xb2, 0x37, 0xb0, 0x1d, 0x57, 0xf3, 0x83, 0x21, 0x44, 0xc6, 0x59, 0x68, 0xef, 0x80, 0x5b, 0xd3,
	0xe0, 0x9e, 0x80, 0x24, 0x5d, 0x5a, 0xd3, 0xc8, 0xf2, 0xa2, 0x66, 0xf9, 0x57, 0x50, 0xef, 0xb2,
	0xc9, 0x7b, 0x1a, 0xff, 0x09, 0x34, 0x22, 0x90, 0x0c, 0x37, 0x7d, 0x06, 0xf5, 0x93, 0x11, 0x8b,
	0x29, 0x6b, 0x43, 0x49, 0x58, 0x6b, 0xfb, 0xf2, 0x8a, 0x15, 0xfa, 0xc1, 0x52, 0x80, 0x46, 0xc2,
	0x19, 0xa0, 0xbf, 0x82, 0x5d, 0x51, 0x20, 0x45, 0x9e, 0xbd, 0xb0, 0xbc, 0xdb, 0xe4, 0x2c, 0xfd,
	0x4f, 0x1e, 0x8a, 0x42, 0x3e, 0x9e, 0x10, 0xf9, 0xac, 0xfa, 0xb7, 0x91, 0x5d, 0xff, 0x0a, 0xeb,
	0xea, 0x5f, 0x71, 0xa9, 0xfe, 0x05, 0xf0, 0x63, 0xc3, 0x1b, 0x63, 0x79, 0x54, 0xba, 0xbf, 0x31,
	0xbc, 0x31, 0x79, 0x0c, 0xc4, 0xf0, 0xf9, 0xd8, 0x76, 0xad, 0x77, 0xcc, 0x1c, 0xa8, 0x2f, 0x83,
	0xaa, 0x92, 0xcd, 0x88, 0x73, 0xa1, 0x3e, 0x19, 0x57, 0xd0, 0x8a, 0xfb, 0x60, 0xb5, 0xbf, 0xc8,
	0x23, 0x28, 0x07, 0x72, 0xed, 0x8d, 0x07, 0x85, 0x87, 0xd5, 0xa7, 0xdb, 0xc7, 0x4a, 0xc1, 0xb1,
	0x60, 0xf4, 0x43, 0x36, 0xfd, 0x35, 0xec, 0x07, 0xdf, 0x1e, 0xcb, 0xbd, 0xb5, 0x77, 0xff, 0xbb,
	0x01, 0x55, 0xb5, 0x65, 0xca, 0x66, 0x9c, 0xfc, 0x1c, 0x76, 0xdc, 0x68, 0x39, 0x08, 0xb3, 0x7c,
	0x5b, 0xa3, 0xf6, 0xcc, 0x18, 0xe4, 0x46, 0xe2, 0xda, 0x3d, 0x82, 0x86, 0x0e, 0x81, 0x32, 0xaa,
	0xa8, 0x68, 0x74, 0x8c, 0x9a, 0xf0, 0x3b, 0xc3, 0x6f, 0xc8, 0x80, 0x1b, 0xa3, 0xd0, 0xef, 0x92,
	0x74, 0x69, 0x8c, 0x84, 0x80, 0x67, 0x4c, 0x1d, 0x11, 0x3b, 0x83, 0x07, 0x9e, 0x07, 0x49, 0x3a,
	0x37, 0xf8, 0x58, 0x13, 0xc0, 0xd0, 0x6c, 0xe9, 0x02, 0x18, 0x9c, 0xfb, 0x50, 0x65, 0x73, 0xc7,
	0x12, 0x1a, 0x44, 0xa2, 0x95, 0xd0, 0xb9, 0x20, 0x49, 0x98, 0x68, 0x2d, 0xd8, 0x74, 0x5c, 0x6b,
	0xc8, 0xda, 0x65, 0xd4, 0x2e, 0x17, 0xe4, 0x01, 0x54, 0x4d, 0xe6, 0x0d, 0x5d, 0xcb, 0xe1, 0x96,
	0x3d, 0x6b, 0x57, 0x10, 0x57, 0x27, 0x91, 0x8f, 0xa0, 0xe6, 0xf8, 0xd7, 0x13, 0xcb, 0x1b, 0x0f,
	0x4c, 0x83, 0xb3, 0x36, 0x20, 0x72, 0x55, 0xd1, 0xba, 0x06, 0x67, 0x94, 0xc1, 0x9d, 0xa5, 0x90,
	0x64, 0x04, 0xfb, 0xb7, 0x61, 0x28, 0xb4, 0x78, 0xb7, 0xc2, 0x78, 0x6b, 0x61, 0xea, 0xeb, 0x82,
	0xd4, 0x84, 0x7d, 0xd5, 0x83, 0x7c, 0x48, 0x2d, 0x7f, 0x80, 0x83, 0xe7, 0x32, 0x30, 0x29, 0x57,
	0x2c, 0x11, 0xc8, 0x7c, 0x32, 0x90, 0x74, 0x0c, 0x9d, 0xb4, 0xdd, 0x1f, 0xc0, 0xce, 0xa7, 0x32,
	0xbd, 0x4e, 0x3c, 0x8f, 0xf1, 0xdb, 0x66, 0xc1, 0xff, 0x36, 0xa0, 0x12, 0x6e, 0x22, 0x07, 0x50,
	0x36, 0xc4, 0x8f, 0xe8, 0xf6, 0x97, 0x70, 0xdd, 0x33, 0xc9, 0x11, 0x80, 0x64, 0x69, 0x37, 0xbf,
	0x82, 0x94, 0xb4, 0xfb, 0x5c, 0x58, 0x77, 0x9f, 0x8b, 0xeb, 0xee, 0xf3, 0xe6, 0xd2, 0x7d, 0xfe,
	0x08, 0x6a, 0xca, 0x05, 0x12, 0x42, 0xde, 0xf8, 0xaa, 0xa2, 0x21, 0x86, 0x26, 0x82, 0x20, 0xa5,
	0x98, 0x48, 0x5a, 0x56, 0x94, 0x57, 0x67, 0x45, 0x25, 0x23, 0x2b, 0x60, 0x39, 0x2b, 0xee, 0x43,
	0xd5, 0xc7, 0x06, 0x4a, 0x26, 0x45, 0x55, 0x02, 0x4b, 0x92, 0xca, 0x89, 0xbd, 0x44, 0x78, 0x32,
	0xee, 0xc0, 0xef, 0x61, 0x3b, 0x26, 0xac, 0x6e, 0x01, 0x09, 0x6f, 0x41, 0xc8, 0xed, 0xc7, 0x05,
	0xe9, 0xdf, 0x0a, 0xb0, 0xb9, 0x36, 0x9a, 0x59, 0x55, 0x2c, 0x1e, 0xe9, 0xc2, 0x9a, 0x48, 0x7f,
	0x88, 0xca, 0x95, 0x8c, 0x74, 0x69, 0x7d, 0xa4, 0xcb, 0x6b, 0x23, 0x5d, 0x59, 0x1d, 0x69, 0xc8,
	0x88, 0x74, 0x75, 0x6d, 0xa4, 0x6b, 0x4b, 0x91, 0x26, 0xd0, 0x48, 0x26, 0x21, 0xbd, 0x82, 0xe6,
	0xed, 0x22, 0xff, 0x0b, 0xa8, 0x24, 0xa3, 0xbe, 0x13, 0x46, 0x5d, 0x46, 0x3c, 0x12, 0xa0, 0xff,
	0xca, 0x8b, 0x26, 0x73, 0xc8, 0x66, 0xfc, 0x72, 0x2e, 0x3e, 0x61, 0xdc, 0x35, 0x66, 0x9e, 0x31,
	0x14, 0x76, 0x6a, 0x9f, 0x30, 0x8d, 0xda, 0x33, 0x85, 0xd6, 0x1b, 0xd7, 0x9e, 0xaa, 0xc0, 0xe3,
	0x6f, 0xb2, 0x03, 0x1b, 0xdc, 0x56, 0xc1, 0xde, 0xe0, 0x76, 0xe4, 0x9b, 0xa2, 0xee, 0x1b, 0xd1,
	0xff, 0x2e, 0x1c, 0xa6, 0xc6, 0x24, 0xfc, 0x2d, 0x68, 0xe8, 0x06, 0x19, 0x46, 0xfc, 0x2d, 0x6e,
	0xde, 0xf5, 0xc4, 0x1e, 0xbe, 0x12, 0x26, 0x94, 0x50, 0xb6, 0x84, 0xeb, 0x9e, 0x49, 0xf7, 0x60,
	0x37, 0xb0, 0x57, 0x77, 0x8f, 0x01, 0xad, 0x38, 0x39, 0xc3, 0x43, 0xbf, 0x81, 0x9a, 0x2e, 0xab,
	0x9c, 0xd4, 0xd4, 0x0a, 0xa4, 0x64, 0xf6, 0x63, 0x62, 0x74, 0x00, 0x44, 0x64, 0xca, 0x87, 0x53,
	0xf0, 0x47, 0x68, 0x9c, 0x4c, 0x26, 0x97, 0xf3, 0x33, 0x7f, 0x9a, 0x09, 0xbf, 0x07, 0x5b, 0x7c,
	0x2e, 0x3a, 0x2e, 0xd5, 0xae, 0x6d, 0x72, 0xb1, 0x85, 0xb6, 0x80, 0x5c, 0xf8, 0xd3, 0xcb, 0xf9,
	0xc9, 0x54, 0x4c, 0x0f, 0x81, 0x63, 0xbe, 0x81, 0xdd, 0x18, 0x35, 0x03, 0x57, 0x24, 0x2e, 0x4a,
	0x0d, 0xbc, 0x10, 0xbb, 0x22, 0x29, 0x17, 0xfe, 0x94, 0x36, 0xa1, 0xde, 0x35, 0x16, 0xca, 0x3c,
	0x09, 0xde, 0x85, 0x46, 0x44, 0xca, 0x40, 0x3e, 0x04, 0x30, 0x8d, 0xc5, 0x20, 0x66, 0x75, 0xd9,
	0x54, 0x3b, 0xe9, 0x29, 0x34, 0xff, 0xc2, 0xd8, 0xab, 0xf5, 0x30, 0xf7, 0xa0, 0xfa, 0x96, 0xb1,
	0x57, 0x11, 0x4e, 0x41, 0x58, 0xf8, 0x36, 0xd8, 0x4b, 0x5f, 0xc2, 0x6e, 0xd7, 0x58, 0xe0, 0xe5,
	0x5e, 0x07, 0x45, 0x61, 0x5b, 0x58, 0xa4, 0x0a, 0x55, 0x68, 0x54, 0xd5, 0x8c, 0xf6, 0xd3, 0x73,
	0x68, 0x09, 0xbb, 0x6e, 0x85, 0xf7, 0x33, 0xd8, 0x41, 0xd3, 0x74, 0x40, 0x61, 0x5d, 0xed, 0xad,
	0x86, 0x40, 0x07, 0x70, 0xd0, 0x35, 0x16, 0xda, 0x07, 0x78, 0x1d, 0xec, 0x31, 0xec, 0x0a, 0x33,
	0x63, 0x5d, 0x61, 0x68, 0x6c, 0xd3, 0x4c, 0x62, 0xd1, 0x6b, 0xe8, 0x08, 0x93, 0x7f, 0x80, 0x86,
	0x5f, 0x42, 0x0b, 0x0d, 0x5f, 0x56, 0x21, 0xcc, 0x27, 0x6f, 0x97, 0xd0, 0xe8, 0x15, 0x14, 0xcf,
	0xc4, 0xce, 0x3b, 0x50, 0x9a, 0xd9, 0x26, 0x8b, 0xca, 0xc4, 0x96, 0x58, 0xf6, 0xcc, 0x88, 0xe1,
	0xa8, 0x12, 0x21, 0x19, 0x8e, 0x98, 0x05, 0x90, 0xe1, 0xd8, 0x2e, 0x57, 0xb5, 0xa2, 0x2c, 0x08,
	0xe7, 0xb6, 0xcb, 0xe9, 0x0c, 0x9a, 0x02, 0xb6, 0x37, 0xbb, 0xb1, 0xbd, 0x4c, 0x8b, 0x0f, 0x00,
	0x37, 0x69, 0x8e, 0x40, 0x75, 0x67, 0xfe, 0x94, 0x7c, 0xaa, 0x14, 0x4c, 0x44, 0xd6, 0x15, 0x12,
	0x5d, 0xbf, 0x40, 0x97, 0xfa, 0x30, 0xdb, 0xfe, 0x91, 0x87, 0xf2, 0xa5, 0xa8, 0x6b, 0x37, 0xcc,
	0x25, 0xbb, 0xb0, 0xc9, 0xe7, 0x03, 0x7d, 0x32, 0x97, 0xe7, 0xe0, 0x73, 0x59, 0xfc, 0xd5, 0x39,
	0xf8, 0x3c, 0x5e, 0xf8, 0x0b, 0x89, 0xe2, 0x86, 0x65, 0xb1, 0xb8, 0x54, 0x16, 0x37, 0xc3, 0xb2,
	0x78, 0x17, 0x2a, 0xb2, 0xb0, 0x09, 0xe3, 0xb7, 0x64, 0x1e, 0x20, 0x41, 0x06, 0xaf, 0x15, 0x18,
	0x74, 0x8b, 0x1e, 0x4f, 0x16, 0xe5, 0x1b, 0xe6, 0xca, 0xd3, 0x26, 0x6b, 0x4c, 0x80, 0xd4, 0xaf,
	0x71, 0x0d, 0x93, 0xce, 0xa1, 0xf4, 0xdc, 0x78, 0x63, 0xbb, 0x56, 0xf6, 0x00, 0x7c, 0x07, 0x4a,
	0xb6, 0x33, 0xc0, 0x5a, 0xad, 0x8e, 0x6e, 0x3b, 0x97, 0xa2, 0x5a, 0x1f, 0x01, 0x8c, 0x6c, 0xdb,
	0xf4, 0x24, 0x4f, 0x7d, 0xdc, 0x91, 0x82, 0xec, 0x03, 0x28, 0x4b, 0xb6, 0x65, 0x2a, 0x3f, 0x94,
	0x70, 0xdd, 0x33, 0xe9, 0xf7, 0x6a, 0x80, 0x95, 0xda, 0x33, 0x0f, 0xf7, 0x39, 0xd4, 0x6e, 0xa4,
	0x98, 0x7e, 0xb6, 0x46, 0x34, 0xbf, 0x29, 0x8c, 0xaa, 0x92, 0xc2, 0x93, 0xfd, 0x33, 0x0f, 0xd5,
	0xae, 0xc1, 0x8d, 0x73, 0x97, 0x79, 0xc6, 0x84, 0x91, 0x4f, 0xa0, 0x6e, 0x1a, 0xdc, 0x18, 0x38,
	0x72, 0xad, 0x7d, 0xcd, 0xcc, 0x48, 0xaa, 0x67, 0x8a, 0x90, 0x88, 0x63, 0x0f, 0x92, 0xbd, 0x0c,
	0x36, 0x2b, 0x7a, 0x0b, 0x54, 0x88, 0xb7, 0x40, 0xf7, 0xa0, 0x8a, 0xf8, 0x2e, 0x7b, 0x1d, 0x9d,
	0xb6, 0x22, 0x48, 0x7d, 0xf6, 0x5a, 0xb6, 0x48, 0x43, 0x7b, 0xe6, 0xf9, 0x53, 0xf5, 0x2c, 0x58,
	0xe9, 0x87, 0x6b, 0x6a, 0xcb, 0xf1, 0x46, 0x33, 0x37, 0xd3, 0x1f, 0x5f, 0x42, 0x33, 0x76, 0x94,
	0x49, 0x5a, 0x5b, 0xaf, 0x83, 0xd5, 0xb5, 0x23, 0xa2, 0x73, 0x3e, 0x83, 0x9d, 0x13, 0x69, 0x77,
	0xd0, 0xd4, 0xaf, 0x6e, 0xee, 0xe8, 0x77, 0xaa, 0xd5, 0x10, 0xa9, 0x98, 0x69, 0xd7, 0xe3, 0xa0,
	0xd3, 0xb3, 0x66, 0x37, 0x36, 0xfa, 0x2e, 0xa5, 0xd7, 0x30, 0x02, 0xa8, 0xa7, 0x7f, 0x27, 0x50,
	0x52, 0xa3, 0x3c, 0x79, 0x09, 0x8d, 0x53, 0xc6, 0xa3, 0x57, 0xc3, 0xab, 0xfe, 0x0b, 0xd2, 0x89,
	0x0d, 0xe8, 0xb1, 0xe7, 0xdd, 0xce, 0xdd, 0x54, 0x9e, 0xb4, 0x8d, 0xe6, 0xc8, 0x77, 0xd0, 0x8c,
	0xc1, 0x5d, 0x70, 0x83, 0x93, 0x7b, 0x29, 0x7b, 0xb4, 0xf7, 0xce, 0xce, 0xfd, 0x95, 0xfc, 0x10,
	0xf7, 0x14, 0x76, 0x4e, 0x19, 0x0f, 0x1e, 0x0c, 0x85, 0x91, 0xed, 0xc8, 0xe1, 0xf1, 0x27, 0xc9,
	0xce, 0x41, 0x0a, 0x27, 0x04, 0x3a, 0x87, 0xfa, 0x29, 0xe3, 0xfa, 0xeb, 0x05, 0x39, 0x8c, 0xf5,
	0xe2, 0x89, 0x87, 0x9d, 0xce, 0xd1, 0x0a, 0x6e, 0x88, 0x78, 0x0c, 0x9b, 0xa7, 0x4c, 0x74, 0x6d,
	0x8d, 0xd8, 0x64, 0x27, 0xf6, 0xea, 0x9d, 0x46, 0x28, 0x7f, 0x06, 0x75, 0xf9, 0xce, 0x87, 0x4d,
	0x0c, 0x3e, 0xa5, 0x45, 0x4e, 0x5d, 0x7e, 0x49, 0xec, 0x1c, 0xa6, 0x33, 0x43, 0xbc, 0x2f, 0xa0,
	0xa6, 0x4e, 0x24, 0xc1, 0xf6, 0xa2, 0xd2, 0xa3, 0xc3, 0xec, 0x27, 0xc9, 0x21, 0xc0, 0xd7, 0x50,
	0xeb, 0xb2, 0x49, 0x04, 0xa0, 0x79, 0x36, 0xfe, 0x54, 0xa7, 0x7b, 0x36, 0xf1, 0xfe, 0x26, 0x61,
	0x4e, 0x46, 0x2c, 0x0d, 0x26, 0xf1, 0x08, 0xa7, 0xc1, 0x24, 0x5f, 0xdc, 0x68, 0x8e, 0xfc, 0x15,
	0xf6, 0xd5, 0x71, 0xb4, 0xcf, 0x1d, 0xc6, 0xe9, 0x7e, 0x2c, 0x12, 0xcb, 0x23, 0x7c, 0xe7, 0xc1,
	0x6a, 0x81, 0x10, 0x7e, 0x0c, 0x77, 0x4f, 0x19, 0x4f, 0x40, 0x3f, 0x5b, 0xa8, 0xc9, 0x9e, 0xd0,
	0xe8, 0x2a, 0xae, 0x7a, 0x29, 0xe8, 0x7c, 0x9c, 0x29, 0x13, 0x6a, 0xfa, 0x33, 0xec, 0x9d, 0x32,
	0x1e, 0x3d, 0x6b, 0x84, 0xe7, 0xd8, 0x8d, 0x8e, 0x1f, 0xfe, 0xef, 0xa2, 0xe5, 0x40, 0xfa, 0x43,
	0x08, 0xcd, 0x91, 0x0b, 0x4c, 0xd5, 0xd8, 0x90, 0x48, 0x8e, 0x96, 0xe7, 0x48, 0xdd, 0xd4, 0x7b,
	0xab, 0xd8, 0x21, 0x68, 0x1f, 0xda, 0x0a, 0xf4, 0xdc, 0x77, 0x87, 0x63, 0xc3, 0x63, 0x11, 0x78,
	0x6b, 0xc9, 0x9f, 0xb7, 0xc3, 0xfc, 0x16, 0x8b, 0x00, 0x72, 0x9e, 0x2d, 0x54, 0xb9, 0x23, 0x77,
	0xe2, 0xf5, 0x28, 0x2c, 0x80, 0x9d, 0x4e, 0x82, 0xa1, 0x15, 0x3b, 0xc4, 0xaa, 0x4b, 0x2f, 0x46,
	0x66, 0x1d, 0xc4, 0x37, 0xe8, 0xe7, 0xed, 0xa4, 0xb1, 0x12, 0xb9, 0xaf, 0xb7, 0xfa, 0x5a, 0xee,
	0xa7, 0x0c, 0x33, 0x5a, 0xee, 0xa7, 0xcd, 0x34, 0x34, 0x47, 0xba, 0xb0, 0x1d, 0xe4, 0xde, 0x3c,
	0xc3, 0x65, 0x77, 0x63, 0xd4, 0x25, 0x94, 0x97, 0x78, 0x53, 0x94, 0x0a, 0xad, 0x49, 0x48, 0xbf,
	0x29, 0x47, 0x4b, 0xad, 0x45, 0x02, 0xee, 0x0b, 0xa8, 0x4a, 0x97, 0x61, 0x33, 0x9e, 0x0e, 0x72,
	0xa0, 0x13, 0x63, 0x0d, 0x3f, 0xcd, 0x91, 0x13, 0x3c, 0x15, 0x52, 0x9f, 0x2d, 0xba, 0xc6, 0x62,
	0x1d, 0x44, 0x72, 0xf4, 0xa0, 0x39, 0xf2, 0x15, 0xd6, 0x6b, 0x05, 0x21, 0x3a, 0xe1, 0x74, 0x8c,
	0x28, 0x5e, 0x4b, 0x83, 0x07, 0x16, 0xfd, 0x46, 0x70, 0x8f, 0xb2, 0x4d, 0x39, 0xd4, 0x4d, 0x49,
	0x8e, 0x09, 0x34, 0x47, 0x7a, 0xd1, 0x85, 0x5c, 0x63, 0xd0, 0x51, 0xcc, 0xa0, 0x14, 0xa8, 0x0b,
	0x2c, 0x4f, 0xf1, 0x4e, 0x3c, 0xc3, 0x32, 0xaa, 0x5b, 0x96, 0x3e, 0x0d, 0xd0, 0x1c, 0xb9, 0x82,
	0x3b, 0x29, 0xa0, 0xab, 0xad, 0xfc, 0x38, 0x66, 0xe5, 0x4a, 0xd8, 0xaf, 0x31, 0x08, 0xda, 0xd4,
	0xb9, 0xce, 0x7b, 0x29, 0x03, 0x2a, 0x5e, 0x07, 0xf1, 0x81, 0x09, 0x67, 0x82, 0x75, 0x91, 0x5c,
	0x1a, 0x1e, 0x68, 0x8e, 0x3c, 0x47, 0x4b, 0xb4, 0xb6, 0x73, 0x45, 0xa2, 0x24, 0x3e, 0xc5, 0xf1,
	0x16, 0x15, 0xbf, 0x9d, 0x44, 0xe1, 0xe8, 0x1d, 0x66, 0x3a, 0x56, 0xfc, 0x6b, 0x90, 0xd2, 0xe2,
	0xd1, 0xdc, 0xf5, 0x16, 0xfe, 0x17, 0xfe, 0xf9, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x27, 0x04,
	0xad, 0x78, 0x4d, 0x1f, 0x00, 0x00,
}
