// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requirement.proto

/*
Package requirement is a generated protocol buffer package.

It is generated from these files:
	requirement.proto

It has these top-level messages:
	PublishRequest
	PublishResponse
	QueryRequest
	QueryResponse
	QueryData
	QueryRow
*/
package requirement

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishRequest struct {
	Version     uint32 `protobuf:"varint,1,opt,name=version" json:"version"`
	CursorNum   uint32 `protobuf:"varint,2,opt,name=cursor_num,json=cursorNum" json:"cursor_num"`
	CursorLabel uint32 `protobuf:"varint,3,opt,name=cursor_label,json=cursorLabel" json:"cursor_label"`
	Lifetime    uint64 `protobuf:"varint,4,opt,name=lifetime" json:"lifetime"`
	Sender      string `protobuf:"bytes,5,opt,name=sender" json:"sender"`
	Contract    string `protobuf:"bytes,6,opt,name=contract" json:"contract"`
	Method      string `protobuf:"bytes,7,opt,name=method" json:"method"`
	Param       string `protobuf:"bytes,8,opt,name=param" json:"param"`
	SigAlg      uint32 `protobuf:"varint,9,opt,name=sig_alg,json=sigAlg" json:"sig_alg"`
	Signature   string `protobuf:"bytes,10,opt,name=signature" json:"signature"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PublishRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PublishRequest) GetCursorNum() uint32 {
	if m != nil {
		return m.CursorNum
	}
	return 0
}

func (m *PublishRequest) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *PublishRequest) GetLifetime() uint64 {
	if m != nil {
		return m.Lifetime
	}
	return 0
}

func (m *PublishRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PublishRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *PublishRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *PublishRequest) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *PublishRequest) GetSigAlg() uint32 {
	if m != nil {
		return m.SigAlg
	}
	return 0
}

func (m *PublishRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type PublishResponse struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublishResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PublishResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *PublishResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryRequest struct {
	PageSize   int32  `protobuf:"varint,1,opt,name=pageSize" json:"pageSize"`
	PageNum    int32  `protobuf:"varint,2,opt,name=pageNum" json:"pageNum"`
	Username   string `protobuf:"bytes,3,opt,name=username" json:"username"`
	FeatureTag uint64 `protobuf:"varint,4,opt,name=feature_tag,json=featureTag" json:"feature_tag"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryRequest) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

type QueryResponse struct {
	Code int32      `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string     `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResponse) GetData() *QueryData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryData struct {
	PageNum  uint64      `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	RowCount uint64      `protobuf:"varint,2,opt,name=rowCount" json:"rowCount"`
	Row      []*QueryRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryData) Reset()                    { *m = QueryData{} }
func (m *QueryData) String() string            { return proto.CompactTextString(m) }
func (*QueryData) ProtoMessage()               {}
func (*QueryData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryData) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryData) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryData) GetRow() []*QueryRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type QueryRow struct {
	RequirementId   string `protobuf:"bytes,1,opt,name=requirement_id,json=requirementId" json:"requirement_id"`
	Username        string `protobuf:"bytes,2,opt,name=username" json:"username"`
	RequirementName string `protobuf:"bytes,3,opt,name=requirement_name,json=requirementName" json:"requirement_name"`
	FeatureTag      uint64 `protobuf:"varint,4,opt,name=feature_tag,json=featureTag" json:"feature_tag"`
	SamplePath      string `protobuf:"bytes,5,opt,name=sample_path,json=samplePath" json:"sample_path"`
	SampleHash      string `protobuf:"bytes,6,opt,name=sample_hash,json=sampleHash" json:"sample_hash"`
	ExpireTime      uint32 `protobuf:"varint,7,opt,name=expire_time,json=expireTime" json:"expire_time"`
	Price           uint64 `protobuf:"varint,8,opt,name=price" json:"price"`
	Description     string `protobuf:"bytes,9,opt,name=description" json:"description"`
	PublishDate     uint32 `protobuf:"varint,10,opt,name=publish_date,json=publishDate" json:"publish_date"`
}

func (m *QueryRow) Reset()                    { *m = QueryRow{} }
func (m *QueryRow) String() string            { return proto.CompactTextString(m) }
func (*QueryRow) ProtoMessage()               {}
func (*QueryRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryRow) GetRequirementId() string {
	if m != nil {
		return m.RequirementId
	}
	return ""
}

func (m *QueryRow) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryRow) GetRequirementName() string {
	if m != nil {
		return m.RequirementName
	}
	return ""
}

func (m *QueryRow) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

func (m *QueryRow) GetSamplePath() string {
	if m != nil {
		return m.SamplePath
	}
	return ""
}

func (m *QueryRow) GetSampleHash() string {
	if m != nil {
		return m.SampleHash
	}
	return ""
}

func (m *QueryRow) GetExpireTime() uint32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *QueryRow) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *QueryRow) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *QueryRow) GetPublishDate() uint32 {
	if m != nil {
		return m.PublishDate
	}
	return 0
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "PublishResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
	proto.RegisterType((*QueryData)(nil), "QueryData")
	proto.RegisterType((*QueryRow)(nil), "QueryRow")
}

func init() { proto.RegisterFile("requirement.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xee, 0xfe, 0x6f, 0x26, 0xdd, 0xb6, 0x58, 0x08, 0xac, 0xe5, 0x6f, 0x89, 0x84, 0xb4, 0x5c,
	0x72, 0x28, 0x4f, 0x80, 0xe8, 0x01, 0x04, 0xaa, 0x8a, 0x29, 0x57, 0x22, 0x37, 0x99, 0x26, 0x96,
	0x92, 0x38, 0xb5, 0x1d, 0x0a, 0xdc, 0x78, 0x14, 0x9e, 0x8a, 0xd7, 0x41, 0x76, 0xbc, 0x69, 0x5a,
	0x09, 0xc4, 0xcd, 0xdf, 0xe7, 0x99, 0xf1, 0xcc, 0x97, 0x6f, 0x02, 0xf7, 0x14, 0x5e, 0xb5, 0x42,
	0x61, 0x85, 0xb5, 0x89, 0x1b, 0x25, 0x8d, 0x8c, 0x7e, 0x8d, 0xe1, 0xe0, 0xac, 0xbd, 0x28, 0x85,
	0x2e, 0x18, 0x5e, 0xb5, 0xa8, 0x0d, 0xa1, 0xb0, 0xf8, 0x8a, 0x4a, 0x0b, 0x59, 0xd3, 0xd1, 0x66,
	0xb4, 0x5d, 0xb1, 0x1d, 0x24, 0x4f, 0x00, 0xd2, 0x56, 0x69, 0xa9, 0x92, 0xba, 0xad, 0xe8, 0xd8,
	0x5d, 0x06, 0x1d, 0x73, 0xda, 0x56, 0xe4, 0x39, 0xec, 0xfb, 0xeb, 0x92, 0x5f, 0x60, 0x49, 0x27,
	0x2e, 0x20, 0xec, 0xb8, 0x0f, 0x96, 0x22, 0x6b, 0x58, 0x96, 0xe2, 0x12, 0x8d, 0xa8, 0x90, 0x4e,
	0x37, 0xa3, 0xed, 0x94, 0xf5, 0x98, 0x3c, 0x80, 0xb9, 0xc6, 0x3a, 0x43, 0x45, 0x67, 0x9b, 0xd1,
	0x36, 0x60, 0x1e, 0xd9, 0x9c, 0x54, 0xd6, 0x46, 0xf1, 0xd4, 0xd0, 0xb9, 0xbb, 0xe9, 0xb1, 0xcd,
	0xa9, 0xd0, 0x14, 0x32, 0xa3, 0x8b, 0x2e, 0xa7, 0x43, 0xe4, 0x3e, 0xcc, 0x1a, 0xae, 0x78, 0x45,
	0x97, 0x8e, 0xee, 0x00, 0x79, 0x08, 0x0b, 0x2d, 0xf2, 0x84, 0x97, 0x39, 0x0d, 0x5c, 0x6f, 0x73,
	0x2d, 0xf2, 0xd7, 0x65, 0x4e, 0x1e, 0x43, 0xa0, 0x45, 0x5e, 0x73, 0xd3, 0x2a, 0xa4, 0xe0, 0x52,
	0x6e, 0x88, 0xe8, 0x3d, 0x1c, 0xf6, 0x12, 0xe9, 0x46, 0xd6, 0x1a, 0x09, 0x81, 0x69, 0x2a, 0x33,
	0x74, 0x02, 0xcd, 0x98, 0x3b, 0x5b, 0x2e, 0xe3, 0x86, 0x3b, 0x5d, 0x02, 0xe6, 0xce, 0xe4, 0x08,
	0x26, 0x95, 0xce, 0x9d, 0x12, 0x01, 0xb3, 0xc7, 0xe8, 0xe7, 0x08, 0xf6, 0x3f, 0xb6, 0xa8, 0xbe,
	0xef, 0xe4, 0x5e, 0xc3, 0xb2, 0xe1, 0x39, 0x7e, 0x12, 0x3f, 0x76, 0xe5, 0x7a, 0x6c, 0x3f, 0x85,
	0x3d, 0x9f, 0x7a, 0xb5, 0x67, 0x6c, 0x07, 0x6d, 0x56, 0xab, 0x51, 0xd5, 0xbc, 0x42, 0x5f, 0xbd,
	0xc7, 0xe4, 0x19, 0x84, 0x97, 0xe8, 0x5a, 0x4f, 0x0c, 0xcf, 0xbd, 0xce, 0xe0, 0xa9, 0x73, 0x9e,
	0x47, 0x9f, 0x61, 0xe5, 0x5b, 0xf8, 0xc7, 0x38, 0x4f, 0x07, 0xe3, 0x84, 0xc7, 0x10, 0xbb, 0x8c,
	0x13, 0x6e, 0xf8, 0x5f, 0x47, 0xfb, 0x02, 0x41, 0x1f, 0x34, 0x6c, 0x7d, 0xe4, 0x1a, 0x18, 0xb6,
	0xae, 0xe4, 0xf5, 0x1b, 0xd9, 0xd6, 0xc6, 0x15, 0x9f, 0xb2, 0x1e, 0x93, 0x47, 0x30, 0x51, 0xf2,
	0x9a, 0x4e, 0x36, 0x93, 0x6d, 0x78, 0x1c, 0x74, 0x6f, 0x32, 0x79, 0xcd, 0x2c, 0x1b, 0xfd, 0x1e,
	0xc3, 0x72, 0xc7, 0x90, 0x17, 0x70, 0x30, 0x70, 0x73, 0x22, 0x32, 0xf7, 0x4c, 0xc0, 0x56, 0x03,
	0xf6, 0x5d, 0x76, 0x4b, 0xa7, 0xf1, 0x1d, 0x9d, 0x5e, 0xc2, 0xd1, 0xb0, 0xc4, 0x40, 0xcb, 0xc3,
	0x01, 0x7f, 0xfa, 0x3f, 0x92, 0xda, 0x00, 0xcd, 0xab, 0xa6, 0xc4, 0xa4, 0xe1, 0xa6, 0xf0, 0x0e,
	0x86, 0x8e, 0x3a, 0xe3, 0xa6, 0x18, 0x04, 0x14, 0x5c, 0x17, 0xde, 0xc8, 0x3e, 0xe0, 0x2d, 0xd7,
	0x2e, 0x00, 0xbf, 0x35, 0xc2, 0xbe, 0x60, 0xb7, 0x63, 0xe1, 0x0c, 0x0a, 0x1d, 0x75, 0x6e, 0xf7,
	0xc3, 0x7a, 0x5a, 0x89, 0x14, 0x9d, 0xa7, 0xa7, 0xac, 0x03, 0x64, 0x03, 0x61, 0x86, 0x3a, 0x55,
	0xa2, 0x31, 0x76, 0x63, 0x03, 0x57, 0x77, 0x48, 0xd9, 0xb5, 0x6c, 0x3a, 0xfb, 0x26, 0x19, 0x37,
	0x9d, 0xbf, 0x57, 0x2c, 0xf4, 0xdc, 0x09, 0x37, 0x78, 0x9c, 0x43, 0xc8, 0x6e, 0x26, 0x26, 0x31,
	0x2c, 0xbc, 0xe1, 0xc9, 0x61, 0x7c, 0xfb, 0xef, 0xb0, 0x3e, 0x8a, 0xef, 0xec, 0x42, 0xb4, 0x47,
	0xb6, 0x30, 0x73, 0xdf, 0x85, 0xac, 0xe2, 0xa1, 0xb5, 0xd7, 0x07, 0xf1, 0x2d, 0x9b, 0x45, 0x7b,
	0x17, 0x73, 0xf7, 0xd7, 0x79, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x34, 0x6f, 0x61, 0x70, 0x8a,
	0x04, 0x00, 0x00,
}
