// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requirement.proto

/*
Package requirement is a generated protocol buffer package.

It is generated from these files:
	requirement.proto

It has these top-level messages:
	PublishRequest
	PublishResponse
	QueryRequest
	QueryResponse
	QueryData
	RequirementData
*/
package requirement

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishRequest struct {
	Version     uint32 `protobuf:"varint,1,opt,name=version" json:"version"`
	CursorNum   uint32 `protobuf:"varint,2,opt,name=cursor_num,json=cursorNum" json:"cursor_num"`
	CursorLabel uint32 `protobuf:"varint,3,opt,name=cursor_label,json=cursorLabel" json:"cursor_label"`
	Lifetime    uint64 `protobuf:"varint,4,opt,name=lifetime" json:"lifetime"`
	Sender      string `protobuf:"bytes,5,opt,name=sender" json:"sender"`
	Contract    string `protobuf:"bytes,6,opt,name=contract" json:"contract"`
	Method      string `protobuf:"bytes,7,opt,name=method" json:"method"`
	Param       string `protobuf:"bytes,8,opt,name=param" json:"param"`
	SigAlg      uint32 `protobuf:"varint,9,opt,name=sig_alg,json=sigAlg" json:"sig_alg"`
	Signature   string `protobuf:"bytes,10,opt,name=signature" json:"signature"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PublishRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PublishRequest) GetCursorNum() uint32 {
	if m != nil {
		return m.CursorNum
	}
	return 0
}

func (m *PublishRequest) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *PublishRequest) GetLifetime() uint64 {
	if m != nil {
		return m.Lifetime
	}
	return 0
}

func (m *PublishRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PublishRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *PublishRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *PublishRequest) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *PublishRequest) GetSigAlg() uint32 {
	if m != nil {
		return m.SigAlg
	}
	return 0
}

func (m *PublishRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type PublishResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublishResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PublishResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *PublishResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryRequest struct {
	PageSize  uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size"`
	PageNum   uint32 `protobuf:"varint,2,opt,name=page_num,json=pageNum" json:"page_num"`
	ReqId     string `protobuf:"bytes,3,opt,name=req_id,json=reqId" json:"req_id"`
	ReqType   string `protobuf:"bytes,4,opt,name=req_type,json=reqType" json:"req_type"`
	Username  string `protobuf:"bytes,5,opt,name=username" json:"username"`
	Random    string `protobuf:"bytes,6,opt,name=random" json:"random"`
	Signature string `protobuf:"bytes,7,opt,name=signature" json:"signature"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryRequest) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryRequest) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *QueryRequest) GetReqType() string {
	if m != nil {
		return m.ReqType
	}
	return ""
}

func (m *QueryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryRequest) GetRandom() string {
	if m != nil {
		return m.Random
	}
	return ""
}

func (m *QueryRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type QueryResponse struct {
	Code int32      `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string     `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResponse) GetData() *QueryData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryData struct {
	PageNum  uint32             `protobuf:"varint,1,opt,name=page_num,json=pageNum" json:"page_num"`
	RowCount uint32             `protobuf:"varint,2,opt,name=row_count,json=rowCount" json:"row_count"`
	Row      []*RequirementData `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryData) Reset()                    { *m = QueryData{} }
func (m *QueryData) String() string            { return proto.CompactTextString(m) }
func (*QueryData) ProtoMessage()               {}
func (*QueryData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryData) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryData) GetRowCount() uint32 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryData) GetRow() []*RequirementData {
	if m != nil {
		return m.Row
	}
	return nil
}

type RequirementData struct {
	Username        string `protobuf:"bytes,1,opt,name=username" json:"username"`
	RequirementId   string `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId" json:"requirement_id"`
	RequirementName string `protobuf:"bytes,3,opt,name=requirement_name,json=requirementName" json:"requirement_name"`
	FeatureTag      uint64 `protobuf:"varint,4,opt,name=feature_tag,json=featureTag" json:"feature_tag"`
	SamplePath      string `protobuf:"bytes,5,opt,name=sample_path,json=samplePath" json:"sample_path"`
	SampleHash      string `protobuf:"bytes,6,opt,name=sample_hash,json=sampleHash" json:"sample_hash"`
	ExpireTime      uint64 `protobuf:"varint,7,opt,name=expire_time,json=expireTime" json:"expire_time"`
	Price           uint64 `protobuf:"varint,8,opt,name=price" json:"price"`
	Description     string `protobuf:"bytes,9,opt,name=description" json:"description"`
	PublishDate     uint64 `protobuf:"varint,10,opt,name=publish_date,json=publishDate" json:"publish_date"`
}

func (m *RequirementData) Reset()                    { *m = RequirementData{} }
func (m *RequirementData) String() string            { return proto.CompactTextString(m) }
func (*RequirementData) ProtoMessage()               {}
func (*RequirementData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RequirementData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RequirementData) GetRequirementId() string {
	if m != nil {
		return m.RequirementId
	}
	return ""
}

func (m *RequirementData) GetRequirementName() string {
	if m != nil {
		return m.RequirementName
	}
	return ""
}

func (m *RequirementData) GetFeatureTag() uint64 {
	if m != nil {
		return m.FeatureTag
	}
	return 0
}

func (m *RequirementData) GetSamplePath() string {
	if m != nil {
		return m.SamplePath
	}
	return ""
}

func (m *RequirementData) GetSampleHash() string {
	if m != nil {
		return m.SampleHash
	}
	return ""
}

func (m *RequirementData) GetExpireTime() uint64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *RequirementData) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RequirementData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RequirementData) GetPublishDate() uint64 {
	if m != nil {
		return m.PublishDate
	}
	return 0
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "PublishResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
	proto.RegisterType((*QueryData)(nil), "QueryData")
	proto.RegisterType((*RequirementData)(nil), "RequirementData")
}

func init() { proto.RegisterFile("requirement.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x5b, 0x6e, 0xd4, 0x30,
	0x14, 0x86, 0x9b, 0xce, 0x25, 0x93, 0x93, 0x4e, 0x67, 0xb0, 0xb8, 0x84, 0x96, 0xcb, 0x10, 0x09,
	0x69, 0x78, 0xc9, 0x43, 0x59, 0x01, 0xa2, 0x0f, 0x54, 0xa0, 0xaa, 0x84, 0xf2, 0x1c, 0xb9, 0xc9,
	0x69, 0xc6, 0x52, 0x12, 0x67, 0x6c, 0x87, 0xd2, 0xee, 0x86, 0xed, 0xb0, 0x08, 0xd6, 0x82, 0x7c,
	0xe9, 0x34, 0x33, 0x82, 0x37, 0xff, 0xbf, 0xcf, 0xb1, 0x93, 0xcf, 0xfe, 0x0d, 0x8f, 0x04, 0xae,
	0x3b, 0x26, 0xb0, 0xc6, 0x46, 0x25, 0xad, 0xe0, 0x8a, 0xc7, 0xbf, 0xf6, 0xe1, 0xf0, 0xa2, 0xbb,
	0xaa, 0x98, 0x5c, 0xa5, 0xb8, 0xee, 0x50, 0x2a, 0x12, 0x81, 0xff, 0x03, 0x85, 0x64, 0xbc, 0x89,
	0xbc, 0x85, 0xb7, 0x9c, 0xa6, 0xf7, 0x92, 0xbc, 0x04, 0xc8, 0x3b, 0x21, 0xb9, 0xc8, 0x9a, 0xae,
	0x8e, 0xf6, 0xcd, 0x64, 0x60, 0x9d, 0xf3, 0xae, 0x26, 0x6f, 0xe0, 0xc0, 0x4d, 0x57, 0xf4, 0x0a,
	0xab, 0x68, 0x60, 0x0a, 0x42, 0xeb, 0x7d, 0xd1, 0x16, 0x39, 0x82, 0x49, 0xc5, 0xae, 0x51, 0xb1,
	0x1a, 0xa3, 0xe1, 0xc2, 0x5b, 0x0e, 0xd3, 0x8d, 0x26, 0x4f, 0x61, 0x2c, 0xb1, 0x29, 0x50, 0x44,
	0xa3, 0x85, 0xb7, 0x0c, 0x52, 0xa7, 0x74, 0x4f, 0xce, 0x1b, 0x25, 0x68, 0xae, 0xa2, 0xb1, 0x99,
	0xd9, 0x68, 0xdd, 0x53, 0xa3, 0x5a, 0xf1, 0x22, 0xf2, 0x6d, 0x8f, 0x55, 0xe4, 0x31, 0x8c, 0x5a,
	0x2a, 0x68, 0x1d, 0x4d, 0x8c, 0x6d, 0x05, 0x79, 0x06, 0xbe, 0x64, 0x65, 0x46, 0xab, 0x32, 0x0a,
	0xcc, 0xb7, 0x8d, 0x25, 0x2b, 0x3f, 0x54, 0x25, 0x79, 0x01, 0x81, 0x64, 0x65, 0x43, 0x55, 0x27,
	0x30, 0x02, 0xd3, 0xf2, 0x60, 0xc4, 0x9f, 0x61, 0xb6, 0x41, 0x24, 0x5b, 0xde, 0x48, 0x24, 0x04,
	0x86, 0x39, 0x2f, 0xd0, 0x01, 0x32, 0x63, 0xed, 0x15, 0x54, 0x51, 0xc3, 0x25, 0x48, 0xcd, 0x98,
	0xcc, 0x61, 0x50, 0xcb, 0xd2, 0x90, 0x08, 0x52, 0x3d, 0x8c, 0x7f, 0x7b, 0x70, 0xf0, 0xb5, 0x43,
	0x71, 0x7b, 0x8f, 0xfb, 0x18, 0x82, 0x96, 0x96, 0x98, 0x49, 0x76, 0x77, 0xbf, 0xde, 0x44, 0x1b,
	0xdf, 0xd8, 0x1d, 0x92, 0xe7, 0x60, 0xc6, 0x3d, 0xde, 0xbe, 0xd6, 0x9a, 0xf6, 0x13, 0x18, 0x0b,
	0x5c, 0x67, 0xac, 0x70, 0xab, 0x8f, 0x04, 0xae, 0xcf, 0x0a, 0xdd, 0xa1, 0x6d, 0x75, 0xdb, 0x5a,
	0xc2, 0x41, 0xea, 0x0b, 0x5c, 0x5f, 0xde, 0xb6, 0xa8, 0x41, 0x76, 0x12, 0x45, 0x43, 0x6b, 0x74,
	0x88, 0x37, 0x5a, 0x83, 0x14, 0xb4, 0x29, 0x78, 0xed, 0x10, 0x3b, 0xb5, 0x4d, 0xc6, 0xdf, 0x25,
	0xf3, 0x1d, 0xa6, 0xee, 0x5f, 0xfe, 0xc1, 0x65, 0xe4, 0xb8, 0xbc, 0xea, 0x71, 0x09, 0x4f, 0x20,
	0x31, 0x1d, 0xa7, 0x54, 0xd1, 0xff, 0x32, 0x2a, 0x21, 0xd8, 0x14, 0x6d, 0x21, 0xf0, 0xb6, 0x11,
	0x1c, 0x43, 0x20, 0xf8, 0x4d, 0x96, 0xf3, 0xae, 0x51, 0x0e, 0xcf, 0x44, 0xf0, 0x9b, 0x8f, 0x5a,
	0x93, 0x18, 0x06, 0x82, 0xdf, 0x44, 0x83, 0xc5, 0x60, 0x19, 0x9e, 0xcc, 0x93, 0xf4, 0xe1, 0xea,
	0x9b, 0xbd, 0xf5, 0x64, 0xfc, 0x67, 0x1f, 0x66, 0x3b, 0x13, 0x5b, 0x94, 0xbc, 0x1d, 0x4a, 0x6f,
	0xe1, 0xb0, 0x17, 0x21, 0xcd, 0xde, 0x1e, 0xf6, 0xb4, 0xe7, 0x9e, 0x15, 0xe4, 0x1d, 0xcc, 0xfb,
	0x65, 0x66, 0x29, 0xfb, 0x7b, 0xb3, 0x9e, 0x7f, 0xae, 0x57, 0x7c, 0x0d, 0xe1, 0x35, 0x1a, 0x98,
	0x99, 0xa2, 0xa5, 0xcb, 0x04, 0x38, 0xeb, 0x92, 0x96, 0xba, 0x40, 0xd2, 0xba, 0xad, 0x30, 0x6b,
	0xa9, 0x5a, 0xb9, 0x73, 0x03, 0x6b, 0x5d, 0x50, 0xb5, 0xea, 0x15, 0xac, 0xa8, 0x5c, 0xb9, 0xe3,
	0x73, 0x05, 0x9f, 0xa8, 0x34, 0x05, 0xf8, 0xb3, 0x65, 0x7a, 0x07, 0x1d, 0x3b, 0xdf, 0x6e, 0x61,
	0xad, 0x4b, 0x1d, 0x3c, 0x1d, 0x16, 0xc1, 0x72, 0x34, 0x61, 0x19, 0xa6, 0x56, 0x90, 0x05, 0x84,
	0x05, 0xca, 0x5c, 0xb0, 0x56, 0xe9, 0xa7, 0x20, 0x30, 0xeb, 0xf6, 0x2d, 0x9d, 0xf7, 0xd6, 0xe6,
	0x22, 0x2b, 0xa8, 0xb2, 0xc1, 0x19, 0xa6, 0xa1, 0xf3, 0x4e, 0xa9, 0xc2, 0x93, 0x12, 0xc2, 0x1e,
	0x5f, 0x92, 0x80, 0xef, 0x92, 0x44, 0x66, 0xc9, 0xf6, 0xb3, 0x73, 0x34, 0x4f, 0x76, 0x42, 0x16,
	0xef, 0x91, 0x25, 0x8c, 0xcc, 0x45, 0x20, 0xd3, 0xa4, 0x9f, 0x99, 0xa3, 0xc3, 0x64, 0xeb, 0xda,
	0xc5, 0x7b, 0x57, 0x63, 0xf3, 0x9c, 0xbd, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x65, 0x4b, 0x09,
	0x61, 0xe3, 0x04, 0x00, 0x00,
}
