@startuml


       |Client|
       start
       :企业或组织用户;
       :查看需求对应提交数据;
       |#AntiqueWhite|backend service|


        if (是否需要审核数据) then (yes)

          :审核者进行数据审核和清洗;
        else

          :转交需求方;

         endif

        :数据验收;

          if (数据有效) then (yes)

                  :转发代币;

                  :获取数据;
                else

                  :拒绝交易;

                 endif


       |blockchain|
       :交易过程上链;

       stop
       @enduml