@startuml

package "App logic layer" {

[Http service]
[Identification Management]
[Transaction management]
[Storage Service]
[Arbition System]
[Contract Management]
[Blockchain client Adaptor]
[DB]
[Files system]
}

package "Blockchain layer" {

[P2P]
[Consensus]
[EVM]
[Transaction]
[Contract Adaptor]

[RPC Server]

[Blockchain client Adaptor]<-->[RPC server]

}

package "DAPP" {
 [connecttion service]
 [key management]
 [contract service]
 [Block Service]

  [connection service]<-->[RPC server]
  [connection service]<-->[Http service]

}

@enduml