@startuml

===提交数据招募或清洗需求==
DataRecuritor --> DataRecuritDeal: post数据需求 Request


DataRecuritDeal --> ContractManagement: 生成智能合约

DataRecuritDeal<--ContractManagement:返回智能合约

DataRecuritor<--DataRecuritDeal:返回智能合约

DataRecuritor-->ContractManagement:命名或部署合约

@enduml