@startumlleft to right direction:DataProvider::DataRecruits::system:rectangle bottos {(contract-deploy)(contract-query)(contract-audit)(contract-model-creation)(contract-model-query)}(DataRecruits)-->(contract-deploy)(DataProvider)-->(contract-deploy)(DataProvider)-->(contract-query)(DataRecruits)-->(contract-query)(system)-->(contract-audit)(system)-->(contract-model-creation)(system)-->(contract-model-query)@enduml