@startuml
left to right direction

:DataProvider:

:DataRecruitor:

rectangle bottos {

(dataTransaction 查询)

(dataTransaction 申诉)


(dataTransaction)

(TokenTransfer)

(dataTransaction) <.>(TokenTransfer)


}


(DataProvider)-->(dataTransaction 查询)
(DataRecruitor)-->(dataTransaction 查询)
(DataProvider)-->(dataTransaction 申诉)
(DataProvider)-->(dataTransaction)
(DataRecruitor)-->(dataTransaction)

(DataProvider)-->(TokenTransfer)
(DataRecruitor)-->(TokenTransfer)

(TokenTransfer)<--"gas consumption"(node)
(TokenTransfer)<--(Auditor)




@enduml




