@startuml


       |Client|
       start
       :提交数据需求;
       |#AntiqueWhite|backend service|
       :验证用户;
       :提交数据需求;
       :招募审核者;
       :部署数据需求合约;
       |blockchain|
       :数据需求上链;

       stop
       @enduml