@startuml

abstract class  Node

class FullNode
class WorkNode
class ListenNode

class ArbitaryNode
class AuditNode
class OracleNode


Node <|--WorkNode
Node <|-- ListenNode

WorkNode <|--FullNode

WorkNode <|--ArbitaryNode
WorkNode <|-- AuditNode
WorkNode <|-- TradeNode
WorkNode <|-- OracleNode

@enduml