@startuml
actor DataRecruitor

actor DataMarker

actor DataProvider

box "client" #LightBlue
	participant DataRecruitor
	participant DataMarker
	participant DataProvider
end box



box "Transaction Service" #LightGreen
	participant TransactionManagement
	participant DataAsset
	participant DataExchangeDeal
end box

==数据采集的交易==

DataRecruitor-->TransactionManagement:发起数据交易

create DataExchangeDeal
TransactionManagement-->DataExchangeDeal:创建实例

DataExchangeDeal--->Blockchain:call exchange 合约

Blockchain-->Blockchain:call 数据募集合约、交易合约、资产合约、转账合约

Blockchain-->DataExchangeDeal:返回交易结果

DataExchangeDeal-->DataRecruitor:返回交易结果

DataRecruitor<------->:获取数据资产过程


==数据清洗标注交易?==

DataMarker-->TransactionManagement:接收数据清洗需求

TransactionManagement-->DataExchangeDeal:数据清洗交易

DataExchangeDeal--->Blockchain:call 数据清洗交易start

Blockchain--->Blockchain:call 数据清洗交易、DataAsset

Blockchain-->DataExchangeDeal: 返回数据相关信息以及清洗数据提交要求
DataExchangeDeal--->DataMarker:返回数据相关信息

DataMarker<---->:获取数据

DataMarker<---->:提交清洗数据

DataMarker----->TransactionManagement:数据清洗结果发送


TransactionManagement-->DataExchangeDeal:创建实例


DataExchangeDeal--->Blockchain: 调用数据清洗交易合约（已提交数据）

Blockchain---->DataExchangeDeal:返回结果

DataExchangeDeal---->DataMarker:返回结果，待数据招募者确认

DataRecruitor--->DataExchangeDeal:,获取数据

DataExchangeDeal--->Blockchain:,获取数据

Blockchain-->DataExchangeDeal:返回清洗数据信息

DataExchangeDeal---->DataRecruitor:返回清洗数据信息

DataRecruitor<---->:获取数据

DataRecruitor----->DataExchangeDeal:确认交易完成

DataExchangeDeal--->Blockchain:call 交易合约、代币转让合约

Blockchain---->DataExchangeDeal:交易完成

DataExchangeDeal---->DataRecruitor:交易完成








@enduml