@startuml
left to right direction
:DataProvider:
:DataRecruitor:
:system:
:Auditor:


rectangle bottos {

(data)

(Requirements)

(DataMatch)

}

note "查询" as N1
(DataProvider) .. N1
N1 --> (Requirements)

note "提交" as N2
(DataProvider) .. N2
N2 --> (data)

note "查询" as N3
(DataProvider) .. N3
N3 --> (data)

note "查询" as N4
(DataRecruitor) .. N4
N4 --> (Requirements)

note "提交" as N5
(DataRecruitor) .. N5
N5 --> (Requirements)

note "查询" as N6
(DataRecruitor) .. N6
N6 --> (data)

(data)<----"存储"(system)


(Requirements)<--"发布"(system)


(DataMatch)<---"提供匹配"(system)

(data)<---"审核"(Auditor)


@enduml




