@startuml
left to right direction
:users:


rectangle bottos {
    users-->(查询 block信息)
    users-->(查询任意交易)
    users-->(统计交易情况)
    users-->(统计合约情况)
    users-->(查询合约情况)
    users-->(查询其他用户信息)

}


@enduml