// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

/*
Package exchange is a generated protocol buffer package.

It is generated from these files:
	exchange.proto

It has these top-level messages:
	ConsumerBuyRequest
	ConsumerBuyResponse
	QueryTxRequest
	QueryTxResponse
	QueryTxData
	TxRow
	TransferRequest
	TransferResponse
	QueryTransferRequest
	QueryTransferResponse
*/
package exchange

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsumerBuyRequest struct {
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *ConsumerBuyRequest) Reset()                    { *m = ConsumerBuyRequest{} }
func (m *ConsumerBuyRequest) String() string            { return proto.CompactTextString(m) }
func (*ConsumerBuyRequest) ProtoMessage()               {}
func (*ConsumerBuyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConsumerBuyRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type ConsumerBuyResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *ConsumerBuyResponse) Reset()                    { *m = ConsumerBuyResponse{} }
func (m *ConsumerBuyResponse) String() string            { return proto.CompactTextString(m) }
func (*ConsumerBuyResponse) ProtoMessage()               {}
func (*ConsumerBuyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConsumerBuyResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ConsumerBuyResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ConsumerBuyResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryTxRequest struct {
	PageSize uint64 `protobuf:"varint,1,opt,name=pageSize" json:"pageSize"`
	PageNum  uint64 `protobuf:"varint,2,opt,name=pageNum" json:"pageNum"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username"`
}

func (m *QueryTxRequest) Reset()                    { *m = QueryTxRequest{} }
func (m *QueryTxRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryTxRequest) ProtoMessage()               {}
func (*QueryTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryTxRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryTxRequest) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryTxRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type QueryTxResponse struct {
	Code uint32       `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryTxData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string       `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryTxResponse) Reset()                    { *m = QueryTxResponse{} }
func (m *QueryTxResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryTxResponse) ProtoMessage()               {}
func (*QueryTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryTxResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryTxResponse) GetData() *QueryTxData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryTxResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryTxData struct {
	PageNum  uint64   `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	RowCount uint64   `protobuf:"varint,2,opt,name=rowCount" json:"rowCount"`
	Row      []*TxRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryTxData) Reset()                    { *m = QueryTxData{} }
func (m *QueryTxData) String() string            { return proto.CompactTextString(m) }
func (*QueryTxData) ProtoMessage()               {}
func (*QueryTxData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryTxData) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryTxData) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryTxData) GetRow() []*TxRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type TxRow struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id"`
	From          string `protobuf:"bytes,2,opt,name=from" json:"from"`
	To            string `protobuf:"bytes,3,opt,name=to" json:"to"`
	Price         uint64 `protobuf:"varint,4,opt,name=price" json:"price"`
	Type          uint64 `protobuf:"varint,5,opt,name=type" json:"type"`
	Date          string `protobuf:"bytes,6,opt,name=date" json:"date"`
	BlockId       uint64 `protobuf:"varint,7,opt,name=block_id,json=blockId" json:"block_id"`
}

func (m *TxRow) Reset()                    { *m = TxRow{} }
func (m *TxRow) String() string            { return proto.CompactTextString(m) }
func (*TxRow) ProtoMessage()               {}
func (*TxRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TxRow) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TxRow) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TxRow) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TxRow) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TxRow) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TxRow) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TxRow) GetBlockId() uint64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

type TransferRequest struct {
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *TransferRequest) Reset()                    { *m = TransferRequest{} }
func (m *TransferRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()               {}
func (*TransferRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TransferRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type TransferResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *TransferResponse) Reset()                    { *m = TransferResponse{} }
func (m *TransferResponse) String() string            { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()               {}
func (*TransferResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TransferResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TransferResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TransferResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryTransferRequest struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id"`
	Random    string `protobuf:"bytes,3,opt,name=random" json:"random"`
	Signature string `protobuf:"bytes,4,opt,name=signature" json:"signature"`
}

func (m *QueryTransferRequest) Reset()                    { *m = QueryTransferRequest{} }
func (m *QueryTransferRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryTransferRequest) ProtoMessage()               {}
func (*QueryTransferRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *QueryTransferRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryTransferRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *QueryTransferRequest) GetRandom() string {
	if m != nil {
		return m.Random
	}
	return ""
}

func (m *QueryTransferRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type QueryTransferResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryTransferResponse) Reset()                    { *m = QueryTransferResponse{} }
func (m *QueryTransferResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryTransferResponse) ProtoMessage()               {}
func (*QueryTransferResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryTransferResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryTransferResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *QueryTransferResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ConsumerBuyRequest)(nil), "ConsumerBuyRequest")
	proto.RegisterType((*ConsumerBuyResponse)(nil), "ConsumerBuyResponse")
	proto.RegisterType((*QueryTxRequest)(nil), "QueryTxRequest")
	proto.RegisterType((*QueryTxResponse)(nil), "QueryTxResponse")
	proto.RegisterType((*QueryTxData)(nil), "QueryTxData")
	proto.RegisterType((*TxRow)(nil), "TxRow")
	proto.RegisterType((*TransferRequest)(nil), "TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "TransferResponse")
	proto.RegisterType((*QueryTransferRequest)(nil), "QueryTransferRequest")
	proto.RegisterType((*QueryTransferResponse)(nil), "QueryTransferResponse")
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0x6c, 0xfa, 0x39, 0x65, 0xdb, 0x6a, 0xb6, 0x20, 0x53, 0x81, 0x54, 0x59, 0x42, 0xda,
	0x0b, 0x11, 0x2a, 0x37, 0x8e, 0xbb, 0x70, 0xa8, 0x84, 0x40, 0x1b, 0x7a, 0xe1, 0x80, 0x90, 0x9b,
	0x78, 0x4b, 0x04, 0xb1, 0x83, 0xed, 0xd0, 0x96, 0x3f, 0xc0, 0x8f, 0xe1, 0x4f, 0x22, 0x3b, 0x6e,
	0x48, 0xb7, 0x80, 0x90, 0xf6, 0x36, 0xef, 0xc9, 0x33, 0xf3, 0xec, 0x99, 0x67, 0x18, 0xf2, 0x6d,
	0xf2, 0x89, 0x89, 0x35, 0x8f, 0x0a, 0x25, 0x8d, 0xa4, 0xcf, 0x00, 0xaf, 0xa4, 0xd0, 0x65, 0xce,
	0xd5, 0x65, 0xb9, 0x8b, 0xf9, 0xd7, 0x92, 0x6b, 0x83, 0x53, 0xe8, 0x15, 0x52, 0x9b, 0x4b, 0x99,
	0xee, 0x48, 0x30, 0x0b, 0x2e, 0xfa, 0x71, 0x8d, 0xe9, 0x5b, 0x38, 0x3f, 0xc8, 0xd0, 0x85, 0x14,
	0x9a, 0x23, 0x42, 0x2b, 0x91, 0x29, 0x77, 0xc7, 0xcf, 0x62, 0x17, 0x5b, 0x2e, 0x65, 0x86, 0x91,
	0x53, 0x57, 0xc2, 0xc5, 0x38, 0x86, 0x30, 0xd7, 0x6b, 0x12, 0x3a, 0xca, 0x86, 0x74, 0x05, 0xc3,
	0xeb, 0x92, 0xab, 0xdd, 0x72, 0xdb, 0x6c, 0xcf, 0xd6, 0xfc, 0x5d, 0xf6, 0xbd, 0xaa, 0xd7, 0x8a,
	0x6b, 0x8c, 0x04, 0xba, 0x36, 0x7e, 0x53, 0xe6, 0xae, 0x6c, 0x2b, 0xde, 0x43, 0x9b, 0x55, 0x6a,
	0xae, 0x04, 0xcb, 0xb9, 0x2f, 0x5f, 0x63, 0xfa, 0x1e, 0x46, 0x75, 0x8f, 0x7f, 0x08, 0x9e, 0x35,
	0x04, 0x0f, 0xe6, 0xf7, 0x22, 0x9f, 0xf3, 0x92, 0x19, 0xf6, 0x57, 0xf9, 0x1f, 0x60, 0xd0, 0x38,
	0xd6, 0xd4, 0x17, 0x1c, 0xe9, 0x53, 0x72, 0x73, 0x25, 0x4b, 0x61, 0xbc, 0xf4, 0x1a, 0x23, 0x81,
	0x50, 0xc9, 0x0d, 0x09, 0x67, 0xe1, 0xc5, 0x60, 0xde, 0x89, 0x96, 0xdb, 0x58, 0x6e, 0x62, 0x4b,
	0xd1, 0x9f, 0x01, 0xb4, 0x1d, 0xc4, 0x27, 0x30, 0x34, 0x8a, 0x09, 0xcd, 0x12, 0x93, 0x49, 0xf1,
	0x31, 0x4b, 0xfd, 0x68, 0xce, 0x1a, 0xec, 0x22, 0xb5, 0xf7, 0xba, 0x51, 0x32, 0xdf, 0x3f, 0xba,
	0x8d, 0x71, 0x08, 0xa7, 0x46, 0x7a, 0xd1, 0xa7, 0x46, 0xe2, 0x04, 0xda, 0x85, 0xca, 0x12, 0x4e,
	0x5a, 0x4e, 0x47, 0x05, 0x6c, 0xa6, 0xd9, 0x15, 0x9c, 0xb4, 0x1d, 0xe9, 0x62, 0x3f, 0x42, 0x4e,
	0x3a, 0xf5, 0x08, 0x39, 0x3e, 0x84, 0xde, 0xea, 0x8b, 0x4c, 0x3e, 0x5b, 0x09, 0xdd, 0xea, 0x8e,
	0x0e, 0x2f, 0x52, 0xfa, 0x14, 0x46, 0x4b, 0xab, 0xe6, 0x86, 0xab, 0xff, 0xd9, 0xa5, 0xd7, 0x30,
	0xfe, 0x7d, 0xfc, 0xce, 0x8b, 0xf4, 0x23, 0x80, 0x49, 0x35, 0x8a, 0x63, 0x09, 0xf5, 0x66, 0x04,
	0x87, 0x9b, 0x81, 0x8f, 0x01, 0x34, 0xd7, 0xda, 0xbf, 0x68, 0xd5, 0xa0, 0xef, 0x99, 0x45, 0x8a,
	0x0f, 0xa0, 0xa3, 0x98, 0x48, 0x65, 0xee, 0x1b, 0x79, 0x84, 0x8f, 0xa0, 0xaf, 0xb3, 0xb5, 0x60,
	0xa6, 0x54, 0xd5, 0x2b, 0xda, 0xac, 0x3d, 0x41, 0xaf, 0xe1, 0xfe, 0x2d, 0x21, 0x77, 0xbd, 0xdc,
	0xfc, 0x1b, 0xf4, 0x5e, 0x79, 0xeb, 0xe2, 0x0b, 0x18, 0x34, 0x2c, 0x88, 0xe7, 0xd1, 0xb1, 0x85,
	0xa7, 0x93, 0xe8, 0x0f, 0x2e, 0xa5, 0x27, 0x18, 0x41, 0xd7, 0xaf, 0x2b, 0x8e, 0xa2, 0x43, 0xdf,
	0x4d, 0xc7, 0xd1, 0x2d, 0x93, 0xd0, 0x93, 0x55, 0xc7, 0xfd, 0x13, 0xcf, 0x7f, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x78, 0xb0, 0xee, 0xed, 0x39, 0x04, 0x00, 0x00,
}
