// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bottos-project/magiccube/service/data/proto/data.proto

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	github.com/bottos-project/magiccube/service/data/proto/data.proto

It has these top-level messages:
	AllRequest
	Slice
	Url
	Node
	Ip
	Hash
	FileCheckRequest
	FileCheckResponse
	GetFileUploadURLRequest
	GetFileUploadURLResponse
	GetFileSliceUploadURLRequest
	GetFileSliceUploadURLResponse
	GetFileStorageNodeRequest
	GetFileStorageNodeResponse
	PutFileRequest
	PutFileResponse
	GetUploadProgressRequest
	GetUploadProgressResponse
	DownloadFileRequest
	DownloadFileResponse
	ComposeFileRequest
	ComposeFileResponse
	GetFileStorageURLRequest
	GetFileStorageURLResponse
	GetStorageIPRequest
	GetStorageIPResponse
	GetFileDownloadURLRequest
	GetFileDownloadURLResponse
*/

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllRequest struct {
}

func (m *AllRequest) Reset()                    { *m = AllRequest{} }
func (m *AllRequest) String() string            { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()               {}
func (*AllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Slice struct {
	Sguid string `protobuf:"bytes,1,opt,name=sguid" json:"sguid"`
}

func (m *Slice) Reset()                    { *m = Slice{} }
func (m *Slice) String() string            { return proto.CompactTextString(m) }
func (*Slice) ProtoMessage()               {}
func (*Slice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Slice) GetSguid() string {
	if m != nil {
		return m.Sguid
	}
	return ""
}

type Url struct {
	Sguid string `protobuf:"bytes,1,opt,name=sguid" json:"sguid"`
	Surl  string `protobuf:"bytes,2,opt,name=surl" json:"surl"`
}

func (m *Url) Reset()                    { *m = Url{} }
func (m *Url) String() string            { return proto.CompactTextString(m) }
func (*Url) ProtoMessage()               {}
func (*Url) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Url) GetSguid() string {
	if m != nil {
		return m.Sguid
	}
	return ""
}

func (m *Url) GetSurl() string {
	if m != nil {
		return m.Surl
	}
	return ""
}

type Node struct {
	NodeID      string `protobuf:"bytes,1,opt,name=nodeID" json:"nodeID"`
	NodeIP      string `protobuf:"bytes,2,opt,name=nodeIP" json:"nodeIP"`
	NodePort    string `protobuf:"bytes,3,opt,name=node_port,json=nodePort" json:"node_port"`
	NodeAddress string `protobuf:"bytes,4,opt,name=node_address,json=nodeAddress" json:"node_address"`
	SeedIP      string `protobuf:"bytes,5,opt,name=seedIP" json:"seedIP"`
	SlaveIP     string `protobuf:"bytes,6,opt,name=slaveIP" json:"slaveIP"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Node) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *Node) GetNodeIP() string {
	if m != nil {
		return m.NodeIP
	}
	return ""
}

func (m *Node) GetNodePort() string {
	if m != nil {
		return m.NodePort
	}
	return ""
}

func (m *Node) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *Node) GetSeedIP() string {
	if m != nil {
		return m.SeedIP
	}
	return ""
}

func (m *Node) GetSlaveIP() string {
	if m != nil {
		return m.SlaveIP
	}
	return ""
}

type Ip struct {
	Sguid   string `protobuf:"bytes,1,opt,name=sguid" json:"sguid"`
	SnodeIp string `protobuf:"bytes,2,opt,name=snode_ip,json=snodeIp" json:"snode_ip"`
}

func (m *Ip) Reset()                    { *m = Ip{} }
func (m *Ip) String() string            { return proto.CompactTextString(m) }
func (*Ip) ProtoMessage()               {}
func (*Ip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Ip) GetSguid() string {
	if m != nil {
		return m.Sguid
	}
	return ""
}

func (m *Ip) GetSnodeIp() string {
	if m != nil {
		return m.SnodeIp
	}
	return ""
}

type Hash struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash"`
}

func (m *Hash) Reset()                    { *m = Hash{} }
func (m *Hash) String() string            { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()               {}
func (*Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Hash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type FileCheckRequest struct {
	Hash []*Hash `protobuf:"bytes,1,rep,name=hash" json:"hash"`
}

func (m *FileCheckRequest) Reset()                    { *m = FileCheckRequest{} }
func (m *FileCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*FileCheckRequest) ProtoMessage()               {}
func (*FileCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FileCheckRequest) GetHash() []*Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

type FileCheckResponse struct {
	Result         uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message        string `protobuf:"bytes,2,opt,name=message" json:"message"`
	MerkleRootHash string `protobuf:"bytes,3,opt,name=merkle_root_hash,json=merkleRootHash" json:"merkle_root_hash"`
	IsExist        uint64 `protobuf:"varint,4,opt,name=is_exist,json=isExist" json:"is_exist"`
}

func (m *FileCheckResponse) Reset()                    { *m = FileCheckResponse{} }
func (m *FileCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*FileCheckResponse) ProtoMessage()               {}
func (*FileCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FileCheckResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *FileCheckResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FileCheckResponse) GetMerkleRootHash() string {
	if m != nil {
		return m.MerkleRootHash
	}
	return ""
}

func (m *FileCheckResponse) GetIsExist() uint64 {
	if m != nil {
		return m.IsExist
	}
	return 0
}

type GetFileUploadURLRequest struct {
	Username string   `protobuf:"bytes,1,opt,name=username" json:"username"`
	Slice    []*Slice `protobuf:"bytes,2,rep,name=slice" json:"slice"`
}

func (m *GetFileUploadURLRequest) Reset()                    { *m = GetFileUploadURLRequest{} }
func (m *GetFileUploadURLRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileUploadURLRequest) ProtoMessage()               {}
func (*GetFileUploadURLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetFileUploadURLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileUploadURLRequest) GetSlice() []*Slice {
	if m != nil {
		return m.Slice
	}
	return nil
}

type GetFileUploadURLResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
	Url     []*Url `protobuf:"bytes,3,rep,name=url" json:"url"`
}

func (m *GetFileUploadURLResponse) Reset()                    { *m = GetFileUploadURLResponse{} }
func (m *GetFileUploadURLResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileUploadURLResponse) ProtoMessage()               {}
func (*GetFileUploadURLResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetFileUploadURLResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetFileUploadURLResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileUploadURLResponse) GetUrl() []*Url {
	if m != nil {
		return m.Url
	}
	return nil
}

type GetFileSliceUploadURLRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid"`
}

func (m *GetFileSliceUploadURLRequest) Reset()                    { *m = GetFileSliceUploadURLRequest{} }
func (m *GetFileSliceUploadURLRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileSliceUploadURLRequest) ProtoMessage()               {}
func (*GetFileSliceUploadURLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetFileSliceUploadURLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileSliceUploadURLRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type GetFileSliceUploadURLResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
	Url     string `protobuf:"bytes,3,opt,name=url" json:"url"`
}

func (m *GetFileSliceUploadURLResponse) Reset()                    { *m = GetFileSliceUploadURLResponse{} }
func (m *GetFileSliceUploadURLResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileSliceUploadURLResponse) ProtoMessage()               {}
func (*GetFileSliceUploadURLResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetFileSliceUploadURLResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetFileSliceUploadURLResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileSliceUploadURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetFileStorageNodeRequest struct {
	Username string   `protobuf:"bytes,1,opt,name=username" json:"username"`
	Slice    []*Slice `protobuf:"bytes,2,rep,name=slice" json:"slice"`
}

func (m *GetFileStorageNodeRequest) Reset()                    { *m = GetFileStorageNodeRequest{} }
func (m *GetFileStorageNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileStorageNodeRequest) ProtoMessage()               {}
func (*GetFileStorageNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetFileStorageNodeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileStorageNodeRequest) GetSlice() []*Slice {
	if m != nil {
		return m.Slice
	}
	return nil
}

type GetFileStorageNodeResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
	Ip      []*Ip  `protobuf:"bytes,3,rep,name=ip" json:"ip"`
}

func (m *GetFileStorageNodeResponse) Reset()                    { *m = GetFileStorageNodeResponse{} }
func (m *GetFileStorageNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileStorageNodeResponse) ProtoMessage()               {}
func (*GetFileStorageNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetFileStorageNodeResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetFileStorageNodeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileStorageNodeResponse) GetIp() []*Ip {
	if m != nil {
		return m.Ip
	}
	return nil
}

type PutFileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid"`
	Url      string `protobuf:"bytes,3,opt,name=url" json:"url"`
}

func (m *PutFileRequest) Reset()                    { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string            { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()               {}
func (*PutFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PutFileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PutFileRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *PutFileRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type PutFileResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
}

func (m *PutFileResponse) Reset()                    { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string            { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()               {}
func (*PutFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PutFileResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PutFileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetUploadProgressRequest struct {
	Username string   `protobuf:"bytes,1,opt,name=username" json:"username"`
	Slice    []*Slice `protobuf:"bytes,2,rep,name=slice" json:"slice"`
}

func (m *GetUploadProgressRequest) Reset()                    { *m = GetUploadProgressRequest{} }
func (m *GetUploadProgressRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUploadProgressRequest) ProtoMessage()               {}
func (*GetUploadProgressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetUploadProgressRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUploadProgressRequest) GetSlice() []*Slice {
	if m != nil {
		return m.Slice
	}
	return nil
}

type GetUploadProgressResponse struct {
	Result            uint64   `protobuf:"varint,1,opt,name=result" json:"result"`
	Message           string   `protobuf:"bytes,2,opt,name=message" json:"message"`
	ProgressDone      uint64   `protobuf:"varint,3,opt,name=progress_done,json=progressDone" json:"progress_done"`
	Progressing       uint64   `protobuf:"varint,4,opt,name=progressing" json:"progressing"`
	SliceProgressDone []*Slice `protobuf:"bytes,5,rep,name=slice_progress_done,json=sliceProgressDone" json:"slice_progress_done"`
	SliceProgressing  []*Slice `protobuf:"bytes,6,rep,name=slice_progressing,json=sliceProgressing" json:"slice_progressing"`
}

func (m *GetUploadProgressResponse) Reset()                    { *m = GetUploadProgressResponse{} }
func (m *GetUploadProgressResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUploadProgressResponse) ProtoMessage()               {}
func (*GetUploadProgressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetUploadProgressResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetUploadProgressResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUploadProgressResponse) GetProgressDone() uint64 {
	if m != nil {
		return m.ProgressDone
	}
	return 0
}

func (m *GetUploadProgressResponse) GetProgressing() uint64 {
	if m != nil {
		return m.Progressing
	}
	return 0
}

func (m *GetUploadProgressResponse) GetSliceProgressDone() []*Slice {
	if m != nil {
		return m.SliceProgressDone
	}
	return nil
}

func (m *GetUploadProgressResponse) GetSliceProgressing() []*Slice {
	if m != nil {
		return m.SliceProgressing
	}
	return nil
}

type DownloadFileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid"`
	Url      string `protobuf:"bytes,3,opt,name=url" json:"url"`
}

func (m *DownloadFileRequest) Reset()                    { *m = DownloadFileRequest{} }
func (m *DownloadFileRequest) String() string            { return proto.CompactTextString(m) }
func (*DownloadFileRequest) ProtoMessage()               {}
func (*DownloadFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DownloadFileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DownloadFileRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *DownloadFileRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DownloadFileResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
}

func (m *DownloadFileResponse) Reset()                    { *m = DownloadFileResponse{} }
func (m *DownloadFileResponse) String() string            { return proto.CompactTextString(m) }
func (*DownloadFileResponse) ProtoMessage()               {}
func (*DownloadFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DownloadFileResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *DownloadFileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ComposeFileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid"`
	Ip       []*Ip  `protobuf:"bytes,3,rep,name=ip" json:"ip"`
}

func (m *ComposeFileRequest) Reset()                    { *m = ComposeFileRequest{} }
func (m *ComposeFileRequest) String() string            { return proto.CompactTextString(m) }
func (*ComposeFileRequest) ProtoMessage()               {}
func (*ComposeFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ComposeFileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ComposeFileRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *ComposeFileRequest) GetIp() []*Ip {
	if m != nil {
		return m.Ip
	}
	return nil
}

type ComposeFileResponse struct {
}

func (m *ComposeFileResponse) Reset()                    { *m = ComposeFileResponse{} }
func (m *ComposeFileResponse) String() string            { return proto.CompactTextString(m) }
func (*ComposeFileResponse) ProtoMessage()               {}
func (*ComposeFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type GetFileStorageURLRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid"`
}

func (m *GetFileStorageURLRequest) Reset()                    { *m = GetFileStorageURLRequest{} }
func (m *GetFileStorageURLRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileStorageURLRequest) ProtoMessage()               {}
func (*GetFileStorageURLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetFileStorageURLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileStorageURLRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type GetFileStorageURLResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
	Url     string `protobuf:"bytes,3,opt,name=url" json:"url"`
}

func (m *GetFileStorageURLResponse) Reset()                    { *m = GetFileStorageURLResponse{} }
func (m *GetFileStorageURLResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileStorageURLResponse) ProtoMessage()               {}
func (*GetFileStorageURLResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetFileStorageURLResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetFileStorageURLResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileStorageURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetStorageIPRequest struct {
	Guid string `protobuf:"bytes,1,opt,name=guid" json:"guid"`
}

func (m *GetStorageIPRequest) Reset()                    { *m = GetStorageIPRequest{} }
func (m *GetStorageIPRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStorageIPRequest) ProtoMessage()               {}
func (*GetStorageIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetStorageIPRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type GetStorageIPResponse struct {
	Result      uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message     string `protobuf:"bytes,2,opt,name=message" json:"message"`
	StorageAddr string `protobuf:"bytes,3,opt,name=storage_addr,json=storageAddr" json:"storage_addr"`
	FileName    string `protobuf:"bytes,4,opt,name=file_name,json=fileName" json:"file_name"`
}

func (m *GetStorageIPResponse) Reset()                    { *m = GetStorageIPResponse{} }
func (m *GetStorageIPResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStorageIPResponse) ProtoMessage()               {}
func (*GetStorageIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetStorageIPResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetStorageIPResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStorageIPResponse) GetStorageAddr() string {
	if m != nil {
		return m.StorageAddr
	}
	return ""
}

func (m *GetStorageIPResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type GetFileDownloadURLRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid"`
	Ip       []*Ip  `protobuf:"bytes,3,rep,name=ip" json:"ip"`
}

func (m *GetFileDownloadURLRequest) Reset()                    { *m = GetFileDownloadURLRequest{} }
func (m *GetFileDownloadURLRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileDownloadURLRequest) ProtoMessage()               {}
func (*GetFileDownloadURLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetFileDownloadURLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileDownloadURLRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *GetFileDownloadURLRequest) GetIp() []*Ip {
	if m != nil {
		return m.Ip
	}
	return nil
}

type GetFileDownloadURLResponse struct {
	Result  uint64 `protobuf:"varint,1,opt,name=result" json:"result"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message"`
	Url     string `protobuf:"bytes,3,opt,name=url" json:"url"`
}

func (m *GetFileDownloadURLResponse) Reset()                    { *m = GetFileDownloadURLResponse{} }
func (m *GetFileDownloadURLResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileDownloadURLResponse) ProtoMessage()               {}
func (*GetFileDownloadURLResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *GetFileDownloadURLResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetFileDownloadURLResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetFileDownloadURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*AllRequest)(nil), "data.AllRequest")
	proto.RegisterType((*Slice)(nil), "data.Slice")
	proto.RegisterType((*Url)(nil), "data.Url")
	proto.RegisterType((*Node)(nil), "data.Node")
	proto.RegisterType((*Ip)(nil), "data.Ip")
	proto.RegisterType((*Hash)(nil), "data.Hash")
	proto.RegisterType((*FileCheckRequest)(nil), "data.FileCheckRequest")
	proto.RegisterType((*FileCheckResponse)(nil), "data.FileCheckResponse")
	proto.RegisterType((*GetFileUploadURLRequest)(nil), "data.GetFileUploadURLRequest")
	proto.RegisterType((*GetFileUploadURLResponse)(nil), "data.GetFileUploadURLResponse")
	proto.RegisterType((*GetFileSliceUploadURLRequest)(nil), "data.GetFileSliceUploadURLRequest")
	proto.RegisterType((*GetFileSliceUploadURLResponse)(nil), "data.GetFileSliceUploadURLResponse")
	proto.RegisterType((*GetFileStorageNodeRequest)(nil), "data.GetFileStorageNodeRequest")
	proto.RegisterType((*GetFileStorageNodeResponse)(nil), "data.GetFileStorageNodeResponse")
	proto.RegisterType((*PutFileRequest)(nil), "data.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "data.PutFileResponse")
	proto.RegisterType((*GetUploadProgressRequest)(nil), "data.GetUploadProgressRequest")
	proto.RegisterType((*GetUploadProgressResponse)(nil), "data.GetUploadProgressResponse")
	proto.RegisterType((*DownloadFileRequest)(nil), "data.DownloadFileRequest")
	proto.RegisterType((*DownloadFileResponse)(nil), "data.DownloadFileResponse")
	proto.RegisterType((*ComposeFileRequest)(nil), "data.ComposeFileRequest")
	proto.RegisterType((*ComposeFileResponse)(nil), "data.ComposeFileResponse")
	proto.RegisterType((*GetFileStorageURLRequest)(nil), "data.GetFileStorageURLRequest")
	proto.RegisterType((*GetFileStorageURLResponse)(nil), "data.GetFileStorageURLResponse")
	proto.RegisterType((*GetStorageIPRequest)(nil), "data.GetStorageIPRequest")
	proto.RegisterType((*GetStorageIPResponse)(nil), "data.GetStorageIPResponse")
	proto.RegisterType((*GetFileDownloadURLRequest)(nil), "data.GetFileDownloadURLRequest")
	proto.RegisterType((*GetFileDownloadURLResponse)(nil), "data.GetFileDownloadURLResponse")
}

func init() {
	proto.RegisterFile("github.com/bottos-project/magiccube/service/data/proto/data.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 956 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0xbf, 0x24, 0x4e, 0x9a, 0x4e, 0xc2, 0x91, 0x6e, 0xdb, 0x3b, 0xc7, 0x47, 0xff, 0xed, 0xbd,
	0x94, 0x07, 0x1a, 0xa9, 0x08, 0xe9, 0x24, 0x24, 0xa4, 0xaa, 0x81, 0x5e, 0x10, 0xaa, 0x22, 0x9f,
	0x0a, 0x1c, 0x0f, 0x04, 0x27, 0x5e, 0x12, 0x73, 0x4e, 0xd6, 0x78, 0x37, 0x07, 0x1f, 0x01, 0xc1,
	0x17, 0xe1, 0x1b, 0xf2, 0x8a, 0x76, 0x76, 0x6d, 0xec, 0xd8, 0x39, 0x09, 0x5f, 0xde, 0x76, 0x66,
	0x76, 0x7f, 0xf3, 0x9b, 0xd9, 0xd9, 0x19, 0x1b, 0x6e, 0xe6, 0x81, 0x5c, 0xac, 0xa7, 0x57, 0x33,
	0xbe, 0x1c, 0x4c, 0xb9, 0x94, 0x5c, 0x7c, 0x12, 0xc5, 0xfc, 0x17, 0x36, 0x93, 0x83, 0xa5, 0x37,
	0x0f, 0x66, 0xb3, 0xf5, 0x94, 0x0d, 0x04, 0x8b, 0xdf, 0x06, 0x33, 0x36, 0xf0, 0x3d, 0xe9, 0x0d,
	0xa2, 0x98, 0x4b, 0x8e, 0xcb, 0x2b, 0x5c, 0x12, 0x4b, 0xad, 0x69, 0x17, 0xe0, 0x26, 0x0c, 0x5d,
	0xf6, 0xeb, 0x9a, 0x09, 0x49, 0x4f, 0xa0, 0xf9, 0x2a, 0x0c, 0x66, 0x8c, 0x1c, 0x41, 0x53, 0xcc,
	0xd7, 0x81, 0x6f, 0xd7, 0xce, 0x6b, 0x97, 0xfb, 0xae, 0x16, 0xe8, 0x00, 0x1a, 0x0f, 0x71, 0x58,
	0x6e, 0x24, 0x04, 0x2c, 0xb1, 0x8e, 0x43, 0xbb, 0x8e, 0x4a, 0x5c, 0xd3, 0xbf, 0x6b, 0x60, 0xdd,
	0x73, 0x9f, 0x91, 0x27, 0xd0, 0x5a, 0x71, 0x9f, 0x8d, 0x86, 0xe6, 0x8c, 0x91, 0x52, 0xfd, 0xd8,
	0x1c, 0x33, 0x12, 0x79, 0x06, 0xfb, 0x6a, 0x35, 0x89, 0x78, 0x2c, 0xed, 0x06, 0x9a, 0xda, 0x4a,
	0x31, 0xe6, 0xb1, 0x24, 0x17, 0xd0, 0x45, 0xa3, 0xe7, 0xfb, 0x31, 0x13, 0xc2, 0xb6, 0xd0, 0xde,
	0x51, 0xba, 0x1b, 0xad, 0x52, 0xb8, 0x82, 0x31, 0x7f, 0x34, 0xb6, 0x9b, 0x1a, 0x57, 0x4b, 0xc4,
	0x86, 0x3d, 0x11, 0x7a, 0x6f, 0x95, 0xc3, 0x16, 0x1a, 0x12, 0x91, 0x7e, 0x06, 0xf5, 0x51, 0xb4,
	0x25, 0xb4, 0x3e, 0xb4, 0x05, 0x7a, 0x0c, 0x22, 0xc3, 0x73, 0x0f, 0xe5, 0x51, 0x44, 0x1d, 0xb0,
	0x5e, 0x7a, 0x62, 0xa1, 0xa2, 0x5f, 0x78, 0x62, 0x61, 0xce, 0xe1, 0x9a, 0x5e, 0x43, 0xef, 0xab,
	0x20, 0x64, 0xb7, 0x0b, 0x36, 0x7b, 0x63, 0x32, 0x4c, 0x4e, 0xd3, 0x7d, 0x8d, 0xcb, 0xce, 0x35,
	0x5c, 0xe1, 0x85, 0x28, 0x04, 0x73, 0xe6, 0xcf, 0x1a, 0x1c, 0x64, 0x0e, 0x89, 0x88, 0xaf, 0x04,
	0xa6, 0x2f, 0x66, 0x62, 0x1d, 0x4a, 0xc4, 0xb7, 0x5c, 0x23, 0xa9, 0x70, 0x96, 0x4c, 0x08, 0x6f,
	0xce, 0x12, 0x5e, 0x46, 0x24, 0x97, 0xd0, 0x5b, 0xb2, 0xf8, 0x4d, 0xc8, 0x26, 0x31, 0xe7, 0x72,
	0x82, 0x3e, 0x75, 0x1e, 0x1f, 0x6b, 0xbd, 0xcb, 0xb9, 0x44, 0xe6, 0x7d, 0x68, 0x07, 0x62, 0xc2,
	0x7e, 0x0f, 0x84, 0xc4, 0x4c, 0x5a, 0xee, 0x5e, 0x20, 0xbe, 0x54, 0x22, 0xfd, 0x1e, 0x9e, 0xde,
	0x31, 0xa9, 0xe8, 0x3c, 0x44, 0x21, 0xf7, 0xfc, 0x07, 0xf7, 0x9b, 0x24, 0x0e, 0x07, 0xda, 0x6b,
	0xc1, 0xe2, 0x95, 0xb7, 0x64, 0x26, 0xe6, 0x54, 0x26, 0x17, 0xd0, 0x14, 0xaa, 0x8a, 0xec, 0x3a,
	0x06, 0xd9, 0xd1, 0x41, 0x62, 0x61, 0xb9, 0xda, 0x42, 0x03, 0xb0, 0x8b, 0xc8, 0x95, 0x83, 0x7d,
	0x06, 0x0d, 0x55, 0x79, 0x0d, 0x74, 0xb7, 0xaf, 0xdd, 0x3d, 0xc4, 0xa1, 0xab, 0xb4, 0xf4, 0x1e,
	0x3e, 0x32, 0xae, 0x90, 0xc1, 0xff, 0x8a, 0x84, 0x80, 0x85, 0xd5, 0x60, 0x6a, 0x1a, 0x1f, 0xc1,
	0x0c, 0x4e, 0xb6, 0xe0, 0x55, 0xe6, 0xdf, 0x4b, 0xf8, 0x2b, 0x2d, 0x92, 0xfe, 0x01, 0xfa, 0x89,
	0x13, 0xc9, 0x63, 0x6f, 0xce, 0xd4, 0x2b, 0xda, 0x51, 0xee, 0x17, 0xe0, 0x94, 0x61, 0x57, 0x66,
	0x6f, 0x43, 0x3d, 0x88, 0x4c, 0xf2, 0xdb, 0xda, 0xdf, 0x28, 0x72, 0xeb, 0x41, 0x44, 0x5d, 0x78,
	0x3c, 0x5e, 0xa3, 0xa7, 0x8a, 0xc9, 0x2e, 0xc9, 0xcc, 0x2d, 0x7c, 0x98, 0x62, 0x56, 0xa5, 0x4c,
	0x5f, 0x63, 0xf9, 0xe9, 0xab, 0x1b, 0xc7, 0x7c, 0xae, 0x7a, 0xc6, 0x8e, 0xb2, 0xfb, 0x57, 0x1d,
	0xaf, 0x6e, 0x13, 0xbb, 0x72, 0x76, 0x9f, 0xc3, 0x07, 0x91, 0x41, 0x99, 0xf8, 0x7c, 0xc5, 0x30,
	0x17, 0x96, 0xdb, 0x4d, 0x94, 0x43, 0xbe, 0x62, 0xe4, 0x1c, 0x3a, 0x89, 0x1c, 0xac, 0xe6, 0xe6,
	0x19, 0x67, 0x55, 0xe4, 0x73, 0x38, 0x44, 0x7e, 0x93, 0x3c, 0x58, 0xb3, 0x18, 0xc7, 0x01, 0xee,
	0x1b, 0x67, 0xe1, 0x5f, 0xc0, 0x41, 0xfe, 0xb0, 0x72, 0xd2, 0x2a, 0x1e, 0xed, 0xe5, 0x8e, 0x06,
	0xab, 0x39, 0xfd, 0x0e, 0x0e, 0x87, 0xfc, 0xb7, 0x95, 0xca, 0xc5, 0x6e, 0xcb, 0xe0, 0x25, 0x1c,
	0xe5, 0x81, 0x2b, 0xd7, 0xc2, 0x8f, 0x40, 0x6e, 0xf9, 0x32, 0xe2, 0x82, 0xbd, 0x0f, 0xc3, 0xed,
	0x8f, 0xe0, 0x18, 0x0e, 0x73, 0xf8, 0x9a, 0x28, 0xfd, 0x3a, 0xed, 0x80, 0xe6, 0x15, 0xbe, 0x47,
	0x4b, 0x9a, 0x6c, 0x76, 0x8b, 0x5d, 0xb7, 0xa3, 0x8f, 0xe1, 0xf0, 0x8e, 0x49, 0x03, 0x3e, 0x1a,
	0x27, 0x3c, 0x13, 0x2e, 0xb5, 0x0c, 0x97, 0x3f, 0x6a, 0x70, 0x94, 0xdf, 0x5b, 0x99, 0xc7, 0x05,
	0x74, 0x85, 0x86, 0xc1, 0x51, 0x6f, 0x08, 0x75, 0x8c, 0x4e, 0x8d, 0x7a, 0xf5, 0x9d, 0xf0, 0x73,
	0x10, 0xb2, 0x09, 0xa6, 0x4a, 0x7f, 0x07, 0xb4, 0x95, 0xe2, 0xde, 0x5b, 0x32, 0xca, 0xd2, 0xb4,
	0x24, 0xa5, 0x52, 0x3d, 0xc7, 0xef, 0xb8, 0xe0, 0x9f, 0xd2, 0x7e, 0x9a, 0x73, 0xb3, 0xbb, 0xf4,
	0x5f, 0xff, 0xd3, 0x02, 0x6b, 0xe8, 0x49, 0x8f, 0x7c, 0x01, 0xfb, 0xe9, 0xc7, 0x01, 0x79, 0xa2,
	0x59, 0x6c, 0x7e, 0x62, 0x38, 0x4f, 0x0b, 0x7a, 0x53, 0x72, 0x8f, 0xc8, 0x2b, 0xe8, 0x6d, 0x8e,
	0x5d, 0x72, 0xa2, 0xb7, 0x6f, 0x19, 0xf4, 0xce, 0xe9, 0x36, 0x73, 0x0a, 0x3a, 0x85, 0xe3, 0xd2,
	0x81, 0x48, 0x68, 0xee, 0x68, 0xe9, 0xf4, 0x75, 0x9e, 0xbf, 0x73, 0x4f, 0xea, 0xe3, 0x5b, 0x38,
	0x28, 0x34, 0x55, 0xf2, 0x1f, 0xb5, 0xd2, 0x4e, 0xee, 0x9c, 0x6d, 0xb5, 0xa7, 0xb8, 0xaf, 0x81,
	0x14, 0x67, 0x21, 0x39, 0xcb, 0x93, 0x2a, 0x4c, 0x60, 0xe7, 0x7c, 0xfb, 0x86, 0x14, 0xfa, 0x05,
	0xec, 0x99, 0x41, 0x45, 0x8e, 0xf4, 0xf6, 0xfc, 0x2c, 0x74, 0x8e, 0x37, 0xb4, 0x1b, 0xc1, 0xe6,
	0x9f, 0x33, 0x39, 0x2d, 0x73, 0x99, 0x49, 0xe4, 0xd9, 0x56, 0x7b, 0x8a, 0x7b, 0x07, 0xdd, 0x6c,
	0xcf, 0x24, 0x7d, 0x7d, 0xa4, 0xa4, 0x41, 0x3b, 0x4e, 0x99, 0x29, 0x05, 0x1a, 0x42, 0x27, 0xd3,
	0xd2, 0x88, 0xad, 0x37, 0x17, 0xbb, 0xa8, 0xd3, 0x2f, 0xb1, 0x64, 0xe9, 0x64, 0x1b, 0x45, 0x42,
	0xa7, 0xa4, 0xd1, 0x24, 0x74, 0xca, 0xfa, 0x4a, 0xee, 0x12, 0x33, 0x0f, 0x70, 0xe3, 0x12, 0x8b,
	0x1d, 0x60, 0xe3, 0x12, 0x4b, 0xde, 0x2e, 0x7d, 0x34, 0x6d, 0xe1, 0xbf, 0xd2, 0xa7, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x79, 0x0d, 0xcf, 0x6b, 0x70, 0x0d, 0x00, 0x00,
}
