// Code generated by protoc-gen-go. DO NOT EDIT.
// source: asset.proto

/*
Package asset is a generated protocol buffer package.

It is generated from these files:
	asset.proto

It has these top-level messages:
	PushTxRequest
	GetFileUploadURLRequest
	GetFileUploadURLResponse
	RegisterFileRequest
	RegisterFileResponse
	QueryUploadedDataResponse
	QueryUploadedData
	QueryUploadedRow
	RegisterRequest
	RegisterResponse
	QueryAllAssetRequest
	QueryPara
	QueryAllAssetResponse
	ModifyRequest
	ModifyResponse
	GetFileUploadStatRequest
	GetFileUploadStatResponse
	GetDownLoadURLRequest
	GetDownLoadURLResponse
	QueryByIDRequest
	GetUserPurchaseAssetListRequest
	GetUserPurchaseAssetListResponse
	QueryPurchaseData
	QueryPurchaseRow
	PreSaleNoticeRequest
	PreSaleNoticeResponse
	QueryRequest
	QueryResponse
	QueryData
	AssetData
	QueryMyNoticeRequest
	QueryMyNoticeResponse
	QueryNoticeData
	QueryNoticeRow
*/
package asset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushTxRequest struct {
	Version     uint32 `protobuf:"varint,1,opt,name=version" json:"version"`
	CursorNum   uint32 `protobuf:"varint,2,opt,name=cursor_num,json=cursorNum" json:"cursor_num"`
	CursorLabel uint32 `protobuf:"varint,3,opt,name=cursor_label,json=cursorLabel" json:"cursor_label"`
	Lifetime    uint64 `protobuf:"varint,4,opt,name=lifetime" json:"lifetime"`
	Sender      string `protobuf:"bytes,5,opt,name=sender" json:"sender"`
	Contract    string `protobuf:"bytes,6,opt,name=contract" json:"contract"`
	Method      string `protobuf:"bytes,7,opt,name=method" json:"method"`
	Param       string `protobuf:"bytes,8,opt,name=param" json:"param"`
	SigAlg      uint32 `protobuf:"varint,9,opt,name=sig_alg,json=sigAlg" json:"sig_alg"`
	Signature   string `protobuf:"bytes,10,opt,name=signature" json:"signature"`
}

func (m *PushTxRequest) Reset()                    { *m = PushTxRequest{} }
func (m *PushTxRequest) String() string            { return proto.CompactTextString(m) }
func (*PushTxRequest) ProtoMessage()               {}
func (*PushTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushTxRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PushTxRequest) GetCursorNum() uint32 {
	if m != nil {
		return m.CursorNum
	}
	return 0
}

func (m *PushTxRequest) GetCursorLabel() uint32 {
	if m != nil {
		return m.CursorLabel
	}
	return 0
}

func (m *PushTxRequest) GetLifetime() uint64 {
	if m != nil {
		return m.Lifetime
	}
	return 0
}

func (m *PushTxRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PushTxRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *PushTxRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *PushTxRequest) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *PushTxRequest) GetSigAlg() uint32 {
	if m != nil {
		return m.SigAlg
	}
	return 0
}

func (m *PushTxRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type GetFileUploadURLRequest struct {
	//    string username = 1;
	//    int64 fileSize = 2;
	//    string fileName = 3;
	//    int32 filePolicy = 4;
	//    int32 fileNumber = 5;
	//    string fileash = 6;
	//    string signature = 7;
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *GetFileUploadURLRequest) Reset()                    { *m = GetFileUploadURLRequest{} }
func (m *GetFileUploadURLRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileUploadURLRequest) ProtoMessage()               {}
func (*GetFileUploadURLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetFileUploadURLRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type GetFileUploadURLResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *GetFileUploadURLResponse) Reset()                    { *m = GetFileUploadURLResponse{} }
func (m *GetFileUploadURLResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileUploadURLResponse) ProtoMessage()               {}
func (*GetFileUploadURLResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetFileUploadURLResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetFileUploadURLResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetFileUploadURLResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RegisterFileRequest struct {
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *RegisterFileRequest) Reset()                    { *m = RegisterFileRequest{} }
func (m *RegisterFileRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterFileRequest) ProtoMessage()               {}
func (*RegisterFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterFileRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type RegisterFileResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *RegisterFileResponse) Reset()                    { *m = RegisterFileResponse{} }
func (m *RegisterFileResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterFileResponse) ProtoMessage()               {}
func (*RegisterFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegisterFileResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterFileResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterFileResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type QueryUploadedDataResponse struct {
	Code int32              `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryUploadedData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string             `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryUploadedDataResponse) Reset()                    { *m = QueryUploadedDataResponse{} }
func (m *QueryUploadedDataResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryUploadedDataResponse) ProtoMessage()               {}
func (*QueryUploadedDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryUploadedDataResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryUploadedDataResponse) GetData() *QueryUploadedData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryUploadedDataResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryUploadedData struct {
	PageNum  uint32              `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	RowCount uint32              `protobuf:"varint,2,opt,name=rowCount" json:"rowCount"`
	Row      []*QueryUploadedRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryUploadedData) Reset()                    { *m = QueryUploadedData{} }
func (m *QueryUploadedData) String() string            { return proto.CompactTextString(m) }
func (*QueryUploadedData) ProtoMessage()               {}
func (*QueryUploadedData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QueryUploadedData) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryUploadedData) GetRowCount() uint32 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryUploadedData) GetRow() []*QueryUploadedRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type QueryUploadedRow struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username"`
	FileHash   string `protobuf:"bytes,2,opt,name=file_hash,json=fileHash" json:"file_hash"`
	FileName   string `protobuf:"bytes,3,opt,name=file_name,json=fileName" json:"file_name"`
	FileSize   uint64 `protobuf:"varint,4,opt,name=file_size,json=fileSize" json:"file_size"`
	FilePolicy string `protobuf:"bytes,5,opt,name=file_policy,json=filePolicy" json:"file_policy"`
	FileNumber uint64 `protobuf:"varint,6,opt,name=file_number,json=fileNumber" json:"file_number"`
	SimOrAss   uint32 `protobuf:"varint,7,opt,name=sim_or_ass,json=simOrAss" json:"sim_or_ass"`
	OpType     uint32 `protobuf:"varint,8,opt,name=op_type,json=opType" json:"op_type"`
	StoreAddr  string `protobuf:"bytes,9,opt,name=store_addr,json=storeAddr" json:"store_addr"`
	CreateTime uint64 `protobuf:"varint,10,opt,name=create_time,json=createTime" json:"create_time"`
}

func (m *QueryUploadedRow) Reset()                    { *m = QueryUploadedRow{} }
func (m *QueryUploadedRow) String() string            { return proto.CompactTextString(m) }
func (*QueryUploadedRow) ProtoMessage()               {}
func (*QueryUploadedRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryUploadedRow) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryUploadedRow) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *QueryUploadedRow) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *QueryUploadedRow) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *QueryUploadedRow) GetFilePolicy() string {
	if m != nil {
		return m.FilePolicy
	}
	return ""
}

func (m *QueryUploadedRow) GetFileNumber() uint64 {
	if m != nil {
		return m.FileNumber
	}
	return 0
}

func (m *QueryUploadedRow) GetSimOrAss() uint32 {
	if m != nil {
		return m.SimOrAss
	}
	return 0
}

func (m *QueryUploadedRow) GetOpType() uint32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

func (m *QueryUploadedRow) GetStoreAddr() string {
	if m != nil {
		return m.StoreAddr
	}
	return ""
}

func (m *QueryUploadedRow) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type RegisterRequest struct {
	// string username = 1;
	// string asset_id = 2;
	// string session_id = 3;
	// string asset_name = 4;
	// int32 feature_tag = 5;
	// string asset_sample_path = 6;
	// string asset_sample_hash = 7;
	// string asset_storage_path = 8;
	// string asset_storage_hash = 9;
	// string expire_time = 10;
	// int64 price = 11;
	// string description = 12;
	// string upload_date = 13;
	// string signature = 14;
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RegisterRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type RegisterResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RegisterResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type QueryAllAssetRequest struct {
	Username  string     `protobuf:"bytes,1,opt,name=username" json:"username"`
	SessionId string     `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id"`
	QueryPara *QueryPara `protobuf:"bytes,3,opt,name=query_para,json=queryPara" json:"query_para"`
}

func (m *QueryAllAssetRequest) Reset()                    { *m = QueryAllAssetRequest{} }
func (m *QueryAllAssetRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryAllAssetRequest) ProtoMessage()               {}
func (*QueryAllAssetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryAllAssetRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryAllAssetRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *QueryAllAssetRequest) GetQueryPara() *QueryPara {
	if m != nil {
		return m.QueryPara
	}
	return nil
}

type QueryPara struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id"`
}

func (m *QueryPara) Reset()                    { *m = QueryPara{} }
func (m *QueryPara) String() string            { return proto.CompactTextString(m) }
func (*QueryPara) ProtoMessage()               {}
func (*QueryPara) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *QueryPara) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryPara) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type QueryAllAssetResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *QueryAllAssetResponse) Reset()                    { *m = QueryAllAssetResponse{} }
func (m *QueryAllAssetResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryAllAssetResponse) ProtoMessage()               {}
func (*QueryAllAssetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *QueryAllAssetResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryAllAssetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *QueryAllAssetResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ModifyRequest struct {
	//    string username = 1;
	//    string signature = 2;
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *ModifyRequest) Reset()                    { *m = ModifyRequest{} }
func (m *ModifyRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyRequest) ProtoMessage()               {}
func (*ModifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ModifyRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type ModifyResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *ModifyResponse) Reset()                    { *m = ModifyResponse{} }
func (m *ModifyResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyResponse) ProtoMessage()               {}
func (*ModifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ModifyResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModifyResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ModifyResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetFileUploadStatRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	FileName string `protobuf:"bytes,2,opt,name=fileName" json:"fileName"`
}

func (m *GetFileUploadStatRequest) Reset()                    { *m = GetFileUploadStatRequest{} }
func (m *GetFileUploadStatRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileUploadStatRequest) ProtoMessage()               {}
func (*GetFileUploadStatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetFileUploadStatRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFileUploadStatRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type GetFileUploadStatResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *GetFileUploadStatResponse) Reset()                    { *m = GetFileUploadStatResponse{} }
func (m *GetFileUploadStatResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileUploadStatResponse) ProtoMessage()               {}
func (*GetFileUploadStatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetFileUploadStatResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetFileUploadStatResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetFileUploadStatResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetDownLoadURLRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username"`
	FileName string `protobuf:"bytes,2,opt,name=fileName" json:"fileName"`
}

func (m *GetDownLoadURLRequest) Reset()                    { *m = GetDownLoadURLRequest{} }
func (m *GetDownLoadURLRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDownLoadURLRequest) ProtoMessage()               {}
func (*GetDownLoadURLRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetDownLoadURLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetDownLoadURLRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type GetDownLoadURLResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *GetDownLoadURLResponse) Reset()                    { *m = GetDownLoadURLResponse{} }
func (m *GetDownLoadURLResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDownLoadURLResponse) ProtoMessage()               {}
func (*GetDownLoadURLResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetDownLoadURLResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetDownLoadURLResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetDownLoadURLResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type QueryByIDRequest struct {
	PageSize int32  `protobuf:"varint,1,opt,name=pageSize" json:"pageSize"`
	PageNum  int32  `protobuf:"varint,2,opt,name=pageNum" json:"pageNum"`
	AssetID  string `protobuf:"bytes,3,opt,name=assetID" json:"assetID"`
}

func (m *QueryByIDRequest) Reset()                    { *m = QueryByIDRequest{} }
func (m *QueryByIDRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryByIDRequest) ProtoMessage()               {}
func (*QueryByIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *QueryByIDRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryByIDRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryByIDRequest) GetAssetID() string {
	if m != nil {
		return m.AssetID
	}
	return ""
}

type GetUserPurchaseAssetListRequest struct {
	PageSize int32  `protobuf:"varint,1,opt,name=pageSize" json:"pageSize"`
	PageNum  int32  `protobuf:"varint,2,opt,name=pageNum" json:"pageNum"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username"`
	AssetId  string `protobuf:"bytes,4,opt,name=asset_id,json=assetId" json:"asset_id"`
}

func (m *GetUserPurchaseAssetListRequest) Reset()         { *m = GetUserPurchaseAssetListRequest{} }
func (m *GetUserPurchaseAssetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserPurchaseAssetListRequest) ProtoMessage()    {}
func (*GetUserPurchaseAssetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{20}
}

func (m *GetUserPurchaseAssetListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetUserPurchaseAssetListRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetUserPurchaseAssetListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserPurchaseAssetListRequest) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

type GetUserPurchaseAssetListResponse struct {
	Code int32              `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryPurchaseData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string             `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *GetUserPurchaseAssetListResponse) Reset()         { *m = GetUserPurchaseAssetListResponse{} }
func (m *GetUserPurchaseAssetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserPurchaseAssetListResponse) ProtoMessage()    {}
func (*GetUserPurchaseAssetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21}
}

func (m *GetUserPurchaseAssetListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUserPurchaseAssetListResponse) GetData() *QueryPurchaseData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserPurchaseAssetListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryPurchaseData struct {
	PageNum  uint64              `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	RowCount uint64              `protobuf:"varint,2,opt,name=rowCount" json:"rowCount"`
	Row      []*QueryPurchaseRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryPurchaseData) Reset()                    { *m = QueryPurchaseData{} }
func (m *QueryPurchaseData) String() string            { return proto.CompactTextString(m) }
func (*QueryPurchaseData) ProtoMessage()               {}
func (*QueryPurchaseData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *QueryPurchaseData) GetPageNum() uint64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryPurchaseData) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryPurchaseData) GetRow() []*QueryPurchaseRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type QueryPurchaseRow struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id"`
	AssetId   string `protobuf:"bytes,3,opt,name=asset_id,json=assetId" json:"asset_id"`
	DataReqId string `protobuf:"bytes,4,opt,name=data_req_id,json=dataReqId" json:"data_req_id"`
	Consumer  string `protobuf:"bytes,5,opt,name=consumer" json:"consumer"`
}

func (m *QueryPurchaseRow) Reset()                    { *m = QueryPurchaseRow{} }
func (m *QueryPurchaseRow) String() string            { return proto.CompactTextString(m) }
func (*QueryPurchaseRow) ProtoMessage()               {}
func (*QueryPurchaseRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *QueryPurchaseRow) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryPurchaseRow) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *QueryPurchaseRow) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *QueryPurchaseRow) GetDataReqId() string {
	if m != nil {
		return m.DataReqId
	}
	return ""
}

func (m *QueryPurchaseRow) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

type PreSaleNoticeRequest struct {
	PostBody string `protobuf:"bytes,1,opt,name=postBody" json:"postBody"`
}

func (m *PreSaleNoticeRequest) Reset()                    { *m = PreSaleNoticeRequest{} }
func (m *PreSaleNoticeRequest) String() string            { return proto.CompactTextString(m) }
func (*PreSaleNoticeRequest) ProtoMessage()               {}
func (*PreSaleNoticeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PreSaleNoticeRequest) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

type PreSaleNoticeResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *PreSaleNoticeResponse) Reset()                    { *m = PreSaleNoticeResponse{} }
func (m *PreSaleNoticeResponse) String() string            { return proto.CompactTextString(m) }
func (*PreSaleNoticeResponse) ProtoMessage()               {}
func (*PreSaleNoticeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PreSaleNoticeResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PreSaleNoticeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PreSaleNoticeResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type QueryRequest struct {
	PageSize  uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size"`
	PageNum   uint32 `protobuf:"varint,2,opt,name=page_num,json=pageNum" json:"page_num"`
	Username  string `protobuf:"bytes,3,opt,name=username" json:"username"`
	Random    string `protobuf:"bytes,4,opt,name=random" json:"random"`
	Signature string `protobuf:"bytes,5,opt,name=signature" json:"signature"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *QueryRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryRequest) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryRequest) GetRandom() string {
	if m != nil {
		return m.Random
	}
	return ""
}

func (m *QueryRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type QueryResponse struct {
	Code int32      `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string     `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *QueryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResponse) GetData() *QueryData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryData struct {
	PageNum  uint32       `protobuf:"varint,1,opt,name=page_num,json=pageNum" json:"page_num"`
	RowCount uint32       `protobuf:"varint,2,opt,name=row_count,json=rowCount" json:"row_count"`
	Row      []*AssetData `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryData) Reset()                    { *m = QueryData{} }
func (m *QueryData) String() string            { return proto.CompactTextString(m) }
func (*QueryData) ProtoMessage()               {}
func (*QueryData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *QueryData) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryData) GetRowCount() uint32 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryData) GetRow() []*AssetData {
	if m != nil {
		return m.Row
	}
	return nil
}

type AssetData struct {
	AssetId     string `protobuf:"bytes,1,opt,name=asset_id,json=assetId" json:"asset_id"`
	Username    string `protobuf:"bytes,2,opt,name=username" json:"username"`
	AssetName   string `protobuf:"bytes,3,opt,name=asset_name,json=assetName" json:"asset_name"`
	AssetType   string `protobuf:"bytes,4,opt,name=asset_type,json=assetType" json:"asset_type"`
	FeatureTag  string `protobuf:"bytes,5,opt,name=feature_tag,json=featureTag" json:"feature_tag"`
	SampleHash  string `protobuf:"bytes,6,opt,name=sample_hash,json=sampleHash" json:"sample_hash"`
	StorageHash string `protobuf:"bytes,7,opt,name=storage_hash,json=storageHash" json:"storage_hash"`
	ExpireTime  uint32 `protobuf:"varint,8,opt,name=expire_time,json=expireTime" json:"expire_time"`
	OpType      uint32 `protobuf:"varint,9,opt,name=op_type,json=opType" json:"op_type"`
	Price       uint64 `protobuf:"varint,10,opt,name=price" json:"price"`
	Description string `protobuf:"bytes,11,opt,name=description" json:"description"`
	CreateTime  uint64 `protobuf:"varint,12,opt,name=create_time,json=createTime" json:"create_time"`
}

func (m *AssetData) Reset()                    { *m = AssetData{} }
func (m *AssetData) String() string            { return proto.CompactTextString(m) }
func (*AssetData) ProtoMessage()               {}
func (*AssetData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *AssetData) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *AssetData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AssetData) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *AssetData) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *AssetData) GetFeatureTag() string {
	if m != nil {
		return m.FeatureTag
	}
	return ""
}

func (m *AssetData) GetSampleHash() string {
	if m != nil {
		return m.SampleHash
	}
	return ""
}

func (m *AssetData) GetStorageHash() string {
	if m != nil {
		return m.StorageHash
	}
	return ""
}

func (m *AssetData) GetExpireTime() uint32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *AssetData) GetOpType() uint32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

func (m *AssetData) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AssetData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AssetData) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type QueryMyNoticeRequest struct {
	PageSize  int32  `protobuf:"varint,1,opt,name=pageSize" json:"pageSize"`
	PageNum   int32  `protobuf:"varint,2,opt,name=pageNum" json:"pageNum"`
	Username  string `protobuf:"bytes,3,opt,name=username" json:"username"`
	Random    string `protobuf:"bytes,4,opt,name=random" json:"random"`
	Signature string `protobuf:"bytes,5,opt,name=signature" json:"signature"`
}

func (m *QueryMyNoticeRequest) Reset()                    { *m = QueryMyNoticeRequest{} }
func (m *QueryMyNoticeRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryMyNoticeRequest) ProtoMessage()               {}
func (*QueryMyNoticeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *QueryMyNoticeRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *QueryMyNoticeRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryMyNoticeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryMyNoticeRequest) GetRandom() string {
	if m != nil {
		return m.Random
	}
	return ""
}

func (m *QueryMyNoticeRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type QueryMyNoticeResponse struct {
	Code int32            `protobuf:"varint,1,opt,name=code" json:"code"`
	Data *QueryNoticeData `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string           `protobuf:"bytes,3,opt,name=msg" json:"msg"`
}

func (m *QueryMyNoticeResponse) Reset()                    { *m = QueryMyNoticeResponse{} }
func (m *QueryMyNoticeResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryMyNoticeResponse) ProtoMessage()               {}
func (*QueryMyNoticeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *QueryMyNoticeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryMyNoticeResponse) GetData() *QueryNoticeData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryMyNoticeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryNoticeData struct {
	PageNum  uint32            `protobuf:"varint,1,opt,name=pageNum" json:"pageNum"`
	RowCount uint32            `protobuf:"varint,2,opt,name=rowCount" json:"rowCount"`
	Row      []*QueryNoticeRow `protobuf:"bytes,3,rep,name=row" json:"row"`
}

func (m *QueryNoticeData) Reset()                    { *m = QueryNoticeData{} }
func (m *QueryNoticeData) String() string            { return proto.CompactTextString(m) }
func (*QueryNoticeData) ProtoMessage()               {}
func (*QueryNoticeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *QueryNoticeData) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *QueryNoticeData) GetRowCount() uint32 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryNoticeData) GetRow() []*QueryNoticeRow {
	if m != nil {
		return m.Row
	}
	return nil
}

type QueryNoticeRow struct {
	Username    string `protobuf:"bytes,1,opt,name=username" json:"username"`
	NoticeId    string `protobuf:"bytes,2,opt,name=notice_id,json=noticeId" json:"notice_id"`
	AssetId     string `protobuf:"bytes,3,opt,name=asset_id,json=assetId" json:"asset_id"`
	AssetName   string `protobuf:"bytes,4,opt,name=asset_name,json=assetName" json:"asset_name"`
	DataReqId   string `protobuf:"bytes,5,opt,name=data_req_id,json=dataReqId" json:"data_req_id"`
	DataReqName string `protobuf:"bytes,6,opt,name=data_req_name,json=dataReqName" json:"data_req_name"`
	Consumer    string `protobuf:"bytes,7,opt,name=consumer" json:"consumer"`
	ReadFlag    string `protobuf:"bytes,8,opt,name=read_flag,json=readFlag" json:"read_flag"`
	Time        uint64 `protobuf:"varint,9,opt,name=time" json:"time"`
}

func (m *QueryNoticeRow) Reset()                    { *m = QueryNoticeRow{} }
func (m *QueryNoticeRow) String() string            { return proto.CompactTextString(m) }
func (*QueryNoticeRow) ProtoMessage()               {}
func (*QueryNoticeRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *QueryNoticeRow) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryNoticeRow) GetNoticeId() string {
	if m != nil {
		return m.NoticeId
	}
	return ""
}

func (m *QueryNoticeRow) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *QueryNoticeRow) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *QueryNoticeRow) GetDataReqId() string {
	if m != nil {
		return m.DataReqId
	}
	return ""
}

func (m *QueryNoticeRow) GetDataReqName() string {
	if m != nil {
		return m.DataReqName
	}
	return ""
}

func (m *QueryNoticeRow) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *QueryNoticeRow) GetReadFlag() string {
	if m != nil {
		return m.ReadFlag
	}
	return ""
}

func (m *QueryNoticeRow) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*PushTxRequest)(nil), "PushTxRequest")
	proto.RegisterType((*GetFileUploadURLRequest)(nil), "GetFileUploadURLRequest")
	proto.RegisterType((*GetFileUploadURLResponse)(nil), "GetFileUploadURLResponse")
	proto.RegisterType((*RegisterFileRequest)(nil), "RegisterFileRequest")
	proto.RegisterType((*RegisterFileResponse)(nil), "RegisterFileResponse")
	proto.RegisterType((*QueryUploadedDataResponse)(nil), "QueryUploadedDataResponse")
	proto.RegisterType((*QueryUploadedData)(nil), "QueryUploadedData")
	proto.RegisterType((*QueryUploadedRow)(nil), "QueryUploadedRow")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*QueryAllAssetRequest)(nil), "QueryAllAssetRequest")
	proto.RegisterType((*QueryPara)(nil), "QueryPara")
	proto.RegisterType((*QueryAllAssetResponse)(nil), "QueryAllAssetResponse")
	proto.RegisterType((*ModifyRequest)(nil), "ModifyRequest")
	proto.RegisterType((*ModifyResponse)(nil), "ModifyResponse")
	proto.RegisterType((*GetFileUploadStatRequest)(nil), "GetFileUploadStatRequest")
	proto.RegisterType((*GetFileUploadStatResponse)(nil), "GetFileUploadStatResponse")
	proto.RegisterType((*GetDownLoadURLRequest)(nil), "GetDownLoadURLRequest")
	proto.RegisterType((*GetDownLoadURLResponse)(nil), "GetDownLoadURLResponse")
	proto.RegisterType((*QueryByIDRequest)(nil), "QueryByIDRequest")
	proto.RegisterType((*GetUserPurchaseAssetListRequest)(nil), "GetUserPurchaseAssetListRequest")
	proto.RegisterType((*GetUserPurchaseAssetListResponse)(nil), "GetUserPurchaseAssetListResponse")
	proto.RegisterType((*QueryPurchaseData)(nil), "QueryPurchaseData")
	proto.RegisterType((*QueryPurchaseRow)(nil), "QueryPurchaseRow")
	proto.RegisterType((*PreSaleNoticeRequest)(nil), "PreSaleNoticeRequest")
	proto.RegisterType((*PreSaleNoticeResponse)(nil), "PreSaleNoticeResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
	proto.RegisterType((*QueryData)(nil), "QueryData")
	proto.RegisterType((*AssetData)(nil), "AssetData")
	proto.RegisterType((*QueryMyNoticeRequest)(nil), "QueryMyNoticeRequest")
	proto.RegisterType((*QueryMyNoticeResponse)(nil), "QueryMyNoticeResponse")
	proto.RegisterType((*QueryNoticeData)(nil), "QueryNoticeData")
	proto.RegisterType((*QueryNoticeRow)(nil), "QueryNoticeRow")
}

func init() { proto.RegisterFile("asset.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcf, 0x6e, 0xdb, 0x46,
	0x13, 0xb7, 0x2c, 0x59, 0x16, 0x47, 0x96, 0xe3, 0xec, 0x67, 0x3b, 0xb4, 0x92, 0x2f, 0x71, 0xd8,
	0xa2, 0x70, 0x51, 0x84, 0x40, 0x5d, 0xb4, 0x40, 0x0f, 0x05, 0xea, 0xd4, 0x48, 0xea, 0xc2, 0x51,
	0x1c, 0xc6, 0x3e, 0x13, 0x6b, 0x71, 0x2d, 0xb3, 0xe0, 0x3f, 0xef, 0x92, 0x75, 0x14, 0xf4, 0x19,
	0x7a, 0xea, 0xa1, 0xa7, 0xa2, 0x87, 0xde, 0xfb, 0x06, 0x7d, 0xae, 0x1e, 0x8b, 0x9d, 0x5d, 0x52,
	0x24, 0x25, 0x3b, 0x4a, 0xd4, 0x9b, 0x66, 0x76, 0x76, 0x66, 0x38, 0xfb, 0x9b, 0xd9, 0xdf, 0x0a,
	0xba, 0x54, 0x08, 0x96, 0xda, 0x09, 0x8f, 0xd3, 0xd8, 0xfa, 0x63, 0x19, 0x7a, 0x27, 0x99, 0xb8,
	0x3c, 0x7d, 0xe3, 0xb0, 0xab, 0x8c, 0x89, 0x94, 0x98, 0xb0, 0xfa, 0x13, 0xe3, 0xc2, 0x8f, 0x23,
	0xb3, 0xb1, 0xdb, 0xd8, 0xeb, 0x39, 0xb9, 0x48, 0xfe, 0x0f, 0x30, 0xcc, 0xb8, 0x88, 0xb9, 0x1b,
	0x65, 0xa1, 0xb9, 0x8c, 0x8b, 0x86, 0xd2, 0x0c, 0xb2, 0x90, 0x3c, 0x86, 0x35, 0xbd, 0x1c, 0xd0,
	0x73, 0x16, 0x98, 0x4d, 0x34, 0xe8, 0x2a, 0xdd, 0xb1, 0x54, 0x91, 0x3e, 0x74, 0x02, 0xff, 0x82,
	0xa5, 0x7e, 0xc8, 0xcc, 0xd6, 0x6e, 0x63, 0xaf, 0xe5, 0x14, 0x32, 0xd9, 0x86, 0xb6, 0x60, 0x91,
	0xc7, 0xb8, 0xb9, 0xb2, 0xdb, 0xd8, 0x33, 0x1c, 0x2d, 0xc9, 0x3d, 0xc3, 0x38, 0x4a, 0x39, 0x1d,
	0xa6, 0x66, 0x1b, 0x57, 0x0a, 0x59, 0xee, 0x09, 0x59, 0x7a, 0x19, 0x7b, 0xe6, 0xaa, 0xda, 0xa3,
	0x24, 0xb2, 0x09, 0x2b, 0x09, 0xe5, 0x34, 0x34, 0x3b, 0xa8, 0x56, 0x02, 0xb9, 0x07, 0xab, 0xc2,
	0x1f, 0xb9, 0x34, 0x18, 0x99, 0x06, 0xe6, 0xd6, 0x16, 0xfe, 0xe8, 0x20, 0x18, 0x91, 0x07, 0x60,
	0x08, 0x7f, 0x14, 0xd1, 0x34, 0xe3, 0xcc, 0x04, 0xdc, 0x32, 0x51, 0x58, 0x5f, 0xc2, 0xbd, 0xe7,
	0x2c, 0x7d, 0xe6, 0x07, 0xec, 0x2c, 0x09, 0x62, 0xea, 0x9d, 0x39, 0xc7, 0x79, 0xad, 0xfa, 0xd0,
	0x49, 0x62, 0x91, 0x3e, 0x8d, 0xbd, 0x31, 0x16, 0xcb, 0x70, 0x0a, 0xd9, 0x3a, 0x05, 0x73, 0x7a,
	0x9b, 0x48, 0xe2, 0x48, 0x30, 0x42, 0xa0, 0x35, 0x8c, 0x3d, 0xa6, 0x0b, 0x8c, 0xbf, 0xc9, 0x06,
	0x34, 0x43, 0x31, 0xc2, 0xb2, 0x1a, 0x8e, 0xfc, 0x29, 0xad, 0x3c, 0x9a, 0x52, 0x2c, 0xa4, 0xe1,
	0xe0, 0x6f, 0xeb, 0x73, 0xf8, 0x9f, 0xc3, 0x46, 0xbe, 0x48, 0x19, 0x97, 0xae, 0xe7, 0x49, 0xe4,
	0x04, 0x36, 0xab, 0x5b, 0x16, 0x4e, 0xc2, 0x87, 0x9d, 0x57, 0x19, 0xe3, 0x63, 0xf5, 0x61, 0xcc,
	0x3b, 0xa4, 0x29, 0x9d, 0xe9, 0x76, 0x45, 0xbb, 0xfd, 0x44, 0x3b, 0x91, 0x7e, 0xbb, 0xfb, 0xc4,
	0x9e, 0xde, 0x8d, 0xeb, 0x79, 0xf8, 0x66, 0x11, 0xde, 0x8a, 0xe0, 0xee, 0x94, 0xb1, 0x84, 0x68,
	0x42, 0x47, 0x6c, 0x90, 0x85, 0x39, 0x44, 0xb5, 0x28, 0xeb, 0xc0, 0xe3, 0xeb, 0xef, 0xe2, 0x2c,
	0x4a, 0x35, 0x40, 0x0b, 0x99, 0x7c, 0x04, 0x4d, 0x1e, 0x5f, 0x9b, 0xcd, 0xdd, 0xe6, 0x5e, 0x77,
	0xff, 0x6e, 0x35, 0x07, 0x27, 0xbe, 0x76, 0xe4, 0xaa, 0xf5, 0xf7, 0x32, 0x6c, 0xd4, 0x57, 0xa4,
	0xd7, 0x4c, 0x30, 0x1e, 0xd1, 0x90, 0xe5, 0xd5, 0xcd, 0x65, 0x72, 0x1f, 0x8c, 0x0b, 0x3f, 0x60,
	0xee, 0x25, 0x15, 0x97, 0xba, 0x6e, 0x1d, 0xa9, 0xf8, 0x9e, 0x8a, 0xcb, 0x62, 0x11, 0x77, 0x36,
	0x27, 0x8b, 0x83, 0xf2, 0x4e, 0xe1, 0xbf, 0x2d, 0xba, 0x41, 0x2a, 0x5e, 0xfb, 0x6f, 0x19, 0x79,
	0x04, 0x5d, 0x5c, 0x4c, 0xe2, 0xc0, 0x1f, 0x8e, 0x75, 0x4b, 0x80, 0x54, 0x9d, 0xa0, 0xa6, 0x30,
	0x88, 0xb2, 0xf0, 0x9c, 0x71, 0xec, 0x8c, 0x96, 0x32, 0x18, 0xa0, 0x86, 0x3c, 0x00, 0x10, 0x7e,
	0xe8, 0xc6, 0xdc, 0xa5, 0x42, 0x60, 0x7f, 0xf4, 0x9c, 0x8e, 0xf0, 0xc3, 0x97, 0xfc, 0x40, 0x08,
	0xd9, 0x0b, 0x71, 0xe2, 0xa6, 0xe3, 0x84, 0x61, 0x8f, 0xf4, 0x9c, 0x76, 0x9c, 0x9c, 0x8e, 0x13,
	0x26, 0x9b, 0x5c, 0xa4, 0x31, 0x67, 0x2e, 0xf5, 0x3c, 0x8e, 0x7d, 0x22, 0x9b, 0x41, 0x6a, 0x0e,
	0x3c, 0x8f, 0xcb, 0xb0, 0x43, 0xce, 0x68, 0xca, 0x5c, 0x6c, 0x62, 0x50, 0x61, 0x95, 0xea, 0xd4,
	0x0f, 0x99, 0xf5, 0x04, 0xee, 0xe4, 0x68, 0x9b, 0x07, 0x9c, 0xc7, 0xb0, 0x31, 0x31, 0x5f, 0x18,
	0x98, 0x3f, 0xc3, 0x26, 0x1e, 0xde, 0x41, 0x10, 0x1c, 0xc8, 0x21, 0x57, 0xca, 0xe0, 0xc6, 0x03,
	0x94, 0x1f, 0xcc, 0x84, 0x1c, 0x70, 0xae, 0xef, 0xe9, 0x00, 0x86, 0xd6, 0x1c, 0x79, 0xe4, 0x53,
	0x80, 0x2b, 0xe9, 0xd2, 0x95, 0x33, 0x04, 0x83, 0x75, 0xf7, 0x41, 0x81, 0xe7, 0x84, 0x72, 0xea,
	0x18, 0x57, 0xf9, 0x4f, 0xeb, 0x19, 0x18, 0x85, 0x7e, 0x81, 0x90, 0xd6, 0x2b, 0xd8, 0xaa, 0x7d,
	0xc5, 0xc2, 0x85, 0xf9, 0x0c, 0x7a, 0x2f, 0x62, 0xcf, 0xbf, 0x18, 0xcf, 0x73, 0x26, 0x3f, 0xc0,
	0x7a, 0x6e, 0xbc, 0x70, 0x60, 0xa7, 0x36, 0x05, 0x5f, 0xa7, 0x74, 0xae, 0x53, 0xe9, 0x43, 0xd1,
	0x28, 0xe5, 0xae, 0x92, 0xb2, 0x75, 0x06, 0x3b, 0x33, 0x7c, 0x2e, 0x9c, 0xea, 0x4b, 0xd8, 0x7a,
	0xce, 0xd2, 0xc3, 0xf8, 0x3a, 0x3a, 0x9e, 0x9a, 0xf2, 0x1f, 0x94, 0xa7, 0x03, 0xdb, 0x75, 0x87,
	0x0b, 0x27, 0x79, 0xae, 0xc7, 0xd3, 0xd3, 0xf1, 0xd1, 0x61, 0xf9, 0x2c, 0xe9, 0x08, 0xe7, 0x86,
	0x9e, 0xba, 0x85, 0x5c, 0x1e, 0x95, 0xcb, 0xb8, 0x54, 0x8c, 0x4a, 0x13, 0x56, 0x91, 0x08, 0x1c,
	0x1d, 0xea, 0x00, 0xb9, 0x68, 0xfd, 0xd2, 0x80, 0x47, 0xcf, 0x59, 0x7a, 0x26, 0x18, 0x3f, 0xc9,
	0xf8, 0xf0, 0x92, 0x0a, 0x86, 0x38, 0x3c, 0xf6, 0x45, 0xba, 0x58, 0xcc, 0x72, 0x25, 0x9b, 0xb5,
	0x4a, 0xee, 0x40, 0x07, 0x13, 0x90, 0x2d, 0xd1, 0x2a, 0x27, 0xe4, 0x59, 0x09, 0xec, 0xde, 0x9c,
	0xcf, 0xfb, 0x5e, 0x3b, 0xb9, 0x8b, 0xb9, 0xae, 0x9d, 0xb2, 0x71, 0xfd, 0xda, 0x69, 0xdd, 0x7c,
	0xed, 0xb4, 0xde, 0x71, 0xed, 0xe4, 0x6e, 0x8b, 0x6b, 0xe7, 0xcf, 0x86, 0x3e, 0xd7, 0xd2, 0xca,
	0x22, 0x53, 0xab, 0x5c, 0xcc, 0xca, 0xe9, 0x7a, 0xe4, 0x21, 0x74, 0xe5, 0x47, 0xbb, 0x9c, 0x5d,
	0x4d, 0x4a, 0x6d, 0x78, 0x78, 0x85, 0x5f, 0x1d, 0x79, 0x9a, 0x6f, 0x89, 0x2c, 0x2c, 0x98, 0x58,
	0x21, 0x5b, 0xfb, 0xb0, 0x79, 0xc2, 0xd9, 0x6b, 0x1a, 0xb0, 0x41, 0x9c, 0xfa, 0xc3, 0xb9, 0xe8,
	0xc7, 0x2b, 0xd8, 0xaa, 0xed, 0x59, 0xb8, 0x09, 0x7e, 0x6b, 0xc0, 0x1a, 0x56, 0x2b, 0x8f, 0x7f,
	0x1f, 0x0c, 0x79, 0x14, 0xea, 0x2a, 0x55, 0xfe, 0x26, 0x70, 0xdc, 0x51, 0x50, 0x2d, 0x91, 0xd6,
	0xb9, 0xf0, 0xb8, 0x0d, 0x6d, 0x4e, 0x23, 0x2f, 0x0e, 0x75, 0x89, 0xb4, 0x54, 0x25, 0x8b, 0x2b,
	0x75, 0xb2, 0x78, 0x06, 0x3d, 0x9d, 0xd9, 0x2d, 0xb8, 0x7c, 0x58, 0xc1, 0xa5, 0xbe, 0x4d, 0x6e,
	0xc5, 0x23, 0xd5, 0x57, 0x0b, 0xe2, 0xb0, 0xfc, 0x41, 0x35, 0xfe, 0x73, 0x1f, 0x0c, 0x1e, 0x5f,
	0xbb, 0xc3, 0x99, 0x04, 0xe8, 0x41, 0x19, 0x89, 0x60, 0x63, 0x0f, 0x61, 0x54, 0x84, 0xe0, 0x3f,
	0xcb, 0x60, 0x14, 0xaa, 0x0a, 0x80, 0x1a, 0x55, 0x00, 0x95, 0x8b, 0xb6, 0x3c, 0x0d, 0x4b, 0xb5,
	0xad, 0x54, 0x52, 0x03, 0x35, 0x83, 0xca, 0x32, 0x12, 0x8f, 0x56, 0x69, 0x19, 0xb9, 0x87, 0xe4,
	0x34, 0x0c, 0xeb, 0xe8, 0xa6, 0x74, 0x54, 0x90, 0x1e, 0xa5, 0x3a, 0xa5, 0x23, 0x69, 0x20, 0x68,
	0x98, 0xe4, 0x74, 0x4b, 0x3d, 0x07, 0x40, 0xa9, 0x90, 0x70, 0x3d, 0x86, 0x35, 0xc9, 0x55, 0x64,
	0x75, 0xd0, 0x42, 0x3d, 0x0b, 0xba, 0x5a, 0x87, 0x26, 0x8f, 0xa0, 0xcb, 0xde, 0x24, 0x3e, 0xd7,
	0x0c, 0x46, 0xb1, 0x1f, 0x50, 0x2a, 0xc9, 0x60, 0xca, 0xd4, 0xc8, 0xa8, 0x50, 0x23, 0xf9, 0xaa,
	0xe0, 0xfe, 0x30, 0x67, 0x3d, 0x4a, 0x20, 0xbb, 0xd0, 0xf5, 0x98, 0x18, 0x72, 0x3f, 0x49, 0xe5,
	0x9b, 0xa9, 0xab, 0x22, 0x96, 0x54, 0x75, 0xce, 0xb4, 0x36, 0xc5, 0x99, 0x7e, 0x6f, 0x68, 0xde,
	0xf2, 0x62, 0x3c, 0xdd, 0x57, 0xff, 0xed, 0x94, 0xfd, 0x30, 0x54, 0x0f, 0x35, 0x23, 0x99, 0xe4,
	0x77, 0x0b, 0xba, 0x3f, 0xae, 0xa0, 0x7b, 0x43, 0xa1, 0x5b, 0xed, 0xbb, 0x15, 0xe3, 0x3f, 0xc2,
	0x9d, 0x9a, 0xe9, 0x07, 0x12, 0xfd, 0xc7, 0x65, 0x9c, 0xdf, 0x29, 0xc7, 0x2f, 0xe6, 0xed, 0xaf,
	0xcb, 0xb0, 0x5e, 0xd5, 0xbf, 0x8b, 0xe4, 0x47, 0x68, 0x38, 0x19, 0xb6, 0x1d, 0xa5, 0xb8, 0x7d,
	0xd6, 0x56, 0xdb, 0xa1, 0x55, 0x6f, 0x87, 0xda, 0x28, 0x5e, 0xa9, 0x8f, 0x62, 0x0b, 0x7a, 0xc5,
	0x3a, 0x7a, 0x68, 0x6b, 0x70, 0x29, 0x8b, 0x81, 0x26, 0x20, 0xc5, 0xb8, 0x5e, 0xad, 0x8e, 0x6b,
	0x9c, 0x06, 0x8c, 0x7a, 0xee, 0x45, 0x40, 0x47, 0xfa, 0x29, 0xdc, 0x91, 0x8a, 0x67, 0x01, 0xc5,
	0xc1, 0x8a, 0x70, 0x34, 0x10, 0x8e, 0xf8, 0x7b, 0xff, 0xaf, 0x26, 0xac, 0xe0, 0x0c, 0x20, 0xdf,
	0xc0, 0x5a, 0xf9, 0xd1, 0x48, 0x36, 0xed, 0x19, 0xcf, 0xce, 0xfe, 0x96, 0x3d, 0xeb, 0x65, 0x69,
	0x2d, 0x91, 0x6f, 0x67, 0x3d, 0xdb, 0x7a, 0x76, 0x79, 0x68, 0xf7, 0xfb, 0xf6, 0x8d, 0x8f, 0x48,
	0x6b, 0x89, 0x7c, 0x05, 0xbd, 0xdc, 0xb7, 0xca, 0x68, 0xc3, 0xae, 0xbd, 0x2b, 0xfa, 0x77, 0xed,
	0xfa, 0xd3, 0xc1, 0x5a, 0x22, 0x4f, 0x00, 0x14, 0x79, 0xc6, 0x4d, 0xb5, 0x90, 0xeb, 0x76, 0x65,
	0x38, 0x5b, 0x4b, 0xe4, 0x6b, 0xe8, 0x55, 0x6e, 0x27, 0xb2, 0x6e, 0x57, 0xfe, 0x0e, 0xe9, 0x6f,
	0xdb, 0x33, 0x6f, 0x2f, 0xfc, 0xc6, 0x5e, 0xa5, 0x29, 0xc8, 0x96, 0x3d, 0xab, 0x89, 0xfb, 0xdb,
	0xf6, 0xcc, 0xde, 0xb1, 0x96, 0xc8, 0x81, 0x06, 0xe1, 0x8b, 0xb1, 0x8e, 0xf1, 0xde, 0x2e, 0xce,
	0xdb, 0xf8, 0x37, 0xce, 0x17, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xa9, 0x50, 0x03, 0xd5,
	0x11, 0x00, 0x00,
}
