// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	contract.proto

It has these top-level messages:
	DeployRequest
	DeployResponse
	QueryRequest
	QueryResponse
*/
package contract

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployRequest struct {
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DeployResponse struct {
}

func (m *DeployResponse) Reset()                    { *m = DeployResponse{} }
func (m *DeployResponse) String() string            { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()               {}
func (*DeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type QueryRequest struct {
	Contract string `protobuf:"bytes,1,opt,name=contract" json:"contract"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type QueryResponse struct {
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*DeployRequest)(nil), "DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "DeployResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xe2, 0xe7, 0xe2, 0x75, 0x49,
	0x2d, 0xc8, 0xc9, 0xaf, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x12, 0xe0, 0xe2, 0x83,
	0x09, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x69, 0x71, 0xf1, 0x04, 0x96, 0xa6, 0x16, 0xc1,
	0x54, 0x08, 0x49, 0x71, 0x71, 0xc0, 0x0c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x41, 0xc6, 0x41, 0xd5, 0x42, 0x34, 0x1b, 0x25, 0x72, 0x71, 0x38, 0x43, 0x25, 0x85, 0xb4, 0xb9,
	0xd8, 0x20, 0x46, 0x0b, 0xf1, 0xe9, 0xa1, 0x58, 0x2a, 0xc5, 0xaf, 0x87, 0x66, 0x27, 0x83, 0x90,
	0x06, 0x17, 0x2b, 0xd8, 0x24, 0x21, 0x5e, 0x3d, 0x64, 0xdb, 0xa5, 0xf8, 0xf4, 0x50, 0x2c, 0x50,
	0x62, 0x48, 0x62, 0x03, 0xfb, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x69, 0x10, 0xbb, 0x76,
	0xdb, 0x00, 0x00, 0x00,
}
